import type { CourseId } from "./courses";

export type AssessmentQuestion = { prompt: string; choices: string[]; answer: number; feedback: string };
export type CourseAssessment = { pre: AssessmentQuestion[]; post: AssessmentQuestion[]; reflection: string };

export const assessments: Record<CourseId, CourseAssessment> = {
  "ai-fundamentals": {
    pre: [
      { prompt: "Aplikasi musik menyarankan lagu berdasarkan kebiasaan mendengarmu. Apa yang paling mungkin terjadi di balik rekomendasi itu?", choices: ["Sistem mengenali pola dari riwayat lagu dan pilihan pengguna lain", "Editor aplikasi memilih satu daftar lagu yang sama untuk semua orang", "Sistem hanya mengurutkan lagu dari yang paling baru dirilis"], answer: 0, feedback: "AI dapat mengenali pola pada data untuk memperkirakan lagu yang mungkin kamu sukai." },
      { prompt: "AI memberi jawaban yang terdengar yakin, tetapi kamu belum tahu sumbernya. Apa langkah berikut yang paling berguna?", choices: ["Meminta penjelasan lain dari AI yang sama", "Memeriksa klaim penting lewat sumber tepercaya", "Membandingkan panjang jawaban dengan artikel daring"], answer: 1, feedback: "Jawaban yang lancar tetap perlu diperiksa, terutama untuk klaim penting." },
      { prompt: "Dua sistem AI memberi hasil berbeda untuk pertanyaan yang sama. Apa penjelasan yang paling masuk akal?", choices: ["Salah satunya pasti memiliki tujuan pribadi", "Sistem yang lebih baru selalu menghasilkan jawaban benar", "Keduanya dapat memakai data, rancangan, atau konteks yang berbeda"], answer: 2, feedback: "Data, rancangan, dan konteks dapat membuat keluaran sistem berbeda." },
      { prompt: "Kamu melihat fitur pengenal wajah di ponsel. Contoh ini paling tepat menunjukkan bahwa AI dapat…", choices: ["Mengenali pola pada gambar untuk mencocokkan wajah", "Mengetahui identitas seseorang tanpa menerima data", "Menjamin foto selalu menggambarkan keadaan sebenarnya"], answer: 0, feedback: "Sistem pengenal gambar mencari pola visual; hasilnya tetap bisa keliru dan perlu konteks." },
      { prompt: "AI menyusun ringkasan dari banyak artikel. Hal apa yang tetap perlu kamu lakukan?", choices: ["Menganggap ringkasan mewakili semua sudut pandang", "Memeriksa klaim penting dengan sumber aslinya", "Memilih versi paling panjang sebagai yang paling lengkap"], answer: 1, feedback: "Ringkasan bisa melewatkan konteks atau keliru, jadi periksa klaim penting pada sumber." },
    ],
    post: [
      { prompt: "Sebuah aplikasi menyarankan berita yang mirip dengan berita yang sering kamu baca. Penjelasan paling tepat adalah…", choices: ["Sistem menemukan pola dari aktivitas dan memperkirakan berita yang mungkin kamu pilih", "Sistem menyimpulkan alasan pribadi di balik setiap bacaanmu", "Sistem memeriksa kebenaran berita sebelum memasukkannya ke rekomendasi"], answer: 0, feedback: "Rekomendasi menunjukkan kecocokan pola, bukan bukti bahwa isi berita sudah diverifikasi." },
      { prompt: "AI merangkum aturan beasiswa, tetapi satu tanggal tampak janggal. Apa tindakan terbaik?", choices: ["Meminta AI menyebutkan tanggal itu sekali lagi", "Mencocokkan tanggal dengan pengumuman resmi penyelenggara", "Mencari artikel lain yang mengutip ringkasan serupa"], answer: 1, feedback: "Untuk informasi yang berdampak, cocokkan detail dengan sumber primer." },
      { prompt: "Manakah pernyataan yang paling akurat tentang kemampuan AI?", choices: ["AI selalu memahami konteks seperti manusia", "AI dapat menemukan pola, tetapi hasilnya masih perlu dinilai manusia", "AI hanya bekerja jika semua jawabannya sudah ditulis sebelumnya"], answer: 1, feedback: "AI berguna untuk mengenali pola, sementara manusia tetap memeriksa konteks dan dampaknya." },
      { prompt: "AI menyarankan rute perjalanan dari data lalu lintas. Apa yang paling tepat disimpulkan?", choices: ["Saran itu bisa membantu, tetapi kondisi terbaru tetap perlu diperiksa", "Rute itu pasti paling aman karena dipilih oleh AI", "AI mengetahui perubahan jalan sebelum informasinya tersedia"], answer: 0, feedback: "Prediksi membantu mengambil keputusan, tetapi data dan kondisi nyata dapat berubah." },
    ],
    reflection: "Jika AI memberi saran yang memengaruhi keputusanmu, apa satu hal yang akan kamu periksa lebih dulu? Jelaskan alasannya.",
  },
  "working-with-generative-ai": {
    pre: [
      { prompt: "Kamu meminta AI membantu menyusun materi untuk teman sekelas, tetapi hasilnya terlalu teknis. Informasi apa yang paling membantu ditambahkan?", choices: ["Latar pembaca dan bagian yang perlu mereka pahami", "Panjang materi dan jumlah paragraf yang diinginkan", "Daftar istilah teknis yang harus muncul di setiap bagian"], answer: 0, feedback: "Konteks tentang pembaca membantu AI menyesuaikan pilihan kata dan kedalaman penjelasan." },
      { prompt: "AI menyebut data tanpa memberikan sumber. Apa langkah berikut yang paling dapat dipercaya?", choices: ["Meminta AI mengulang angka dengan format tabel", "Meminta nama sumber lalu membuka sumber aslinya untuk mencocokkan klaim", "Membandingkan jawabannya dengan ringkasan dari chatbot lain"], answer: 1, feedback: "Mintalah sumber yang dapat diperiksa, lalu buka dan cocokkan klaimnya." },
      { prompt: "Draf AI sudah dekat dengan kebutuhanmu, tetapi satu bagian meleset. Cara kerja yang paling efektif adalah…", choices: ["Mengganti seluruh prompt dengan instruksi yang lebih panjang", "Meminta AI membuat tiga draf baru tanpa menjelaskan masalahnya", "Menunjuk bagian yang meleset, memberi alasan, dan mempertahankan bagian yang sudah sesuai"], answer: 2, feedback: "Umpan balik spesifik menjaga bagian yang sudah sesuai dan memperbaiki bagian yang meleset." },
      { prompt: "Kamu perlu menulis panduan dari laporan panjang. Cara membagi pekerjaan yang paling membantu adalah…", choices: ["Minta AI mengerjakan seluruh panduan sekaligus tanpa meninjau draf", "Tentukan bagian yang perlu dibuat, lalu tinjau sebelum semuanya digabung", "Gabungkan beberapa ringkasan AI apa adanya"], answer: 1, feedback: "Pekerjaan bertahap memudahkanmu meninjau isi dan memberi koreksi sebelum hasil digabung." },
      { prompt: "Kamu meminta AI mengolah catatan rapat. Batasan mana yang paling berguna untuk menjaga isi tetap akurat?", choices: ["Jangan menambahkan keputusan yang tidak tertulis di catatan", "Gunakan gaya bahasa yang terdengar meyakinkan", "Tambahkan contoh keputusan dari rapat lain"], answer: 0, feedback: "Batasan yang jelas membantu AI membedakan isi sumber dari informasi tambahan." },
    ],
    post: [
      { prompt: "Kamu meminta ringkasan untuk pengurus komunitas yang sibuk. Prompt mana yang memberi konteks paling berguna?", choices: ["Ringkas semua bagian laporan dalam urutan yang sama", "Ringkas temuan utama untuk pengurus nonteknis yang perlu menentukan jadwal kegiatan", "Buat ringkasan singkat dengan gaya profesional"], answer: 1, feedback: "Tujuan dan pembaca membantu AI memilih informasi yang relevan." },
      { prompt: "AI membuat klaim statistik untuk laporan. Apa yang sebaiknya kamu lakukan sebelum memakainya?", choices: ["Cari sumber data dan cocokkan definisi serta angkanya", "Minta AI menambahkan tautan yang mendukung klaim", "Bandingkan angka itu dengan perkiraan umum tentang topiknya"], answer: 0, feedback: "Angka perlu dilacak ke sumber yang dapat dipercaya sebelum dipakai." },
      { prompt: "Setelah dua kali revisi, hasil AI masih belum sesuai. Langkah berikut yang paling membantu adalah…", choices: ["Minta versi yang lebih ringkas dengan nada berbeda", "Berikan contoh arah yang diinginkan, lalu sebutkan bagian yang harus dipertahankan", "Mulai chat baru dan tempelkan hasil yang sama"], answer: 1, feedback: "Contoh dan batasan yang jelas membuat revisi lebih terarah." },
      { prompt: "AI menggabungkan informasi dari catatanmu dan menambahkan satu klaim baru. Apa yang sebaiknya kamu lakukan?", choices: ["Periksa klaim tambahan itu dan tandai informasi yang belum terverifikasi", "Pertahankan klaimnya jika gaya bahasanya sesuai", "Minta AI menghapus semua informasi dari catatanmu"], answer: 0, feedback: "Bedakan informasi yang kamu berikan dari tambahan AI, lalu verifikasi klaim baru." },
    ],
    reflection: "Ceritakan satu tugas yang akan kamu bantu dengan AI. Konteks atau batasan apa yang akan kamu berikan, dan bagian mana yang tetap kamu periksa sendiri?",
  },
  "vibe-coding": {
    pre: [
      { prompt: "Coding agent akan membantu membuat aplikasi kecil. Apa yang paling baik dilakukan sebelum meminta perubahan kode?", choices: ["Berikan daftar perubahan dan minta agent langsung mengedit semua file terkait", "Jelaskan tujuan, lalu minta agent membaca struktur project dan melaporkan rencananya", "Minta agent memilih fitur awal berdasarkan project yang mirip"], answer: 1, feedback: "Tujuan dan pemahaman terhadap project memberi dasar yang lebih aman untuk bekerja." },
      { prompt: "Agent meminta izin menjalankan perintah terminal yang belum kamu pahami. Apa pilihan yang bijak?", choices: ["Izinkan jika agent menjelaskan bahwa perintah itu mempercepat pekerjaan", "Minta agent menjalankan perintah yang sama dari folder lain", "Tinjau perintah dan dampaknya, lalu setujui jika sesuai dengan tugas"], answer: 2, feedback: "Pahami dampak tindakan sebelum memberi izin, khususnya untuk perintah terminal." },
      { prompt: "Halaman aplikasi terlihat benar di laptopmu. Apa pemeriksaan berikut yang paling berguna sebelum dibagikan?", choices: ["Coba alur utama dan periksa tampilan pada ukuran layar lain", "Minta agent memastikan tidak ada bug tanpa mencoba sendiri", "Periksa kode sumber saja karena tampilannya sudah terbuka"], answer: 0, feedback: "Pengujian alur utama dan ukuran layar membantu menemukan masalah yang belum terlihat." },
      { prompt: "Kamu punya ide membuat rencana kegiatan dengan bantuan AI. Prompt awal mana yang paling jelas?", choices: ["Buat rencana kegiatan yang menarik", "Beri ide sebanyak mungkin untuk sebuah acara", "Susun rencana satu hari untuk 30 peserta dengan anggaran terbatas; tandai hal yang perlu dikonfirmasi"], answer: 2, feedback: "Tujuan, batasan, dan hal yang belum pasti memberi AI konteks kerja yang lebih jelas." },
      { prompt: "Apa pembeda paling penting antara AI chat biasa dan coding agent saat bekerja di project?", choices: ["Coding agent dapat memakai alat untuk membaca atau mengubah project jika diberi izin", "Coding agent selalu memakai model AI yang lebih pintar", "AI chat tidak bisa membantu menulis atau menjelaskan kode"], answer: 0, feedback: "Coding agent dapat berinteraksi dengan file dan alat project; tindakannya tetap perlu ditinjau." },
    ],
    post: [
      { prompt: "Agent sudah merangkum project. Sebelum meminta fitur baru, apa langkah yang paling membantu?", choices: ["Minta rencana fitur sambil menganggap ringkasan itu sudah akurat", "Berikan spesifikasi lengkap tanpa memeriksa apa yang agent pahami", "Cocokkan ringkasan dengan tujuan project dan luruskan bagian yang keliru"], answer: 2, feedback: "Pastikan agent memahami struktur dan tujuan sebelum memperluas perubahan." },
      { prompt: "Agent menawarkan menghapus file yang tampak tidak terpakai. Apa yang sebaiknya kamu lakukan?", choices: ["Setujui setelah melihat nama file tidak muncul di halaman utama", "Periksa pemakaian file dan perubahan yang akan dibuat sebelum menyetujui", "Minta agent memindahkannya dulu tanpa memeriksa dependensi"], answer: 1, feedback: "Perubahan file perlu ditinjau dampaknya; coding agent juga bisa keliru." },
      { prompt: "Fitur baru berhasil dibuka, tetapi belum dicoba di ponsel. Kesimpulan terbaik adalah…", choices: ["Uji alur utama dan tata letak pada ukuran layar yang relevan", "Tampilan desktop cukup menjadi acuan untuk semua perangkat", "Periksa prompt agent lagi sebelum menguji aplikasi"], answer: 0, feedback: "Satu tampilan berhasil belum menjamin pengalaman di perangkat dan alur lain." },
      { prompt: "Sebelum mengunggah project ke layanan hosting, hal apa yang perlu diperiksa?", choices: ["Apakah warna dan nama file sudah konsisten", "Apakah API key atau konfigurasi rahasia ikut tersimpan di project", "Apakah agent sudah menyatakan project selesai"], answer: 1, feedback: "Pastikan rahasia project tidak ikut terunggah dan periksa pengaturan deployment." },
    ],
    reflection: "Bayangkan kamu membuat fitur kecil dengan coding agent. Apa yang akan kamu minta, tindakan apa yang perlu kamu tinjau, dan bagaimana kamu menguji hasilnya?",
  },
};
