import type { LessonContent } from "./fundamentals-content";
import type { Activity } from "./activities/types";
import type { SectionPresentation } from "./fundamentals-presentation";
import type { LessonStage } from "./module-one-data";

export const vibeStages: LessonStage[] = [
  { id: "from-chat-to-agent", title: "Dari Copy-Paste ke Coding Agent", area: "Pelajaran 1 / 7", question: "Apa yang berubah saat AI bisa membuka project?", intro: "Satu halaman sederhana bisa membuatmu bolak-balik menyalin kode. Ikuti momen ketika agent mulai bekerja langsung di dalam project." },
  { id: "tools-models", title: "Kenali Alat dan Modelnya", area: "Pelajaran 2 / 7", question: "Alat mana yang cocok untuk kebutuhanmu?", intro: "Kamu sudah punya ide aplikasi. Sekarang pilih alat yang cocok untuk tahapnya dan model yang cukup untuk pekerjaannya." },
  { id: "permissions", title: "Izin dan Cara Kerja Agent", area: "Pelajaran 3 / 7", question: "Tindakan apa yang perlu kamu izinkan?", intro: "Agent ingin mengubah file dan menjalankan perintah. Sebelum menekan setuju, kenali pilihan izin dan cara meminta bantuan sesuai tahap kerja." },
  { id: "project-context", title: "Beri Agent Arah dan Konteks", area: "Pelajaran 4 / 7", question: "Bagaimana agar agent memahami project?", intro: "Ketika permintaanmu hanya ‘buat aplikasi keren’, agent harus menebak banyak hal. Beri arah yang cukup agar rencananya bisa kamu periksa." },
  { id: "setup-and-deploy", title: "Dari Laptop ke Internet", area: "Pelajaran 5 / 7", question: "Apa yang membuat aplikasi bisa diakses orang lain?", intro: "Sebelum membangun, bayangkan temanmu ingin mencoba aplikasi dari laptopnya. Cari tahu mengapa alamat lokal tidak cukup dan apa yang diperlukan untuk membagikannya." },
  { id: "build-project", title: "Bangun Ide, Satu Bagian Dulu", area: "Pelajaran 6 / 7", question: "Bagaimana mengubah ide menjadi aplikasi?", intro: "Sekarang pilih ide kecil yang ingin kamu pakai sendiri. Dari situ, buat versi pertama yang bisa dicoba sebelum menambah fitur lain." },
  { id: "test-and-launch", title: "Uji, Perbaiki, dan Luncurkan", area: "Pelajaran 7 / 7", question: "Kapan project siap dibagikan?", intro: "Tautannya sudah ada. Coba buka dari perangkat lain, cari yang masih janggal, perbaiki, lalu ceritakan keputusan yang kamu ambil selama membuatnya." },
];

const source = (label: string, url: string) => ({ label, url });

export const vibeLessons: LessonContent[] = [
  {
    lead: "Kamu ingin membuat halaman login untuk project kecil. AI chat memberi kode yang tampak siap pakai, tetapi saat dijalankan muncul pesan `Module not found`. Di sini kamu akan melihat apa yang berubah ketika AI bisa membaca project secara langsung.",
    sections: [
      { title: "Dulu: salin, tempel, lalu cari error", paragraphs: ["Awalnya kamu menulis ke AI di browser: ‘Buat halaman login sederhana dengan email, password, dan tombol masuk.’ Setelah kode disalin ke VS Code dan project dijalankan, hasilnya berbeda dari yang tampak di chat:\n\n> Module not found: file yang dicari project tidak ditemukan.", "Kamu kembali ke AI, menyalin perbaikan, menempelkannya, lalu menjalankan project lagi. Proses ini bisa berulang karena AI tidak otomatis mengetahui struktur folder, library, gaya kode, atau hubungan antarfile di project-mu.", "AI chat tetap membantu menulis fungsi, CSS, query, menjelaskan error, bahkan membuat satu file penuh. Namun **kitalah yang menjadi penghubung antara AI dan project**."], },
      { title: "Sekarang: agent dapat bekerja di dalam project", paragraphs: ["Karena error tadi muncul di project, minta agent memeriksanya langsung: ‘Cari penyebab `Module not found` di project ini. Jelaskan file yang terkait dan rencana perbaikannya sebelum mengubah kode.’", "Coding agent dapat membaca file, mencari bagian relevan, membuat rencana, meminta izin, mengubah file, menjalankan perintah, lalu melihat hasilnya. Agent bukan sekadar mengirim potongan kode. Ia memakai alat untuk bekerja langsung pada project.", "Batasnya tetap ada. Agent bisa salah membaca kebutuhan, memilih file, atau membuat bug. Karena itu kita perlu meninjau perubahan dan mencoba aplikasinya."], },
      { title: "Coba bedakan agent dan chat", paragraphs: ["Dari pengalaman menyalin kode dan mencoba agent di project, tindakan apa yang hanya bisa dilakukan cara kedua?"], },
      { title: "Vibe coding: membangun lewat percakapan", paragraphs: ["Cara membangun lewat percakapan seperti contoh halaman login tadi sering disebut **vibe coding**. Istilah itu populer pada 2025 setelah digunakan Andrej Karpathy. Istilah ini punya makna yang cukup longgar. Di kursus ini, kita memakainya sebagai cara membangun software lewat percakapan: jelaskan tujuan, beri konteks, buat rencana, minta AI membantu implementasi, lalu uji, tinjau, dan perbaiki.", "Ini bukan berarti ‘AI kerjakan semuanya, saya tinggal klik Accept’. Kamu tidak harus menjadi programmer sebelum mulai, tetapi tetap perlu tahu apa yang ingin dibuat dan menilai apakah hasilnya bekerja."], sources: [source("Andrej Karpathy · unggahan tentang vibe coding", "https://x.com/karpathy/status/1886192184808149383")] },
      { title: "Peran kita bergeser ke arah dan keputusan", paragraphs: ["Saat menulis kode sendiri, pertanyaannya sering ‘Bagaimana saya menulis fungsi ini?’ Saat memakai coding agent, kita juga perlu bertanya: **‘Apa yang sebenarnya perlu dibuat, batasnya apa, dan bagaimana saya tahu hasilnya benar?’**", "Kamu tetap menentukan kebutuhan, batasan, dan keputusan akhir. Agent dapat membantu memilih cara implementasi; kamu memastikan cara itu sesuai project."], },
      { title: "Kalau kamu belum pernah coding", paragraphs: ["Kalau contoh halaman login tadi terasa teknis, mulai saja dari tujuan project dan hasil yang terlihat di layar. Istilah seperti VS Code, terminal, file project, Git, dan deployment akan muncul bersama contoh penggunaannya.", "Beberapa bagian berikutnya membahas izin alat dan cara agent bekerja lebih rinci. Kamu boleh membacanya perlahan dan kembali setelah mencoba membuat project pertama."], },
    ],
    takeaway: "Saat halaman login gagal, coding agent bisa mencari file yang terkait dan mencoba perbaikan di project. Kamu tetap perlu membaca perubahan dan menjalankan halaman itu sendiri.",
    check: { question: "Apa pembeda utama coding agent dari AI chat biasa?", choices: [
      { label: "Agent dapat menggunakan alat untuk membaca, mengubah, dan menjalankan sesuatu pada project.", feedback: "Benar. Perubahan besarnya adalah akses agent ke konteks project dan alat kerja.", correct: true },
      { label: "Agent selalu memakai model yang paling pintar.", feedback: "Belum tentu. Agent dapat menggunakan berbagai model.", correct: false },
      { label: "Agent tidak membuat kesalahan.", feedback: "Agent tetap bisa membuat bug atau salah memahami instruksi.", correct: false },
    ] },
  },
  {
    lead: "Setelah mencoba kode dari AI chat, kamu mulai mencari alat yang bisa membantu lebih jauh. Ada yang cocok untuk mencari ide, membuat contoh di browser, atau mengubah file project. Pilihannya bergantung pada pekerjaanmu saat itu.",
    sections: [
      { title: "Tiga kelompok alat yang sering ditemui", paragraphs: ["Sebelum memilih alat, lihat dulu tugasmu. Masih mencari bentuk aplikasi? **AI chat** seperti ChatGPT, Claude, atau Gemini bisa diajak bertukar ide, menjelaskan konsep, dan membandingkan pilihan. Biasanya, kita sendiri yang membawa jawabannya ke project.", "Ingin cepat mencoba tampilan dari browser? **AI app builder** seperti Replit Agent atau Lovable dapat membuat prototype dan mengurus sebagian persiapan. Paket gratis biasanya punya batas penggunaan.", "Sudah punya project dengan beberapa file? **AI coding agent** seperti Kilo Code, OpenCode, Codex, Claude Code, atau Cursor dapat bekerja dengan file, repository, terminal, dan alat development."], },
      { title: "Kita memakai Kilo, tetapi pola kerjanya bisa dibawa", paragraphs: ["Kursus ini memakai **Kilo Code** melalui VS Code. Kilo menyediakan agent, pilihan model, permission, petunjuk project, skills, dan MCP. Kita memilihnya sebagai alat latihan, bukan karena semua orang harus memakai Kilo.", "Besok tool-mu mungkin berbeda. Polanya tetap serupa: **tujuan → konteks → rencana → agent memakai alat → tinjau → uji → perbaiki**."], sources: [source("Dokumentasi Kilo Code untuk VS Code", "https://kilo.ai/docs/code-with-ai/platforms/vscode")] },
      { title: "Agent bekerja dalam putaran", paragraphs: ["Misalnya kamu meminta tulisan tombol pada halaman login diganti menjadi ‘Masuk’. Agent membaca permintaan dan konteks, mencari file yang memuat tombol itu, membuat perubahan jika diizinkan, lalu melihat hasilnya.", "Proses berulang ini sering disebut **agent loop**. Agent dapat melanjutkan pekerjaan berdasarkan hasil tindakan sebelumnya sampai tugas selesai atau perlu bertanya lagi."], },
      { title: "Model dan agent bukan hal yang sama", paragraphs: ["**Model** adalah AI yang menghasilkan jawaban dan melakukan penalaran. **Agent** adalah sistem yang menghubungkan model dengan konteks, instruksi, alat, izin, dan environment.", "Analogi sederhananya: model seperti mesin berpikir; agent seperti mesin berpikir yang diberi alat, ruang kerja, dan aturan. Model yang sama bisa terasa berbeda ketika alat dan izin agent-nya berbeda."], },
      { title: "Pilih model sesuai tingkat kesulitan", paragraphs: ["Mengubah tulisan tombol dari ‘Submit’ menjadi ‘Kirim’ tidak sama sulitnya dengan mencari bug yang melibatkan banyak file dan state aplikasi.", "Untuk perubahan sederhana, model yang lebih ringan atau gratis mungkin cukup. Untuk pekerjaan rumit, model yang lebih mampu bisa membantu. Pertimbangkan juga biaya, kecepatan, context window, privasi, dan kemampuan yang dibutuhkan.", "**Benchmark punya konteks.** SWE-bench menguji penyelesaian issue software di repository; LiveCodeBench berfokus pada soal coding; Terminal-Bench menguji penggunaan terminal dan alat. Angka dari satu benchmark tidak otomatis menentukan model terbaik untuk semua tugas. Agent, alat, prompt, environment, dan batas token juga berpengaruh."], sources: [source("SWE-bench", "https://github.com/swe-bench/SWE-bench"), source("LiveCodeBench", "https://github.com/GOTOIA/livecodebench"), source("Terminal-Bench", "https://github.com/harbor-framework/terminal-bench")] },
      { title: "Perlukah model paling mahal?", paragraphs: ["Setelah melihat cara agent bekerja, coba nilai tugas kecil ini: kamu hanya ingin mengganti tulisan satu tombol pada halaman.\n\n**A.** Ya, selalu gunakan model termahal.\n\n**B.** Tidak, model sederhana mungkin cukup."], reveal: { paragraphs: ["**B.** Mengganti tulisan tombol adalah perubahan kecil, jadi model ringan mungkin sudah cukup. Simpan model yang lebih mampu untuk masalah yang menyangkut banyak file dan state."] }, },
      { title: "Auto Free untuk latihan awal", paragraphs: ["Kilo memiliki pilihan **Auto Free** yang mengarahkan permintaan ke model gratis yang tersedia. Model gratis bisa terkena batas penggunaan dan pilihan modelnya dapat berubah.", "Jika ingin semua penggunaan tetap tanpa kredit, pengaturan autocomplete dan model latar belakang juga perlu diperiksa. Perhatikan juga privasi: penyedia model gratis dapat memiliki kebijakan pencatatan data yang berbeda. Jangan kirim data pribadi atau rahasia tanpa memahami kebijakan alat yang kamu pakai."], sources: [source("Kilo · Menggunakan Kilo secara gratis", "https://kilo.ai/docs/getting-started/using-kilo-for-free"), source("Kilo · Model dan provider", "https://kilo.ai/docs/gateway/models-and-providers")] },
    ],
    takeaway: "Jika masih mencari ide, mulai dari chat. Jika perlu memperbaiki file project, gunakan agent. Pilih model yang cukup untuk tugas itu dan lihat kebijakan datanya sebelum mengirim isi project.",
    check: { question: "Kamu hanya ingin mengganti satu label tombol. Apa pilihan yang masuk akal?", choices: [
      { label: "Pakai model sederhana yang cukup untuk tugas kecil itu.", feedback: "Tepat. Kemampuan model perlu disesuaikan dengan kerumitan tugas.", correct: true },
      { label: "Selalu pilih model termahal agar aman.", feedback: "Biaya lebih tinggi tidak selalu memberi manfaat untuk perubahan sederhana.", correct: false },
      { label: "Pilih model dari angka benchmark terbesar saja.", feedback: "Benchmark punya konteks dan tidak mewakili semua jenis pekerjaan.", correct: false },
    ] },
  },
  {
    lead: "Saat membantu memperbaiki halaman login, coding agent meminta izin menjalankan perintah terminal. Sebelum menekan ‘Setuju’, kamu perlu tahu apa yang akan dijalankan dan apa pengaruhnya pada project.",
    sections: [
      { title: "Agent dapat melakukan tindakan", paragraphs: ["Permintaan izin tadi bisa mencakup beberapa langkah: membuka file, mengubah tombol masuk, dan menjalankan aplikasi. Setiap langkah berbeda akibatnya. Membaca file memberinya konteks; mengedit file mengubah project; menjalankan perintah bisa memasang package atau memulai program.", "Karena itu, izin membantu kita memilih tindakan yang boleh langsung berjalan, yang perlu kita setujui, dan yang sebaiknya diblokir."], },
      { title: "Allow, Ask, Deny", paragraphs: ["Di Kilo, permission dapat diatur per alat atau perintah:\n\n**Allow**: tindakan boleh berjalan tanpa bertanya.\n\n**Ask**: agent perlu meminta izin lebih dulu.\n\n**Deny**: tindakan diblokir.\n\nJika tidak ada aturan yang cocok, dokumentasi Kilo menyebut default-nya meminta persetujuan. Pengaturan yang tepat tetap bergantung pada project dan kebijakan tool."], sources: [source("Kilo · Agent Permissions", "https://kilo.ai/docs/customize/agent-permissions"), source("Kilo · Auto-Approving Actions", "https://kilo.ai/docs/getting-started/settings/auto-approving-actions")] },
      { title: "Berikan izin secukupnya", paragraphs: ["Untuk belajar, pendekatan awal yang mudah dipahami: membaca file boleh; perubahan file dan perintah terminal minta persetujuan; tindakan di luar project juga perlu diperiksa.", "Misalnya agent ingin menjalankan `npm install random-ui-library`. Sebelum menyetujui, tanyakan kenapa package baru diperlukan. Bisa jadi memang berguna; bisa juga CSS yang sudah ada sudah cukup.", "Aturan dapat dibuat lebih spesifik: `git status` boleh berjalan, sedangkan perintah yang menghapus file perlu ditolak atau meminta persetujuan. **Approve bukan tombol Next. Itu keputusan.**"], },
      { title: "Pilih mode kerja: Ask, Plan, Code, Debug", paragraphs: ["**Ask** untuk memahami: ‘Jelaskan struktur project ini. Jangan ubah file.’\n\n**Plan** untuk merancang: ‘Saya ingin menambah pencarian. Jangan coding dulu; jelaskan file yang berubah dan cara kerjanya.’\n\n**Code** untuk menerapkan: ‘Implementasikan tahap pertama dari rencana. Jangan ubah bagian lain.’\n\n**Debug** untuk mencari penyebab: ‘Tombol ini tidak bekerja. Cari penyebabnya dan tunjukkan bukti sebelum mengubah kode.’"], },
      { title: "Project belum kamu kenal: mulai dari mana?", paragraphs: ["Setelah memilih izin, kamu masih perlu menentukan pekerjaan pertama agent di project yang belum kamu kenal."], },
    ],
    takeaway: "Sebelum menyetujui perintah tadi, baca apa yang akan dijalankan dan mengapa. Untuk belajar, biarkan agent membaca file; minta persetujuan saat ia akan mengubah atau menjalankan sesuatu.",
    check: { question: "Kamu belum tahu cara kerja project dan ingin menambah fitur pencarian. Apa langkah awal yang paling aman?", choices: [
      { label: "Minta agent menjelaskan project dan menyusun rencana tanpa mengubah file dulu.", feedback: "Benar. Pahami konteks lalu tinjau rencana sebelum implementasi.", correct: true },
      { label: "Minta agent menulis ulang seluruh project.", feedback: "Perubahan besar tanpa memahami project bisa merusak bagian yang sudah bekerja.", correct: false },
      { label: "Izinkan semua perintah supaya lebih cepat.", feedback: "Izin penuh mengurangi kendali atas tindakan agent.", correct: false },
    ] },
  },
  {
    lead: "Sekarang kamu ingin membuat timer belajar sederhana. Permintaan ‘buat aplikasi belajar yang keren’ malah menghasilkan rencana login, database, dan kalender. Kita akan memberi konteks yang cukup agar agent berhenti menebak kebutuhanmu.",
    sections: [
      { title: "Jangan mulai dari ‘buat aplikasi keren’", paragraphs: ["Di rencana agent, akun pengguna, kalender, dan database malah mendapat tempat paling besar. Semua itu masuk akal untuk beberapa aplikasi belajar, tetapi tidak untuk timer yang ingin kamu pakai sore ini. Ia menebak karena tujuan dan batasnya belum kamu ceritakan.\n\n> Rencana agent — Buat akun pengguna, simpan data di database, tambahkan kalender dan pengingat.", "Coba sebutkan siapa yang akan memakai aplikasi, satu masalah yang dibantu, dan fungsi pertama yang perlu bekerja. Untuk fitur besar, lanjutkan dengan **Ide → Kebutuhan → Rencana → Bangun → Uji → Perbaiki**. Untuk mengganti warna tombol, langkah panjang seperti itu tidak perlu."], },
      { title: "Simpan aturan project yang terus berlaku", paragraphs: ["Kalau kamu selalu ingin ‘jangan menambah library tanpa alasan’, ‘jangan ubah file di luar tugas’, atau ‘pastikan tampilan nyaman di ponsel’, aturan itu dapat ditulis di **AGENTS.md**.", "Anggap file ini sebagai petunjuk kerja agent. Contohnya: utamakan solusi sederhana; jelaskan perubahan besar sebelum mengerjakannya; jangan menambah dependency tanpa alasan; setelah perubahan, pastikan aplikasi tetap bisa dijalankan.", "Tidak semua project memerlukannya. Untuk project kecil, satu catatan `PROJECT.md` tentang tujuan, fitur, batasan, dan definisi selesai mungkin cukup. `product-spec.md` atau `architecture.md` berguna jika ukuran project memang membutuhkannya."], sources: [source("Kilo · Custom Instructions", "https://kilo.ai/docs/customize/custom-instructions")] },
      { title: "Skills adalah playbook untuk jenis tugas", paragraphs: ["**AGENTS.md** menyimpan aturan atau konteks project. **SKILL.md** menjelaskan kapan dan bagaimana agent menjalankan jenis pekerjaan tertentu, misalnya membuat interface atau meninjau tulisan.", "Kilo menemukan skills yang tersedia dan memuat isi lengkap saat skill relevan. Banyak skills tidak otomatis lebih baik; pilih yang benar-benar membantu. Aturan atau playbook yang tidak relevan hanya menambah konteks."], sources: [source("Kilo · Skills", "https://kilo.ai/docs/customize/skills")] },
      { title: "MCP menambahkan akses ke alat lain", paragraphs: ["**MCP (Model Context Protocol)** adalah cara menghubungkan agent dengan tools atau layanan tambahan, seperti alat desain, database, dokumentasi, atau pemantauan.", "Analogi sederhananya: AGENTS.md memberi aturan, SKILL.md memberi playbook, MCP memberi akses ke alat. Project pertama tidak perlu MCP kalau belum ada kebutuhan yang jelas."], sources: [source("Kilo · Menggunakan MCP", "https://kilo.ai/docs/automate/mcp/using-in-kilo-code")] },
      { title: "Aktivitas · pilih konteks yang cukup", paragraphs: ["Timer pertamamu belum membutuhkan semua petunjuk dan alat tambahan tadi. Coba pilih apa yang benar-benar membantu agent mengerjakan versi kecilnya."], },
    ],
    takeaway: "Untuk timer itu, tulis siapa penggunanya, satu fungsi utama, dan fitur yang belum diperlukan. Jika aturan yang sama terus dibutuhkan, simpan sebagai petunjuk project.",
    check: { question: "Kapan AGENTS.md paling berguna?", choices: [
      { label: "Saat ada aturan project yang ingin selalu diikuti agent.", feedback: "Tepat. AGENTS.md menyimpan petunjuk yang berulang untuk project.", correct: true },
      { label: "Setiap kali membuat file baru, apa pun ukuran project.", feedback: "Project kecil mungkin belum membutuhkannya.", correct: false },
      { label: "Untuk menyimpan semua kode aplikasi.", feedback: "AGENTS.md berisi instruksi dan konteks, bukan kode aplikasi.", correct: false },
    ] },
  },
  {
    lead: "Sebelum membuat timer belajar, bayangkan ia sudah berjalan di laptopmu. Jika alamat `localhost` kamu kirim ke teman, ia tidak akan melihat aplikasi yang sama. Cari tahu mengapa, lalu pilih cara membagikannya nanti.",
    sections: [
      { title: "Localhost hanya berjalan di perangkatmu", paragraphs: ["Dalam contoh timer tadi, alamat `http://localhost:5173` membuka aplikasi di komputer sendiri. Di laptop temanmu, alamat itu mencari aplikasi di komputernya, bukan di laptopmu.", "Agar temanmu bisa mencoba aplikasi itu nanti, kamu perlu **deployment**: menerbitkannya ke tempat yang dapat diakses lewat URL publik, misalnya `nama-project.vercel.app`."], },
      { title: "Tidak semua aplikasi perlu database", paragraphs: ["Untuk timer belajar yang hanya menyimpan pengaturan di browser, database server belum diperlukan. Hal yang sama berlaku untuk kalkulator, kuis sederhana, portfolio interaktif, atau tracker lokal.", "Database atau backend mulai berguna jika aplikasi butuh login, data lintas perangkat, banyak pengguna, atau penyimpanan online. Supabase adalah salah satu pilihan yang menyediakan PostgreSQL, autentikasi, penyimpanan file, dan API; kita tidak memerlukannya untuk project pertama kecuali ada kebutuhan."], },
      { title: "Jaga API key dan secret", paragraphs: ["Jika nanti aplikasimu terhubung ke layanan luar, kamu mungkin menerima API key atau kredensial. Jangan menaruh informasi rahasia itu di kode frontend atau repository publik.", "Aplikasi biasanya memakai **environment variables** untuk mengatur nilai rahasia. Untuk sekarang cukup ingat: jangan mengunggah secret ke GitHub atau menaruhnya di kode yang dikirim ke browser."], },
      { title: "Setup Kilo untuk latihan", paragraphs: ["Setelah tahu kebutuhan project dan jalur untuk membagikannya, siapkan alat latihannya. Kursus ini menggunakan extension Kilo di VS Code: buka Extensions, cari Kilo Code, pasang extension yang tersedia, lalu buka dari sidebar. Dokumentasi dan tampilan dapat berubah, jadi ikuti petunjuk pemasangan resmi terbaru.", "Kalau lebih nyaman memakai terminal, Kilo juga menyediakan CLI melalui `npm install -g @kilocode/cli`, lalu perintah `kilo`. Untuk project berbasis React atau framework lain, Node.js mungkin diperlukan.", "Latihan kita menggunakan Auto Free jika tersedia. Biarkan membaca file; minta persetujuan untuk edit dan perintah terminal. Autocomplete bersifat opsional. Setiap model memiliki aturan biaya dan privasinya sendiri. Periksa pengaturannya sebelum mengirim data."], sources: [source("Kilo · Extension VS Code", "https://kilo.ai/docs/code-with-ai/platforms/vscode"), source("Kilo · CLI", "https://kilo.ai/docs/code-with-ai/platforms/cli"), source("Kilo · Menggunakan Kilo secara gratis", "https://kilo.ai/docs/getting-started/using-kilo-for-free")] },
      { title: "Perlukah timer memakai database?", paragraphs: ["Kamu ingin membuat timer belajar pribadi yang menyimpan pengaturan di browser perangkat yang sama. Apakah database online wajib?"], reveal: { paragraphs: ["**Tidak.** Mulai dengan solusi lokal yang sederhana; tambah database jika kebutuhan berubah."] }, },
    ],
    takeaway: "Jika temanmu perlu mencoba aplikasi, terbitkan ke URL publik dan buka tautannya dari perangkat lain. Timer sederhana bisa berjalan tanpa database; simpan kunci rahasia di luar kode yang dibagikan.",
    check: { question: "Timer belajar sederhana hanya perlu menyimpan pengaturan di satu browser. Apa pilihan awal yang masuk akal?", choices: [
      { label: "Mulai tanpa database server; simpan lokal bila sesuai kebutuhan.", feedback: "Benar. Tidak semua aplikasi perlu database online.", correct: true },
      { label: "Selalu pasang Supabase sejak awal.", feedback: "Database menambah bagian yang perlu dikonfigurasi dan dirawat.", correct: false },
      { label: "Tulis API key di file JavaScript supaya mudah ditemukan.", feedback: "Secret tidak boleh ditaruh di kode publik.", correct: false },
    ] },
  },
  {
    lead: "Setelah memahami alat dan cara membagikan hasilnya, kamu siap membuat timer belajar sendiri. Versi pertama cukup punya satu layar untuk memulai dan menjeda waktu. Kamu bisa menambah fitur setelah mencoba versi kecil itu.",
    sections: [
      { title: "Tentukan ide sebelum membuka coding agent", paragraphs: ["Pikirkan satu hal kecil yang ingin kamu pakai minggu ini. Mungkin timer untuk sesi belajar, kuis untuk mengulang materi, atau halaman untuk acara kampus. Bayangkan kapan kamu akan membukanya dan apa yang ingin kamu lakukan di sana.", "Ide lain juga boleh: kalkulator pengeluaran, flashcard, portfolio, atau permainan mini. Pilih sesuatu yang bisa dicoba orang lain, lalu tentukan satu fungsi yang membuatnya berguna."], },
      { title: "Langkah 1 · jelaskan versi pertama", paragraphs: ["Sebelum agent menulis kode timer, jelaskan empat hal: **apa yang dibuat, siapa yang akan menggunakannya, apa 2-4 fungsi utama, dan apa yang belum perlu dibuat**. Deskripsinya boleh singkat.", "Minta AI membantu merapikan kebutuhan kalau perlu. Pastikan versi pertama tetap kecil dan bisa dicoba."], },
      { title: "Langkah 2-3 · minta agent memahami dan merencanakan", paragraphs: ["Buka project di VS Code, lalu gunakan Ask atau Plan: ‘Saya ingin membuat aplikasi berikut. Bantu merancang versi pertama yang sederhana. Jangan coding dulu. Jelaskan fitur minimum, struktur project, dan urutan implementasinya. Hindari fitur yang tidak diperlukan.’", "Baca rencana itu. Kalau terlalu rumit, minta agent menyederhanakannya. Untuk project sederhana, aturan tambahan boleh dilewati. Jika memakai AGENTS.md, cukup tulis beberapa aturan yang benar-benar penting."], },
      { title: "Langkah 4-5 · bangun bagian terkecil", paragraphs: ["Jangan minta ‘buat semuanya’. Mulai dari tampilan utama atau fungsi inti, jalankan, lalu lihat hasilnya. Setelah itu minta kemampuan nyata satu per satu: tombol bekerja, timer berjalan, data bisa ditambahkan, nilai dihitung, quiz bisa dijawab, atau kartu bisa difilter.", "Setelah tiap perubahan, lihat file yang berubah dan coba fitur tersebut. Minta agent menjelaskan perubahan penting dengan kata-kata sederhana."], },
      { title: "Bagian mana yang dibuat lebih dulu?", paragraphs: ["Rencana sudah ada. Sekarang tentukan bagian mana yang dibangun lebih dulu."], },
    ],
    takeaway: "Minta agent membuat timer yang bisa dimulai dan dijeda. Jalankan hasilnya dulu; penilaianmu setelah mencoba akan memberi arah yang lebih baik untuk fitur berikutnya.",
    check: { question: "Kamu mulai membuat study planner. Bagaimana membatasi versi pertama?", choices: [
      { label: "Tentukan pengguna, dua sampai empat fungsi utama, dan fitur yang belum diperlukan.", feedback: "Tepat. Batas yang jelas membantu agent tidak menebak terlalu banyak.", correct: true },
      { label: "Minta agent membuat semua fitur yang mungkin berguna.", feedback: "Permintaan terbuka mendorong asumsi dan fitur berlebihan.", correct: false },
      { label: "Mulai menambah database, login, dan pembayaran sebelum ada kebutuhan.", feedback: "Komponen itu menambah kerumitan jika project belum memerlukannya.", correct: false },
    ] },
  },
  {
    lead: "Timer belajarmu sudah bekerja di laptop. Sebelum dibagikan, coba tampilan sempit seperti layar ponsel dan lihat apakah tombolnya mudah dipakai. Setelah masalah penting diperbaiki, barulah terbitkan dan uji tautannya.",
    sections: [
      { title: "Langkah 6-8 · uji, perbaiki, dan review", paragraphs: ["Sebelum aplikasi diterbitkan, sempitkan jendela browser ke ukuran ponsel. Coba mulai, jeda, lalu refresh halaman. Bagaimana kalau kamu mengetik angka yang tidak biasa atau menyentuh tombol dengan satu tangan? Percobaan seperti ini sering menemukan masalah yang tidak terlihat dari kode saja.", "Pilih satu hal yang membingungkan atau rusak. Ceritakan langkah untuk memunculkannya kepada agent, lalu minta ia mencari penyebab dan memperbaikinya tanpa merusak bagian yang sudah bekerja.", "Sebelum membagikan tautan, coba lagi fungsi utamanya. Lihat apakah ada error atau perubahan yang tidak diperlukan. Jika kamu belum paham satu bagian penting, minta agent menjelaskan mengapa bagian itu ada."], },
      { title: "Langkah 9 · deploy dengan jalur yang sesuai", paragraphs: ["Jalur paling sederhana adalah **Vercel Drop**: unggah file atau folder lewat browser, pilih nama project, lalu deploy. Vercel dapat mendeteksi framework tertentu dan memberi URL publik. Setelah itu buka URL dari perangkat lain dan uji kembali.", "Jika ingin menyimpan kode sebagai portfolio, gunakan jalur **GitHub → Vercel**. Repository GitHub bukan syarat agar project selesai; yang penting project bisa dibuka dan dicoba. Keberhasilan deploy juga belum membuktikan semua fitur benar."], sources: [source("Vercel · Vercel Drop", "https://vercel.com/changelog/vercel-drop"), source("Kilo · dokumentasi resmi", "https://kilo.ai/docs")] },
      { title: "Tautan yang benar-benar bisa dibuka", paragraphs: ["Sekarang kirim tautannya kepada satu teman. Jika ia bisa membuka timer dan menekan tombol mulai serta jeda dari perangkatnya sendiri, versi pertama sudah mencapai tujuanmu. Catat masalah yang ia temukan untuk perbaikan berikutnya."], },
      { title: "Refleksi singkat", paragraphs: ["Sebelum menutup project, catat apa yang kamu buat dan siapa yang mencobanya. Bagian mana yang paling banyak dibantu AI? Keputusan apa yang kamu ambil sendiri? Apa yang berubah setelah melihat hasil uji di ponsel?\n\nCatatan ini membantumu mengingat alasan di balik versi pertama, bukan sekadar daftar file yang dihasilkan."], },
      { title: "Opsional · ceritakan project-mu", paragraphs: ["Setelah tautannya bekerja, kamu boleh memilih siapa yang akan melihatnya. Kirim kepada teman atau dosen untuk mendapat masukan; jika sudah nyaman, masukkan ke portfolio atau bagikan lebih luas.", "Ceritakan apa yang kamu buat, kenapa memilih ide itu, bagaimana AI membantu, keputusan apa yang tetap kamu buat sendiri, dan apa yang dipelajari. Sertakan tautan live; repository GitHub boleh ditambahkan jika ada. Ceritanya tetap ceritamu, meski AI membantu merapikan tulisan."], },
      { title: "Ke mana melangkah setelah ini?", paragraphs: ["Kalau project berikutnya butuh data lintas perangkat atau banyak pengguna, pelajari database online seperti Supabase dan autentikasi. API dapat menghubungkan aplikasi dengan cuaca, peta, AI, atau layanan lain.", "Git dan GitHub membantu menyimpan riwayat versi dan bekerja bersama. Testing membantu memeriksa perilaku dengan cara yang sistematis. MCP, custom agents, dan skills dapat memperluas alat atau menyesuaikan alur agent saat memang diperlukan."], },
      { title: "Prinsip yang dibawa pulang", paragraphs: ["Timer tadi dimulai dari kebutuhan sederhana, bukan daftar fitur. Setiap kali agent mengusulkan sesuatu, kamu memutuskan apakah itu membantu pengguna dan bagaimana cara memeriksanya.", "Alat dan model akan berubah. Kebiasaan yang tetap berguna ialah menjelaskan tujuan, membaca rencana, mencoba hasilnya, lalu memperbaiki hal yang benar-benar mengganggu orang yang memakai aplikasi.", "Sekarang kamu punya sesuatu yang bisa dibuka orang lain. Itu lebih berarti daripada sekadar menerima kode yang tampak selesai di layar chat."], },
    ],
    takeaway: "Perbesar tombol jeda, coba lagi di ponsel, lalu minta temanmu menguji tautan yang sama. Ceritakan apa yang kamu ubah setelah melihat cara orang lain memakainya.",
    check: { question: "Deployment berhasil dan kamu mendapat URL. Apa langkah berikutnya?", choices: [
      { label: "Buka URL dari perangkat lain, uji fitur, lalu catat hal yang perlu diperbaiki.", feedback: "Benar. URL live belum memastikan semua fungsi bekerja.", correct: true },
      { label: "Anggap semua fitur pasti benar karena deployment sukses.", feedback: "Deployment hanya menerbitkan aplikasi, bukan memverifikasi setiap fungsi.", correct: false },
      { label: "Hapus project lokal karena sudah online.", feedback: "Project lokal tetap dibutuhkan untuk perubahan berikutnya.", correct: false },
    ] },
  },
];

const p = (kind: SectionPresentation["kind"], label: string, title: string, items: { title: string; detail: string }[], bridge: string, interactive = false, activity?: Activity, visual?: SectionPresentation["visual"]): SectionPresentation => ({ kind, label, title, items, bridge, interactive, activity, visual });

export const vibePresentations: SectionPresentation[][] = [
  [
    p("steps", "ALUR LAMA", "Salin → Tempel → Jalankan → Ulangi", [{ title: "AI di browser", detail: "Menjawab dari konteks yang kita kirim." }, { title: "VS Code", detail: "Kita sendiri mencari file dan memindahkan kode." }, { title: "Error", detail: "Kembali ke AI, tempel pesan error, lalu coba lagi." }], "Coding agent dapat bekerja lebih dekat dengan project."),
    p("steps", "ALUR BARU", "Agent membaca dan bertindak di project", [{ title: "Pahami", detail: "Baca struktur dan kode project." }, { title: "Rencanakan", detail: "Tentukan file dan langkah yang relevan." }, { title: "Minta izin", detail: "Tunggu persetujuan sebelum tindakan tertentu." }, { title: "Kerjakan", detail: "Edit file atau jalankan perintah sesuai izin." }, { title: "Periksa", detail: "Lihat hasil dan lanjutkan bila masih ada pekerjaan." }], "Pilih jawaban pada checkpoint untuk membedakan agent dari chat biasa.", true),
    p("compare", "CHECKPOINT 1", "Apa yang membedakan coding agent?", [], "Vibe coding menggunakan percakapan untuk membangun, menguji, dan memperbaiki software.", false, { kind: "predict", prompt: "Apa yang membedakan coding agent dari AI chat biasa?", options: [{ label: "Agent selalu memakai AI yang lebih pintar.", correct: false, feedback: "Modelnya bisa sama persis. Yang berbeda adalah apa yang boleh dilakukannya." }, { label: "Agent dapat memakai alat untuk membaca, mengubah, dan menjalankan sesuatu pada project.", correct: true, feedback: "Tepat. Akses ke alat dan file itulah bedanya." }, { label: "Agent tidak pernah membuat bug.", correct: false, feedback: "Agent tetap bisa membuat bug. Justru karena itu hasilnya perlu kamu uji." }], reveal: "Coding agent bukan model yang lebih pintar, melainkan model yang diberi alat dan izin. Itu sebabnya izin dan pemeriksaan jadi bahasan penting di kursus ini." }),
    p("steps", "CARA KERJA KURSUS", "Tujuan → Konteks → Rencana → Bangun → Uji", [{ title: "Percakapan", detail: "Jelaskan kebutuhan dan batasan." }, { title: "Agent", detail: "Membantu membuat perubahan pada project." }, { title: "Manusia", detail: "Meninjau, menguji, dan menentukan apakah hasil sesuai." }], "Kita tidak perlu menjadi programmer lebih dulu, tetapi perlu tetap terlibat."),
    p("compare", "PERAN KITA", "Arahkan kebutuhan, nilai hasilnya", [{ title: "Kamu menentukan", detail: "Requirement, batasan, dan standar hasil yang benar." }, { title: "Agent membantu", detail: "Memilih cara implementasi dan membuat perubahan pada project." }], "Kursus ini menyediakan jalur utama dan bahasan opsional yang lebih teknis."),
    p("statement", "SATU KURSUS, DUA TINGKAT", "Semua orang bisa mulai", [{ title: "Jalur utama", detail: "Pengalaman coding tidak diperlukan untuk mengikuti konsep dasarnya." }, { title: "Lebih Dalam (Opsional)", detail: "Bahasan teknis dapat dipelajari bertahap oleh yang ingin mendalami coding agent." }], "Selanjutnya, kita lihat pilihan alat dan model yang tersedia."),
  ],
  [
    p("tiles", "PETA ALAT", "Pilih alat sesuai pekerjaan", [{ title: "AI chat", detail: "Untuk bertukar ide, memahami konsep, menyusun kebutuhan, dan membandingkan pilihan." }, { title: "AI app builder", detail: "Untuk membuat prototype dari browser dengan persiapan yang lebih ringan." }, { title: "AI coding agent", detail: "Untuk bekerja dengan file, repository, terminal, dan project development." }], "Kursus ini memakai Kilo sebagai contoh coding agent."),
    p("compare", "ALAT LATIHAN", "Kilo sekarang, pola yang bisa dibawa", [{ title: "Kilo Code", detail: "Dipakai melalui VS Code, dengan pilihan model, izin, aturan project, skills, dan MCP." }, { title: "Tool lain", detail: "OpenCode, Codex, Claude Code, Cursor, dan alat lain dapat punya interface berbeda." }, { title: "Pola umum", detail: "Tujuan → konteks → rencana → alat → tinjau → uji → perbaiki." }], "Agent memakai alat dalam putaran yang berulang."),
    p("steps", "AGENT LOOP", "Dari permintaan ke tindakan", [{ title: "Baca request", detail: "Pahami tugas dan konteksnya." }, { title: "Pilih tool", detail: "Tentukan alat yang tepat untuk membaca atau mengubah project." }, { title: "Lakukan", detail: "Ambil tindakan jika diizinkan." }, { title: "Lihat hasil", detail: "Gunakan hasilnya untuk memilih langkah berikutnya." }], "Agar jelas, pisahkan model dari agent yang menggunakannya.", false, undefined, { layout: "diagram", diagram: { id: "agent-loop", caption: "Putaran inilah yang membedakan agent dari chat: ia bertindak, lalu kamu yang memeriksa hasilnya." } }),
    p("compare", "DUA ISTILAH", "Model ≠ agent", [{ title: "Model", detail: "AI yang melakukan penalaran dan menghasilkan jawaban." }, { title: "Agent", detail: "Sistem yang memberi model konteks, alat, izin, dan environment." }], "Pilih kemampuan model sesuai beban tugas."),
    p("tiles", "SESUAIKAN DENGAN TUGAS", "Sederhana atau kompleks?", [{ title: "Perubahan kecil", detail: "Ganti label tombol: model ringan mungkin sudah cukup." }, { title: "Bug lintas file", detail: "Masalah pada banyak file dan state mungkin butuh model lebih mampu." }, { title: "Bandingkan", detail: "Biaya, kecepatan, context window, privasi, dan benchmark." }, { title: "Checkpoint 2", detail: "Tugas kecil tidak otomatis memerlukan model paling mahal." }], "Benchmark mengukur jenis pekerjaan tertentu, bukan semua kemampuan sekaligus.", true),
    p("compare", "BACA BENCHMARK DENGAN KONTEKS", "Tes berbeda, ukuran berbeda", [{ title: "SWE-bench", detail: "Dekat dengan penyelesaian issue software pada repository." }, { title: "LiveCodeBench", detail: "Berfokus pada pemecahan soal coding." }, { title: "Terminal-Bench", detail: "Melihat kemampuan agent menggunakan terminal dan tools." }], "Untuk latihan, Auto Free dapat membantu. Tetap periksa batas dan kebijakan datanya."),
    p("statement", "PILIHAN LATIHAN", "Auto Free dapat berubah", [{ title: "Perhatikan", detail: "Model gratis bisa terkena batas penggunaan. Untuk bebas kredit, cek juga pengaturan autocomplete dan model latar belakang. Jangan kirim data rahasia tanpa memahami kebijakan provider." }], "Berikutnya, kita bahas tindakan apa saja yang perlu mendapat izin."),
  ],
  [
    p("statement", "AGENT BISA BERTINDAK", "Izin menjaga kita tetap tahu", [{ title: "Contoh tindakan", detail: "Membaca file, mengedit project, menjalankan command, atau memasang package." }], "Tentukan tindakan mana yang boleh, perlu persetujuan, atau diblokir."),
    p("tiles", "ALLOW · ASK · DENY", "Tiga tingkat izin", [], "Untuk belajar, minta persetujuan untuk perubahan dan command.", false, undefined, { layout: "diagram", diagram: { id: "permission-gate", caption: "Setiap tindakan agent lewat salah satu dari tiga jalur ini. Ask adalah jalur yang menjaga keputusan tetap di tanganmu." } }),
    p("compare", "SEBELUM MENYETUJUI", "Periksa alasan tindakan", [{ title: "npm install random-ui-library", detail: "Tanyakan kenapa package baru diperlukan." }, { title: "git status", detail: "Perintah baca status dapat dibuat boleh jika sesuai aturan project." }, { title: "Menghapus file", detail: "Pahami target dan dampaknya sebelum memberi izin." }], "Pilih cara kerja agent sesuai tujuanmu."),
    p("tiles", "EMPAT MODE KERJA", "Ask · Plan · Code · Debug", [{ title: "Ask", detail: "Memahami project. Jangan ubah file." }, { title: "Plan", detail: "Merencanakan fitur. Jangan coding dulu." }, { title: "Code", detail: "Menerapkan satu tahap dari rencana." }, { title: "Debug", detail: "Mencari penyebab dan bukti sebelum mengubah kode." }], "Kalau belum tahu project-nya, mulai dari memahami."),
    p("compare", "CHECKPOINT 3", "Project belum kamu kenal", [], "Setelah agent memahami project, jelaskan tujuan dan konteksnya.", false, { kind: "predict", prompt: "Kamu belum tahu cara kerja sebuah project. Langkah pertama yang lebih aman?", options: [{ label: "Langsung minta AI menulis ulang semuanya.", correct: false, feedback: "Berisiko mengubah bagian yang sebenarnya tidak perlu, dan kamu tidak punya dasar untuk memeriksanya." }, { label: "Minta AI menjelaskan project terlebih dahulu.", correct: true, feedback: "Tepat. Pahami struktur dan tugasnya sebelum merencanakan perubahan." }], reveal: "Menulis ulang tanpa memahami membuat kamu kehilangan kemampuan menilai hasilnya. Penjelasan lebih dulu adalah investasi, bukan langkah tambahan." }),
  ],
  [
    p("compare", "RUMIT SESUAI KEBUTUHAN", "Ide → Requirement → Plan → Build", [{ title: "Perubahan kecil", detail: "Warna tombol mungkin dapat langsung diubah." }, { title: "Fitur baru", detail: "Rencana membantu memeriksa kebutuhan dan file yang perlu berubah." }, { title: "Aplikasi besar", detail: "Pecah pekerjaan; jangan mulai dari ‘buat semuanya’." }], "Aturan yang terus berlaku bisa disimpan di project."),
    p("steps", "AGENTS.MD", "Petunjuk kerja untuk agent", [{ title: "Contoh aturan", detail: "Utamakan solusi sederhana; jangan tambah dependency tanpa alasan; batasi perubahan pada tugas." }, { title: "Tidak wajib", detail: "Project kecil mungkin cukup punya catatan PROJECT.md yang ringkas." }, { title: "Dokumen lain", detail: "Product spec atau architecture docs berguna jika ukuran project membutuhkannya." }], "Aturan project berbeda dari playbook untuk jenis pekerjaan tertentu."),
    p("compare", "AGENTS.MD DAN SKILL.MD", "Aturan project dan playbook", [{ title: "AGENTS.md", detail: "Menyimpan aturan atau konteks yang berlaku di project." }, { title: "SKILL.md", detail: "Menjelaskan kapan dan bagaimana menjalankan jenis pekerjaan tertentu." }, { title: "Pilih yang relevan", detail: "Skill yang tidak diperlukan hanya menambah konteks." }], "MCP memberi agent akses ke tool atau layanan tambahan."),
    p("tiles", "MCP", "Akses ke layanan tambahan", [{ title: "Contoh", detail: "Alat desain, database, dokumentasi, atau pemantauan." }, { title: "Ingat", detail: "Untuk project pertama, MCP tidak wajib." }], "Pilih kebutuhan dulu; jangan menambah integrasi tanpa alasan."),
    p("compare", "AKTIVITAS", "Quiz kecil tanpa login", [], "Sekarang lihat bagaimana project bisa berpindah dari laptop ke internet.", false, { kind: "predict", prompt: "Kamu membuat quiz kecil tanpa login. Apa yang perlu diminta lebih dulu?", options: [{ label: "Tambahkan database, autentikasi, lima skills, dan integrasi MCP.", correct: false, feedback: "Semua itu membuat project lebih rumit daripada yang diminta, dan tiap tambahan jadi hal baru yang harus kamu periksa." }, { label: "Minta fitur inti dan tampilan ponsel; tambahkan layanan lain hanya jika kebutuhannya muncul.", correct: true, feedback: "Tepat. Mulai dari yang bisa dijalankan, lalu tumbuhkan sesuai kebutuhan nyata." }], reveal: "Konteks yang membantu tugas berbeda dari semua kemungkinan yang tersedia. Tambahkan yang pertama, tahan yang kedua." }),
  ],
  [
    p("compare", "LOKAL DAN PUBLIK", "Localhost hanya di laptopmu", [{ title: "localhost:5173", detail: "Alamat ini membuka aplikasi yang berjalan di komputer sendiri." }, { title: "Deployment", detail: "Menerbitkan aplikasi agar dapat diakses pengguna melalui URL publik." }], "Sebelum memilih layanan, tentukan apakah aplikasi butuh data online."),
    p("compare", "DATABASE ATAU TIDAK?", "Tidak semua aplikasi perlu server", [{ title: "Tanpa database", detail: "Pomodoro, calculator, quiz, portfolio, random generator, atau tracker lokal." }, { title: "Database mungkin perlu", detail: "Login, data lintas perangkat, banyak pengguna, atau data online." }, { title: "Supabase", detail: "Salah satu opsi untuk PostgreSQL, autentikasi, storage, dan API." }], "Rahasiakan key dan kredensial yang memberi akses ke layanan."),
    p("statement", "JAGA SECRET", "Jangan unggah API key ke kode publik", [{ title: "Environment variables", detail: "Cara umum menyimpan konfigurasi rahasia di luar kode yang dikirim ke browser." }], "Setelah konsep dasarnya, kita bisa menyiapkan Kilo untuk latihan."),
    p("steps", "SETUP KILO", "Extension utama, CLI sebagai pilihan", [{ title: "VS Code", detail: "Cari Kilo Code di Extensions, pasang, lalu buka dari sidebar. Ikuti instruksi pemasangan resmi terbaru." }, { title: "CLI", detail: "Alternatif terminal: pasang @kilocode/cli dan jalankan `kilo`." }, { title: "Node.js", detail: "Diperlukan untuk menjalankan project yang memakai framework tertentu, seperti React." }], "Pilih model dan izin dengan memperhatikan penggunaan dan privasi."),
    p("tiles", "PENGATURAN LATIHAN", "Mulai dengan kendali yang jelas", [{ title: "Model", detail: "Gunakan Auto Free jika tersedia; periksa batas dan kebijakan provider." }, { title: "Permission", detail: "Membaca boleh; edit dan terminal sebaiknya meminta persetujuan." }, { title: "Autocomplete", detail: "Opsional. Pengaturan modelnya dapat terpisah dari agent utama." }], "Sekarang semua bekal utama sudah siap untuk membuat project."),
  ],
  [
    p("tiles", "PILIH IDE", "Apa yang ingin kamu buat?", [{ title: "Belajar", detail: "Pomodoro, study planner, quiz, flashcard, atau GPA calculator." }, { title: "Keseharian", detail: "Expense calculator, habit tracker, book tracker, atau random meal picker." }, { title: "Karya pribadi", detail: "Portfolio interaktif, event website, mini game, mood journal lokal, atau idemu sendiri." }], "Tentukan fungsi kecil yang membuat ide itu berguna."),
    p("steps", "LANGKAH 1", "Tulis definisi versi pertama", [], "Minta agent merapikan ide, tetapi jangan minta coding dulu.", false, { kind: "promptLab", task: "Tulis definisi versi pertama project-mu", startPrompt: "Saya mau membuat aplikasi study planner.", checks: [{ id: "siapa", label: "Menyebut siapa penggunanya", pattern: "untuk (mahasiswa|siswa|pengguna|saya|teman|dosen|guru|tim)|pengguna(nya)? (adalah|utama)", hint: "Sebutkan siapa yang akan memakainya." }, { id: "fungsi", label: "Menyebut 2-4 fungsi inti", pattern: "(fungsi|fitur)[\\s\\S]*(dan|,)|(menambah|menyimpan|menampilkan|mencatat|mengingatkan)[\\s\\S]*(menambah|menyimpan|menampilkan|mencatat|mengingatkan)", hint: "Sebut minimal dua kemampuan inti, bukan satu daftar panjang." }, { id: "batas", label: "Menyebut yang belum perlu dibuat", pattern: "belum perlu|tidak perlu|tanpa (login|akun|database)|nanti saja|di luar (lingkup|cakupan)", hint: "Sebutkan satu hal yang sengaja belum dibuat di versi pertama." }], outputs: { weak: "Agent menebak sendiri fitur, pengguna, dan teknologinya, lalu membangun sesuatu yang lebih besar dari kebutuhanmu.", strong: "Agent mengusulkan rencana yang bisa kamu periksa: fungsi yang kamu sebut, untuk pengguna yang kamu sebut, tanpa bagian yang sudah kamu keluarkan." } }),
    p("steps", "LANGKAH 2-3", "Pahami project dan baca rencana", [{ title: "Ask atau Plan", detail: "Minta fitur minimum, struktur project, dan urutan implementasi." }, { title: "Tinjau", detail: "Baca rencana. Jika terlalu rumit, minta disederhanakan." }, { title: "Rules bila perlu", detail: "Pakai beberapa aturan penting; project sederhana boleh melewatinya." }], "Mulai implementasi dari bagian terkecil yang terlihat."),
    p("steps", "LANGKAH 4-5", "Bangun tampilan, lalu fungsi", [{ title: "Tampilan utama", detail: "Minta satu bagian UI, jalankan aplikasi, lalu lihat hasilnya." }, { title: "Fungsi inti", detail: "Tambahkan timer, input data, kalkulasi, jawaban quiz, atau filter satu per satu." }, { title: "Periksa perubahan", detail: "Lihat file yang berubah dan minta penjelasan bagian penting." }], "Checkpoint ini membandingkan dua cara memulai.", true),
    p("compare", "CHECKPOINT", "Apa yang dibuat lebih dulu?", [], "Setelah fungsi inti dibuat, ujilah sendiri di berbagai keadaan.", false, { kind: "predict", prompt: "Untuk membuat study planner, langkah pertama mana yang lebih mudah diperiksa?", options: [{ label: "Minta semua fitur selesai sekaligus.", correct: false, feedback: "Kalau ada yang rusak, kamu sulit tahu bagian mana penyebabnya." }, { label: "Minta tampilan utama, jalankan, lalu tambahkan satu fungsi inti.", correct: true, feedback: "Tepat. Hasil kecil yang bisa dijalankan lebih mudah diperiksa daripada semua fitur sekaligus." }], reveal: "Membangun sepotong demi sepotong bukan soal kecepatan, melainkan soal menjaga kemampuanmu memeriksa hasilnya." }),
  ],
  [
    p("steps", "LANGKAH 6-8", "Uji → Perbaiki → Review", [{ title: "Coba sendiri", detail: "Klik, ketik, ubah ukuran layar, refresh, dan masukkan nilai yang tidak biasa." }, { title: "Cari satu masalah", detail: "Temukan bagian yang membingungkan, rusak, atau kurang nyaman." }, { title: "Minta bukti dan perbaikan", detail: "Minta agent mencari penyebab lalu memperbaiki tanpa merusak bagian lain." }, { title: "Review", detail: "Periksa fungsi, error, perubahan tak perlu, kerumitan, dan pemahamanmu." }], "Kalau ada bagian yang belum kamu pahami, minta agent menjelaskannya."),
    p("compare", "LANGKAH 9", "Pilih jalur deployment", [{ title: "Vercel Drop", detail: "Unggah file atau folder lewat browser; Vercel membangun framework yang dikenali dan memberi URL live." }, { title: "GitHub → Vercel", detail: "Simpan repository sebagai portfolio dan hubungkan ke Vercel untuk deployment dari Git." }, { title: "Bukan syarat", detail: "GitHub opsional. Yang penting project berhasil live dan diuji." }], "Deployment berhasil belum berarti seluruh fitur benar."),
    p("statement", "FINISH LINE", "Orang lain dapat membuka project-mu", [{ title: "Dari ide ke internet", detail: "Tentukan tujuan, arahkan agent, batasi izin, bangun, uji, perbaiki, dan bagikan URL yang berfungsi." }], "Catat keputusan yang kamu buat selama proses."),
    p("tiles", "REFLEKSI", "Empat pertanyaan singkat", [{ title: "Apa yang dibuat?", detail: "Tulis nama dan kegunaan project." }, { title: "AI membantu apa?", detail: "Bagian mana yang paling banyak dibantu agent?" }, { title: "Keputusanmu?", detail: "Apa yang kamu putuskan sendiri?" }, { title: "Apa yang berubah?", detail: "Apa yang kamu ubah setelah melihat hasil AI?" }], "Kalau mau, ceritakan project-mu kepada orang lain."),
    p("compare", "OPSIONAL · BAGIKAN KARYA", "Portfolio, teman, dosen, atau LinkedIn", [{ title: "Ceritakan", detail: "Apa yang kamu buat, mengapa memilihnya, bagaimana AI membantu, dan apa yang kamu putuskan sendiri." }, { title: "Sertakan", detail: "Tautan live. Repository GitHub hanya jika tersedia." }, { title: "Tetap personal", detail: "AI boleh merapikan tulisan, tetapi ceritanya tetap milikmu." }], "Setelah ini, pilih keterampilan lanjutan sesuai kebutuhan project."),
    p("tiles", "LANGKAH BERIKUTNYA", "Tambah kemampuan saat diperlukan", [{ title: "Database dan autentikasi", detail: "Untuk data online lintas perangkat dan akun pengguna." }, { title: "API", detail: "Untuk layanan cuaca, peta, AI, atau data lain." }, { title: "Git dan testing", detail: "Untuk riwayat perubahan, kolaborasi, dan pemeriksaan sistematis." }, { title: "MCP, agents, skills", detail: "Untuk menambah alat atau menyesuaikan workflow saat memang berguna." }], "Rangkum bekal yang sudah kamu pelajari."),
    p("statement", "INTI KURSUS", "Ide → Percakapan → Rencana → Bangun → Uji → Perbaiki → Deploy", [{ title: "Pegangan", detail: "Arahkan AI, pertanyakan hasilnya, dan tentukan sendiri kapan software siap digunakan." }], "Kamu sudah menyelesaikan Vibe Coding."),
  ],
];
