import type { LessonContent } from "./fundamentals-content";
import type { SectionPresentation } from "./fundamentals-presentation";
import type { LessonStage } from "./module-one-data";

export const vibeStages: LessonStage[] = [
  { id: "from-chat-to-agent", title: "Dari Copy-Paste ke Coding Agent", area: "Pelajaran 1 / 7", question: "Apa yang berubah saat AI bisa membuka project?", intro: "Kenali perbedaan AI chat dan coding agent, lalu lihat cara kerja manusia bersama AI." },
  { id: "tools-models", title: "Kenali Alat dan Modelnya", area: "Pelajaran 2 / 7", question: "Alat mana yang cocok untuk kebutuhanmu?", intro: "Bandingkan AI chat, app builder, dan coding agent; pahami juga peran model." },
  { id: "permissions", title: "Izin dan Cara Kerja Agent", area: "Pelajaran 3 / 7", question: "Tindakan apa yang perlu kamu izinkan?", intro: "Atur izin secara bijak dan pilih mode kerja agent sesuai tugas." },
  { id: "project-context", title: "Beri Agent Arah dan Konteks", area: "Pelajaran 4 / 7", question: "Bagaimana agar agent memahami project?", intro: "Rencanakan fitur, simpan aturan penting, dan gunakan skills atau MCP hanya saat perlu." },
  { id: "setup-and-deploy", title: "Dari Laptop ke Internet", area: "Pelajaran 5 / 7", question: "Apa yang membuat aplikasi bisa diakses orang lain?", intro: "Pahami localhost, deployment, database, keamanan secret, dan setup Kilo." },
  { id: "build-project", title: "Bangun Ide, Satu Bagian Dulu", area: "Pelajaran 6 / 7", question: "Bagaimana mengubah ide menjadi aplikasi?", intro: "Uraikan kebutuhan, minta rencana, lalu bangun fungsi utama sedikit demi sedikit." },
  { id: "test-and-launch", title: "Uji, Perbaiki, dan Luncurkan", area: "Pelajaran 7 / 7", question: "Kapan project siap dibagikan?", intro: "Uji aplikasi sendiri, lakukan review, deploy, dan ceritakan apa yang kamu pelajari." },
];

const source = (label: string, url: string) => ({ label, url });

export const vibeLessons: LessonContent[] = [
  {
    lead: "Kita mulai dari ide sederhana: membuat halaman login. Dulu, AI memberi kode lalu kita memindahkannya sendiri ke project. Sekarang agent bisa bekerja langsung dengan file project.",
    sections: [
      { title: "Dulu: salin, tempel, lalu cari error", paragraphs: ["Kamu meminta AI di browser: ‘Buat halaman login sederhana dengan email, password, dan tombol masuk.’ AI memberi kode. Kamu menyalinnya ke VS Code, mencari file yang tepat, menjalankan project—lalu mendapat error seperti `Module not found`.", "Kamu kembali ke AI, menyalin perbaikan, menempelkannya, lalu menjalankan project lagi. Proses ini bisa berulang karena AI tidak otomatis mengetahui struktur folder, library, gaya kode, atau hubungan antarfile di project-mu.", "AI chat tetap membantu menulis fungsi, CSS, query, menjelaskan error, bahkan membuat satu file penuh. Namun **kitalah yang menjadi penghubung antara AI dan project**."], },
      { title: "Sekarang: agent dapat bekerja di dalam project", paragraphs: ["Kamu bisa meminta: ‘Pelajari project ini. Cari bagian halaman login, tambahkan validasi email dan password, ikuti pola yang sudah ada, dan jangan menambah library tanpa alasan. Jelaskan rencanamu dulu.’", "Coding agent dapat membaca file, mencari bagian relevan, membuat rencana, meminta izin, mengubah file, menjalankan perintah, lalu melihat hasilnya. Agent bukan sekadar mengirim potongan kode—ia menggunakan alat untuk bekerja pada project.", "Batasnya tetap ada. Agent bisa salah membaca kebutuhan, memilih file, atau membuat bug. Karena itu kita perlu meninjau perubahan dan mencoba aplikasinya."], },
      { title: "Checkpoint 1 · apa yang membedakan coding agent?", paragraphs: ["Pilih jawaban yang paling tepat. A. Agent selalu memakai AI yang lebih pintar. B. Agent dapat memakai alat untuk membaca, mengubah, dan menjalankan sesuatu pada project. C. Agent tidak pernah membuat bug."], },
      { title: "Vibe coding: membangun lewat percakapan", paragraphs: ["Istilah **vibe coding** populer pada 2025 setelah digunakan Andrej Karpathy. Istilah ini punya makna yang cukup longgar. Di kursus ini, kita memakainya sebagai cara membangun software lewat percakapan: jelaskan tujuan, beri konteks, buat rencana, minta AI membantu implementasi, lalu uji, tinjau, dan perbaiki.", "Ini bukan berarti ‘AI kerjakan semuanya, saya tinggal klik Accept’. Kamu tidak harus menjadi programmer sebelum mulai, tetapi tetap perlu tahu apa yang ingin dibuat dan menilai apakah hasilnya bekerja."], sources: [source("Andrej Karpathy · unggahan tentang vibe coding", "https://x.com/karpathy/status/1886192184808149383")] },
      { title: "Peran kita bergeser ke arah dan keputusan", paragraphs: ["Saat menulis kode sendiri, pertanyaannya sering ‘Bagaimana saya menulis fungsi ini?’ Saat memakai coding agent, kita juga perlu bertanya: **‘Apa yang sebenarnya perlu dibuat, batasnya apa, dan bagaimana saya tahu hasilnya benar?’**", "Kamu tetap menentukan kebutuhan, batasan, dan keputusan akhir. Agent dapat membantu memilih cara implementasi; kamu memastikan cara itu sesuai project."], },
      { title: "Satu kursus, dua tingkat kedalaman", paragraphs: ["Kursus ini cocok untuk mahasiswa IT maupun non-IT, designer, peneliti, creator, dan siapa pun yang ingin tahu cara membuat software. Kita mengenal VS Code, terminal, file project, Git, dan deployment secara bertahap.", "Bagian **Lebih Dalam — Opsional** memperkenalkan konsep seperti izin alat, konteks project, AGENTS.md, skills, pemilihan model, MCP, debugging agentic, dan alur review. Jalur utama tetap bisa diikuti tanpa pengalaman coding."], },
    ],
    takeaway: "Coding agent dapat bekerja menggunakan file dan alat di dalam project. Manusia tetap menentukan tujuan, batasan, dan apakah hasilnya layak dipakai.",
    check: { question: "Apa pembeda utama coding agent dari AI chat biasa?", choices: [
      { label: "Agent dapat menggunakan alat untuk membaca, mengubah, dan menjalankan sesuatu pada project.", feedback: "Benar. Perubahan besarnya adalah akses agent ke konteks project dan alat kerja.", correct: true },
      { label: "Agent selalu memakai model yang paling pintar.", feedback: "Belum tentu. Agent dapat menggunakan berbagai model.", correct: false },
      { label: "Agent tidak membuat kesalahan.", feedback: "Agent tetap bisa membuat bug atau salah memahami instruksi.", correct: false },
    ] },
  },
  {
    lead: "Banyak alat dapat membantu membuat software. Pilih berdasarkan pekerjaan yang ingin kamu lakukan, bukan hanya karena alat itu sedang populer.",
    sections: [
      { title: "Tiga kelompok alat yang sering ditemui", paragraphs: ["**AI chat** seperti ChatGPT, Claude, atau Gemini berguna untuk bertukar ide, memahami konsep, menyusun kebutuhan, merancang arsitektur, atau membandingkan pilihan. Biasanya, kita membawa jawaban AI ke project sendiri.", "**AI app builder** seperti Replit Agent atau Lovable membantu membuat prototype langsung melalui browser. Mulainya mudah dan platform bisa mengurus sebagian detail seperti environment dan hosting. Paket gratis biasanya punya batas penggunaan.", "**AI coding agent** seperti Kilo Code, OpenCode, Codex, Claude Code, atau Cursor lebih dekat dengan project: dapat bekerja dengan file, repository, terminal, dan alat development."], },
      { title: "Kita memakai Kilo, tetapi pola kerjanya bisa dibawa", paragraphs: ["Kursus ini memakai **Kilo Code** melalui VS Code. Kilo menyediakan agent, pilihan model, permission, petunjuk project, skills, dan MCP. Kita memilihnya sebagai alat latihan—bukan karena semua orang harus selalu memakai Kilo.", "Besok tool-mu mungkin berbeda. Polanya tetap serupa: **tujuan → konteks → rencana → agent memakai alat → tinjau → uji → perbaiki**."], sources: [source("Dokumentasi Kilo Code untuk VS Code", "https://kilo.ai/docs/code-with-ai/platforms/vscode")] },
      { title: "Agent bekerja dalam putaran", paragraphs: ["Saat kamu meminta judul halaman diganti menjadi ‘FocusFlow’, agent membaca permintaan dan konteks, memilih alat, memeriksa file, menentukan tindakan, membuat perubahan jika diizinkan, lalu melihat hasilnya.", "Proses berulang ini sering disebut **agent loop**. Agent dapat melanjutkan pekerjaan berdasarkan hasil tindakan sebelumnya sampai tugas selesai atau perlu bertanya lagi."], },
      { title: "Model dan agent bukan hal yang sama", paragraphs: ["**Model** adalah AI yang menghasilkan jawaban dan melakukan penalaran. **Agent** adalah sistem yang menghubungkan model dengan konteks, instruksi, alat, izin, dan environment.", "Analogi sederhananya: model seperti mesin berpikir; agent seperti mesin berpikir yang diberi alat, ruang kerja, dan aturan. Model yang sama bisa terasa berbeda ketika alat dan izin agent-nya berbeda."], },
      { title: "Pilih model sesuai tingkat kesulitan", paragraphs: ["Mengubah tulisan tombol dari ‘Submit’ menjadi ‘Kirim’ tidak sama sulitnya dengan mencari bug yang melibatkan banyak file dan state aplikasi.", "Untuk perubahan sederhana, model yang lebih ringan atau gratis mungkin cukup. Untuk pekerjaan rumit, model yang lebih mampu bisa membantu. Pertimbangkan juga biaya, kecepatan, context window, privasi, dan kemampuan yang dibutuhkan.", "**Benchmark punya konteks.** SWE-bench menguji penyelesaian issue software di repository; LiveCodeBench berfokus pada soal coding; Terminal-Bench menguji penggunaan terminal dan alat. Angka dari satu benchmark tidak otomatis menentukan model terbaik untuk semua tugas. Agent, alat, prompt, environment, dan batas token juga berpengaruh."], sources: [source("SWE-bench", "https://github.com/swe-bench/SWE-bench"), source("LiveCodeBench", "https://github.com/GOTOIA/livecodebench"), source("Terminal-Bench", "https://github.com/harbor-framework/terminal-bench")] },
      { title: "Checkpoint 2 · perlu model paling mahal?", paragraphs: ["Tugasmu hanya mengganti tulisan tombol pada landing page. A. Ya, selalu gunakan model termahal. B. Tidak, model sederhana mungkin cukup."], },
      { title: "Auto Free untuk latihan awal", paragraphs: ["Kilo memiliki pilihan **Auto Free** yang mengarahkan permintaan ke model gratis yang tersedia. Model gratis bisa terkena batas penggunaan dan pilihan modelnya dapat berubah.", "Jika ingin semua penggunaan tetap tanpa kredit, pengaturan autocomplete dan model latar belakang juga perlu diperiksa. Perhatikan juga privasi: penyedia model gratis dapat memiliki kebijakan pencatatan data yang berbeda. Jangan kirim data pribadi atau rahasia tanpa memahami kebijakan alat yang kamu pakai."], sources: [source("Kilo · Menggunakan Kilo secara gratis", "https://kilo.ai/docs/getting-started/using-kilo-for-free"), source("Kilo · Model dan provider", "https://kilo.ai/docs/gateway/models-and-providers")] },
    ],
    takeaway: "AI chat, app builder, coding agent, model, dan benchmark menjawab kebutuhan yang berbeda. Pilih yang cukup untuk tugasmu dan periksa kebijakan datanya.",
    check: { question: "Kamu hanya ingin mengganti satu label tombol. Apa pilihan yang masuk akal?", choices: [
      { label: "Pakai model sederhana yang cukup untuk tugas kecil itu.", feedback: "Tepat. Kemampuan model perlu disesuaikan dengan kerumitan tugas.", correct: true },
      { label: "Selalu pilih model termahal agar aman.", feedback: "Biaya lebih tinggi tidak selalu memberi manfaat untuk perubahan sederhana.", correct: false },
      { label: "Pilih model dari angka benchmark terbesar saja.", feedback: "Benchmark punya konteks dan tidak mewakili semua jenis pekerjaan.", correct: false },
    ] },
  },
  {
    lead: "Karena coding agent bisa bertindak, kita perlu memahami izin dan memilih cara kerja yang sesuai dengan tahap pekerjaan.",
    sections: [
      { title: "Agent dapat melakukan tindakan", paragraphs: ["Chatbot umumnya memberi saran. Coding agent juga dapat membaca file, mengedit project, menjalankan perintah, atau memasang package.", "Izin membantu kita menentukan tindakan yang boleh berjalan otomatis, yang harus meminta persetujuan, dan yang tidak boleh dilakukan."], },
      { title: "Allow, Ask, Deny", paragraphs: ["Di Kilo, permission dapat diatur per alat atau perintah:\n\n**Allow** — tindakan boleh berjalan tanpa bertanya.\n\n**Ask** — agent perlu meminta izin.\n\n**Deny** — tindakan diblokir.\n\nJika tidak ada aturan yang cocok, dokumentasi Kilo menyebut default-nya meminta persetujuan. Pengaturan yang tepat tetap bergantung pada project dan kebijakan tool."], sources: [source("Kilo · Agent Permissions", "https://kilo.ai/docs/customize/agent-permissions"), source("Kilo · Auto-Approving Actions", "https://kilo.ai/docs/getting-started/settings/auto-approving-actions")] },
      { title: "Berikan izin secukupnya", paragraphs: ["Untuk belajar, pendekatan awal yang mudah dipahami: membaca file boleh; perubahan file dan perintah terminal minta persetujuan; tindakan di luar project juga perlu diperiksa.", "Misalnya agent ingin menjalankan `npm install random-ui-library`. Sebelum menyetujui, tanyakan kenapa package baru diperlukan. Bisa jadi memang berguna; bisa juga CSS yang sudah ada sudah cukup.", "Aturan dapat dibuat lebih spesifik: `git status` boleh berjalan, sedangkan perintah yang menghapus file perlu ditolak atau meminta persetujuan. **Approve bukan tombol Next. Itu keputusan.**"], },
      { title: "Pilih mode kerja: Ask, Plan, Code, Debug", paragraphs: ["**Ask** untuk memahami: ‘Jelaskan struktur project ini. Jangan ubah file.’\n\n**Plan** untuk merancang: ‘Saya ingin menambah pencarian. Jangan coding dulu; jelaskan file yang berubah dan cara kerjanya.’\n\n**Code** untuk menerapkan: ‘Implementasikan tahap pertama dari rencana. Jangan ubah bagian lain.’\n\n**Debug** untuk mencari penyebab: ‘Tombol ini tidak bekerja. Cari penyebabnya dan tunjukkan bukti sebelum mengubah kode.’"], },
      { title: "Checkpoint 3 · pahami project dulu", paragraphs: ["Kamu belum tahu cara kerja project. A. Langsung minta AI menulis ulang semuanya. B. Minta AI menjelaskan project terlebih dahulu."], },
    ],
    takeaway: "Mulai dengan izin yang terbatas dan pilih mode kerja sesuai kebutuhan: memahami, merencanakan, menerapkan, atau mencari penyebab masalah.",
    check: { question: "Kamu belum tahu cara kerja project dan ingin menambah fitur pencarian. Apa langkah awal yang paling aman?", choices: [
      { label: "Minta agent menjelaskan project dan menyusun rencana tanpa mengubah file dulu.", feedback: "Benar. Pahami konteks lalu tinjau rencana sebelum implementasi.", correct: true },
      { label: "Minta agent menulis ulang seluruh project.", feedback: "Perubahan besar tanpa memahami project bisa merusak bagian yang sudah bekerja.", correct: false },
      { label: "Izinkan semua perintah supaya lebih cepat.", feedback: "Izin penuh mengurangi kendali atas tindakan agent.", correct: false },
    ] },
  },
  {
    lead: "Coding agent bekerja lebih terarah saat tujuan dan aturan project jelas. Simpan konteks yang memang terus berlaku; tidak semua project perlu dokumentasi panjang.",
    sections: [
      { title: "Jangan mulai dari ‘buat aplikasi keren’", paragraphs: ["Permintaan ‘Buat aplikasi belajar yang keren’ membuat agent menebak siapa penggunanya, masalah yang ingin dibantu, fitur, tampilan, tempat penyimpanan data, dan hal yang tidak diperlukan.", "Untuk perubahan besar, gunakan alur **Ide → Kebutuhan → Rencana → Bangun → Uji → Perbaiki**. Untuk perubahan kecil seperti mengganti warna tombol, rencana panjang tidak perlu. Sesuaikan proses dengan besar tugas."], },
      { title: "Simpan aturan project yang terus berlaku", paragraphs: ["Kalau kamu selalu ingin ‘jangan menambah library tanpa alasan’, ‘jangan ubah file di luar tugas’, atau ‘pastikan tampilan nyaman di ponsel’, aturan itu dapat ditulis di **AGENTS.md**.", "Anggap file ini sebagai petunjuk kerja agent. Contohnya: utamakan solusi sederhana; jelaskan perubahan besar sebelum mengerjakannya; jangan menambah dependency tanpa alasan; setelah perubahan, pastikan aplikasi tetap bisa dijalankan.", "Tidak semua project memerlukannya. Untuk project kecil, satu catatan `PROJECT.md` tentang tujuan, fitur, batasan, dan definisi selesai mungkin cukup. `product-spec.md` atau `architecture.md` berguna jika ukuran project memang membutuhkannya."], sources: [source("Kilo · Custom Instructions", "https://kilo.ai/docs/customize/custom-instructions")] },
      { title: "Skills adalah playbook untuk jenis tugas", paragraphs: ["**AGENTS.md** menyimpan aturan atau konteks project. **SKILL.md** menjelaskan kapan dan bagaimana agent menjalankan jenis pekerjaan tertentu, misalnya membuat interface atau meninjau tulisan.", "Kilo menemukan skills yang tersedia dan memuat isi lengkap saat skill relevan. Banyak skills tidak otomatis lebih baik; pilih yang benar-benar membantu. Aturan atau playbook yang tidak relevan hanya menambah konteks."], sources: [source("Kilo · Skills", "https://kilo.ai/docs/customize/skills")] },
      { title: "MCP menambahkan akses ke alat lain", paragraphs: ["**MCP (Model Context Protocol)** adalah cara menghubungkan agent dengan tools atau layanan tambahan, seperti alat desain, database, dokumentasi, atau pemantauan.", "Analogi sederhananya: AGENTS.md memberi aturan, SKILL.md memberi playbook, MCP memberi akses ke alat. Project pertama tidak perlu MCP kalau belum ada kebutuhan yang jelas."], sources: [source("Kilo · Menggunakan MCP", "https://kilo.ai/docs/automate/mcp/using-in-kilo-code")] },
      { title: "Aktivitas · pilih konteks yang cukup", paragraphs: ["Kamu membuat quiz kecil tanpa login. Apa yang perlu diminta lebih dulu? **A.** Tambahkan database, autentikasi, lima skills, dan integrasi MCP. **B.** Minta fitur inti dan tampilan ponsel; tambahkan layanan lain hanya jika kebutuhan membutuhkannya.\n\n**Pilihan B** menjaga project tetap sederhana. Tambahkan konteks yang membantu tugas, bukan semua kemungkinan yang tersedia."], },
    ],
    takeaway: "Rencanakan fitur sesuai kerumitannya. Simpan aturan yang terus berlaku, dan tambahkan dokumentasi, skills, atau MCP hanya bila membantu project.",
    check: { question: "Kapan AGENTS.md paling berguna?", choices: [
      { label: "Saat ada aturan project yang ingin selalu diikuti agent.", feedback: "Tepat. AGENTS.md menyimpan petunjuk yang berulang untuk project.", correct: true },
      { label: "Setiap kali membuat file baru, apa pun ukuran project.", feedback: "Project kecil mungkin belum membutuhkannya.", correct: false },
      { label: "Untuk menyimpan semua kode aplikasi.", feedback: "AGENTS.md berisi instruksi dan konteks, bukan kode aplikasi.", correct: false },
    ] },
  },
  {
    lead: "Aplikasi di laptop belum tentu dapat dibuka orang lain. Sebelum membangun, kenali jalur dari project lokal sampai menjadi tautan publik.",
    sections: [
      { title: "Localhost hanya berjalan di perangkatmu", paragraphs: ["Saat aplikasi berjalan di laptop, browser mungkin membuka `http://localhost:5173`. Alamat itu merujuk ke aplikasi yang berjalan di komputer sendiri. Temanmu tidak otomatis bisa membukanya dari laptop lain.", "**Deployment** adalah proses menerbitkan aplikasi ke environment yang dapat diakses pengguna. Setelah di-deploy, kamu mendapat URL publik, misalnya `nama-project.vercel.app`."], },
      { title: "Tidak semua aplikasi perlu database", paragraphs: ["Pomodoro timer, kalkulator, quiz sederhana, portfolio interaktif, generator acak, atau tracker dengan localStorage dapat bekerja tanpa database server.", "Database atau backend mulai berguna jika aplikasi butuh login, data lintas perangkat, banyak pengguna, atau penyimpanan online. Supabase adalah salah satu pilihan yang menyediakan PostgreSQL, autentikasi, penyimpanan file, dan API; kita tidak memerlukannya untuk project pertama kecuali ada kebutuhan."], },
      { title: "Jaga API key dan secret", paragraphs: ["API key, kredensial database, dan informasi rahasia lain jangan ditulis langsung di kode frontend atau repository publik.", "Aplikasi biasanya memakai **environment variables** untuk mengatur nilai rahasia. Untuk sekarang cukup ingat: jangan mengunggah secret ke GitHub atau menaruhnya di kode yang dikirim ke browser."], },
      { title: "Setup Kilo untuk latihan", paragraphs: ["Jalur utama kursus ini menggunakan extension Kilo di VS Code: buka Extensions, cari Kilo Code, pasang extension yang tersedia, lalu buka dari sidebar. Dokumentasi dan tampilan dapat berubah, jadi ikuti petunjuk pemasangan resmi terbaru.", "Kalau lebih nyaman memakai terminal, Kilo juga menyediakan CLI melalui `npm install -g @kilocode/cli`, lalu perintah `kilo`. Untuk project berbasis React atau framework lain, Node.js mungkin diperlukan.", "Latihan kita menggunakan Auto Free jika tersedia. Biarkan membaca file; minta persetujuan untuk edit dan perintah terminal. Autocomplete bersifat opsional. Setiap model memiliki aturan biaya dan privasinya sendiri—periksa pengaturan sebelum mengirim data."], sources: [source("Kilo · Extension VS Code", "https://kilo.ai/docs/code-with-ai/platforms/vscode"), source("Kilo · CLI", "https://kilo.ai/docs/code-with-ai/platforms/cli"), source("Kilo · Menggunakan Kilo secara gratis", "https://kilo.ai/docs/getting-started/using-kilo-for-free")] },
      { title: "Checkpoint · database atau tidak?", paragraphs: ["Kamu ingin membuat timer belajar pribadi yang menyimpan pengaturan di browser perangkat yang sama. Apakah database online wajib? **Tidak.** Mulai dengan solusi lokal yang sederhana; tambah database jika kebutuhan berubah."], },
    ],
    takeaway: "Pahami dulu apakah project berjalan lokal atau perlu diakses publik. Tambahkan database hanya jika dibutuhkan, dan jaga secret di luar kode publik.",
    check: { question: "Timer belajar sederhana hanya perlu menyimpan pengaturan di satu browser. Apa pilihan awal yang masuk akal?", choices: [
      { label: "Mulai tanpa database server; simpan lokal bila sesuai kebutuhan.", feedback: "Benar. Tidak semua aplikasi perlu database online.", correct: true },
      { label: "Selalu pasang Supabase sejak awal.", feedback: "Database menambah bagian yang perlu dikonfigurasi dan dirawat.", correct: false },
      { label: "Tulis API key di file JavaScript supaya mudah ditemukan.", feedback: "Secret tidak boleh ditaruh di kode publik.", correct: false },
    ] },
  },
  {
    lead: "Sekarang saatnya membangun. Mulai dari versi kecil yang dapat digunakan, lalu tambahkan kemampuan satu per satu.",
    sections: [
      { title: "Tentukan ide sebelum membuka coding agent", paragraphs: ["Kamu bebas memilih project: Pomodoro timer, study planner, kalkulator pengeluaran, quiz, habit tracker, book tracker, random meal picker, GPA calculator, portfolio interaktif, situs acara, flashcard, mini game, mood journal lokal, decision helper, atau ide sendiri.", "Tidak harus aplikasi bisnis, task manager, atau memakai AI. Yang penting ada sesuatu yang dapat digunakan atau diinteraksikan oleh orang lain."], },
      { title: "Langkah 1 · jelaskan versi pertama", paragraphs: ["Jawab empat hal: **apa yang dibuat, siapa yang akan menggunakannya, apa 2–4 fungsi utama, dan apa yang belum perlu dibuat**. Deskripsinya boleh singkat.", "Minta AI membantu merapikan kebutuhan kalau perlu. Pastikan versi pertama tetap kecil dan bisa dicoba."], },
      { title: "Langkah 2–3 · minta agent memahami dan merencanakan", paragraphs: ["Buka project di VS Code, lalu gunakan Ask atau Plan: ‘Saya ingin membuat aplikasi berikut. Bantu merancang versi pertama yang sederhana. Jangan coding dulu. Jelaskan fitur minimum, struktur project, dan urutan implementasinya. Hindari fitur yang tidak diperlukan.’", "Baca rencana itu. Kalau terlalu rumit, minta agent menyederhanakannya. Untuk project sederhana, aturan tambahan boleh dilewati. Jika memakai AGENTS.md, cukup tulis beberapa aturan yang benar-benar penting."], },
      { title: "Langkah 4–5 · bangun bagian terkecil", paragraphs: ["Jangan minta ‘buat semuanya’. Mulai dari tampilan utama atau fungsi inti, jalankan, lalu lihat hasilnya. Setelah itu minta kemampuan nyata satu per satu: tombol bekerja, timer berjalan, data bisa ditambahkan, nilai dihitung, quiz bisa dijawab, atau kartu bisa difilter.", "Setelah tiap perubahan, lihat file yang berubah dan coba fitur tersebut. Minta agent menjelaskan perubahan penting dengan kata-kata sederhana."], },
      { title: "Checkpoint · apa yang dibangun lebih dulu?", paragraphs: ["Untuk membuat study planner, apa langkah pertama yang lebih mudah diperiksa? A. Minta semua fitur selesai sekaligus. B. Minta tampilan utama, jalankan, lalu tambahkan satu fungsi inti."], },
    ],
    takeaway: "Tulis kebutuhan sederhana, baca rencana agent, dan bangun satu bagian yang terlihat sebelum menambah fungsi lain.",
    check: { question: "Kamu mulai membuat study planner. Bagaimana membatasi versi pertama?", choices: [
      { label: "Tentukan pengguna, dua sampai empat fungsi utama, dan fitur yang belum diperlukan.", feedback: "Tepat. Batas yang jelas membantu agent tidak menebak terlalu banyak.", correct: true },
      { label: "Minta agent membuat semua fitur yang mungkin berguna.", feedback: "Permintaan terbuka mendorong asumsi dan fitur berlebihan.", correct: false },
      { label: "Mulai menambah database, login, dan pembayaran sebelum ada kebutuhan.", feedback: "Komponen itu menambah kerumitan jika project belum memerlukannya.", correct: false },
    ] },
  },
  {
    lead: "Project belum selesai hanya karena kode berhasil dibuat atau deployment memberi URL. Gunakan, uji, perbaiki, lalu tinjau apa yang akan kamu bagikan.",
    sections: [
      { title: "Langkah 6–8 · uji, perbaiki, dan review", paragraphs: ["Jangan hanya bertanya ke AI ‘Sudah benar?’ Klik, ketik, ubah ukuran layar, refresh halaman, dan coba input yang tidak biasa. Perhatikan apa yang terjadi ketika pengguna melakukan sesuatu di luar alur yang kamu bayangkan.", "Pilih setidaknya satu hal yang membingungkan, rusak, tidak nyaman, atau kurang menarik. Minta agent mencari penyebab lalu memperbaikinya tanpa merusak bagian lain yang sudah bekerja.", "Sebelum selesai, cek: fitur utama bekerja? Ada error? Agent mengubah bagian yang tidak perlu? Solusi terlalu rumit? Kamu memahami garis besar aplikasi? Jika belum, minta agent menjelaskan bagian itu, mengapa diperlukan, dan apa akibatnya jika dihapus."], },
      { title: "Langkah 9 · deploy dengan jalur yang sesuai", paragraphs: ["Jalur paling sederhana adalah **Vercel Drop**: unggah file atau folder lewat browser, pilih nama project, lalu deploy. Vercel dapat mendeteksi framework tertentu dan memberi URL publik. Setelah itu buka URL dari perangkat lain dan uji kembali.", "Jika ingin menyimpan kode sebagai portfolio, gunakan jalur **GitHub → Vercel**. Repository GitHub bukan syarat agar project selesai; yang penting project bisa dibuka dan dicoba. Keberhasilan deploy juga belum membuktikan semua fitur benar."], sources: [source("Vercel · Vercel Drop", "https://vercel.com/changelog/vercel-drop"), source("Kilo · dokumentasi resmi", "https://kilo.ai/docs")] },
      { title: "Finish line · ide yang bisa dibuka orang lain", paragraphs: ["Kamu sudah berangkat dari ide, mengarahkan AI, membaca rencana, mengatur izin, membangun software, mengujinya, memperbaikinya, dan menerbitkannya. Jika orang lain dapat membuka URL-mu dari perangkat berbeda, project sudah mencapai tujuan utama kursus."], },
      { title: "Refleksi singkat", paragraphs: ["Catat jawabanmu: **1. Apa yang kamu buat? 2. Bagian apa yang paling banyak dibantu AI? 3. Keputusan apa yang kamu buat sendiri? 4. Apa yang kamu ubah setelah melihat hasil AI?**\n\nTujuannya bukan menguji hafalan kode, tetapi memastikan kamu tetap ikut berpikir dan membuat keputusan."], },
      { title: "Opsional · ceritakan project-mu", paragraphs: ["Project tetap selesai meskipun tidak kamu unggah ke mana pun. Kalau ingin membagikannya, kirim tautan live kepada teman, dosen, organisasi, masukkan ke portfolio, atau bagikan di LinkedIn.", "Ceritakan apa yang kamu buat, kenapa memilih ide itu, bagaimana AI membantu, keputusan apa yang tetap kamu buat sendiri, dan apa yang dipelajari. Sertakan tautan live; repository GitHub boleh ditambahkan jika ada. Ceritanya tetap ceritamu, meski AI membantu merapikan tulisan."], },
      { title: "Ke mana melangkah setelah ini?", paragraphs: ["Kalau project berikutnya butuh data lintas perangkat atau banyak pengguna, pelajari database online seperti Supabase dan autentikasi. API dapat menghubungkan aplikasi dengan cuaca, peta, AI, atau layanan lain.", "Git dan GitHub membantu menyimpan riwayat versi dan bekerja bersama. Testing membantu memeriksa perilaku dengan cara yang sistematis. MCP, custom agents, dan skills dapat memperluas alat atau menyesuaikan alur agent saat memang diperlukan."], },
      { title: "Prinsip yang dibawa pulang", paragraphs: ["Jangan hanya bertanya ‘AI bisa membuat ini tidak?’ Tanyakan juga: **Apa yang ingin saya buat? Konteks apa yang dibutuhkan? Apakah rencananya masuk akal? Tindakan apa yang saya izinkan? Apakah hasilnya bekerja? Apakah solusinya lebih rumit dari yang perlu? Apa yang perlu diperbaiki setelah diuji?**", "Vibe coding bukan membiarkan AI mengambil semua keputusan, dan bukan pula syarat menjadi programmer dulu. Tool dan model bisa berubah. Kemampuan yang bertahan adalah tahu apa yang ingin dibangun, mengarahkan AI, mempertanyakan hasilnya, dan menilai kapan software siap digunakan.", "Akhirnya bukan sekadar ‘Saya menghasilkan kode dengan AI’, tetapi: **‘Saya punya ide, membangunnya bersama AI, dan orang lain bisa membukanya lewat tautan.’**"], },
    ],
    takeaway: "Project siap dibagikan setelah fitur utamanya dicoba, masalah penting diperbaiki, perubahan ditinjau, dan tautan live diuji dari perangkat lain.",
    check: { question: "Deployment berhasil dan kamu mendapat URL. Apa langkah berikutnya?", choices: [
      { label: "Buka URL dari perangkat lain, uji fitur, lalu catat hal yang perlu diperbaiki.", feedback: "Benar. URL live belum memastikan semua fungsi bekerja.", correct: true },
      { label: "Anggap semua fitur pasti benar karena deployment sukses.", feedback: "Deployment hanya menerbitkan aplikasi, bukan memverifikasi setiap fungsi.", correct: false },
      { label: "Hapus project lokal karena sudah online.", feedback: "Project lokal tetap dibutuhkan untuk perubahan berikutnya.", correct: false },
    ] },
  },
];

const p = (kind: SectionPresentation["kind"], label: string, title: string, items: { title: string; detail: string }[], bridge: string, interactive = false): SectionPresentation => ({ kind, label, title, items, bridge, interactive });

export const vibePresentations: SectionPresentation[][] = [
  [
    p("steps", "ALUR LAMA", "Salin → Tempel → Jalankan → Ulangi", [{ title: "AI di browser", detail: "Menjawab dari konteks yang kita kirim." }, { title: "VS Code", detail: "Kita sendiri mencari file dan memindahkan kode." }, { title: "Error", detail: "Kembali ke AI, tempel pesan error, lalu coba lagi." }], "Coding agent dapat bekerja lebih dekat dengan project."),
    p("steps", "ALUR BARU", "Agent membaca dan bertindak di project", [{ title: "Pahami", detail: "Baca struktur dan kode project." }, { title: "Rencanakan", detail: "Tentukan file dan langkah yang relevan." }, { title: "Minta izin", detail: "Tunggu persetujuan sebelum tindakan tertentu." }, { title: "Kerjakan", detail: "Edit file atau jalankan perintah sesuai izin." }, { title: "Periksa", detail: "Lihat hasil dan lanjutkan bila masih ada pekerjaan." }], "Pilih jawaban pada checkpoint untuk membedakan agent dari chat biasa.", true),
    p("compare", "CHECKPOINT 1", "Apa yang membedakan coding agent?", [{ title: "A · Model lebih pintar", detail: "Tidak selalu. Agent bisa memakai model yang berbeda-beda." }, { title: "B · Memakai tools", detail: "Benar. Agent dapat membaca, mengubah, dan menjalankan sesuatu pada project." }, { title: "C · Bebas bug", detail: "Tidak benar. Hasil agent tetap perlu ditinjau dan diuji." }], "Vibe coding menggunakan percakapan untuk membangun, menguji, dan memperbaiki software.", true),
    p("steps", "CARA KERJA KURSUS", "Tujuan → Konteks → Rencana → Bangun → Uji", [{ title: "Percakapan", detail: "Jelaskan kebutuhan dan batasan." }, { title: "Agent", detail: "Membantu membuat perubahan pada project." }, { title: "Manusia", detail: "Meninjau, menguji, dan menentukan apakah hasil sesuai." }], "Kita tidak perlu menjadi programmer lebih dulu, tetapi perlu tetap terlibat."),
    p("compare", "PERAN KITA", "Arahkan kebutuhan, nilai hasilnya", [{ title: "Kamu menentukan", detail: "Requirement, batasan, dan standar hasil yang benar." }, { title: "Agent membantu", detail: "Memilih cara implementasi dan membuat perubahan pada project." }], "Kursus ini menyediakan jalur utama dan bahasan opsional yang lebih teknis."),
    p("statement", "SATU COURSE, DUA TINGKAT", "Semua orang bisa mulai", [{ title: "Jalur utama", detail: "Pengalaman coding tidak diperlukan untuk mengikuti konsep dasarnya." }, { title: "Lebih Dalam — Opsional", detail: "Bahasan teknis dapat dipelajari bertahap oleh yang ingin mendalami coding agent." }], "Selanjutnya, kita lihat pilihan alat dan model yang tersedia."),
  ],
  [
    p("tiles", "PETA ALAT", "Pilih alat sesuai pekerjaan", [{ title: "AI chat", detail: "Untuk bertukar ide, memahami konsep, menyusun kebutuhan, dan membandingkan pilihan." }, { title: "AI app builder", detail: "Untuk membuat prototype dari browser dengan persiapan yang lebih ringan." }, { title: "AI coding agent", detail: "Untuk bekerja dengan file, repository, terminal, dan project development." }], "Kursus ini memakai Kilo sebagai contoh coding agent."),
    p("compare", "ALAT LATIHAN", "Kilo sekarang, pola yang bisa dibawa", [{ title: "Kilo Code", detail: "Dipakai melalui VS Code, dengan pilihan model, izin, aturan project, skills, dan MCP." }, { title: "Tool lain", detail: "OpenCode, Codex, Claude Code, Cursor, dan alat lain dapat punya interface berbeda." }, { title: "Pola umum", detail: "Tujuan → konteks → rencana → alat → tinjau → uji → perbaiki." }], "Agent memakai alat dalam putaran yang berulang."),
    p("steps", "AGENT LOOP", "Dari permintaan ke tindakan", [{ title: "Baca request", detail: "Pahami tugas dan konteksnya." }, { title: "Pilih tool", detail: "Tentukan alat yang tepat untuk membaca atau mengubah project." }, { title: "Lakukan", detail: "Ambil tindakan jika diizinkan." }, { title: "Lihat hasil", detail: "Gunakan hasilnya untuk memilih langkah berikutnya." }], "Agar jelas, pisahkan model dari agent yang menggunakannya."),
    p("compare", "DUA ISTILAH", "Model ≠ agent", [{ title: "Model", detail: "AI yang melakukan penalaran dan menghasilkan jawaban." }, { title: "Agent", detail: "Sistem yang memberi model konteks, alat, izin, dan environment." }], "Pilih kemampuan model sesuai beban tugas."),
    p("tiles", "SESUAIKAN DENGAN TUGAS", "Sederhana atau kompleks?", [{ title: "Perubahan kecil", detail: "Ganti label tombol: model ringan mungkin sudah cukup." }, { title: "Bug lintas file", detail: "Masalah pada banyak file dan state mungkin butuh model lebih mampu." }, { title: "Bandingkan", detail: "Biaya, kecepatan, context window, privasi, dan benchmark." }, { title: "Checkpoint 2", detail: "Tugas kecil tidak otomatis memerlukan model paling mahal." }], "Benchmark mengukur jenis pekerjaan tertentu, bukan semua kemampuan sekaligus.", true),
    p("compare", "BACA BENCHMARK DENGAN KONTEKS", "Tes berbeda, ukuran berbeda", [{ title: "SWE-bench", detail: "Dekat dengan penyelesaian issue software pada repository." }, { title: "LiveCodeBench", detail: "Berfokus pada pemecahan soal coding." }, { title: "Terminal-Bench", detail: "Melihat kemampuan agent menggunakan terminal dan tools." }], "Untuk latihan, Auto Free dapat membantu—tetap periksa batas dan kebijakan datanya."),
    p("statement", "PILIHAN LATIHAN", "Auto Free dapat berubah", [{ title: "Perhatikan", detail: "Model gratis bisa terkena batas penggunaan. Untuk bebas kredit, cek juga pengaturan autocomplete dan model latar belakang. Jangan kirim data rahasia tanpa memahami kebijakan provider." }], "Berikutnya, kita bahas tindakan apa saja yang perlu mendapat izin."),
  ],
  [
    p("statement", "AGENT BISA BERTINDAK", "Izin menjaga kita tetap tahu", [{ title: "Contoh tindakan", detail: "Membaca file, mengedit project, menjalankan command, atau memasang package." }], "Tentukan tindakan mana yang boleh, perlu persetujuan, atau diblokir."),
    p("tiles", "ALLOW · ASK · DENY", "Tiga tingkat izin", [{ title: "Allow", detail: "Tindakan boleh berjalan tanpa bertanya." }, { title: "Ask", detail: "Agent meminta persetujuan terlebih dahulu." }, { title: "Deny", detail: "Tindakan tidak diperbolehkan." }], "Untuk belajar, minta persetujuan untuk perubahan dan command.", true),
    p("compare", "SEBELUM MENYETUJUI", "Periksa alasan tindakan", [{ title: "npm install random-ui-library", detail: "Tanyakan kenapa package baru diperlukan." }, { title: "git status", detail: "Perintah baca status dapat dibuat boleh jika sesuai aturan project." }, { title: "Menghapus file", detail: "Pahami target dan dampaknya sebelum memberi izin." }], "Pilih cara kerja agent sesuai tujuanmu."),
    p("tiles", "EMPAT MODE KERJA", "Ask · Plan · Code · Debug", [{ title: "Ask", detail: "Memahami project. Jangan ubah file." }, { title: "Plan", detail: "Merencanakan fitur. Jangan coding dulu." }, { title: "Code", detail: "Menerapkan satu tahap dari rencana." }, { title: "Debug", detail: "Mencari penyebab dan bukti sebelum mengubah kode." }], "Kalau belum tahu project-nya, mulai dari memahami."),
    p("compare", "CHECKPOINT 3", "Project belum kamu kenal", [{ title: "A · Rewrite semuanya", detail: "Berisiko mengubah bagian yang sebenarnya tidak perlu." }, { title: "B · Minta penjelasan", detail: "Tepat. Pahami struktur dan tugas sebelum merencanakan perubahan." }], "Setelah agent memahami project, jelaskan tujuan dan konteksnya.", true),
  ],
  [
    p("compare", "RUMIT SESUAI KEBUTUHAN", "Ide → Requirement → Plan → Build", [{ title: "Perubahan kecil", detail: "Warna tombol mungkin dapat langsung diubah." }, { title: "Fitur baru", detail: "Rencana membantu memeriksa kebutuhan dan file yang perlu berubah." }, { title: "Aplikasi besar", detail: "Pecah pekerjaan; jangan mulai dari ‘buat semuanya’." }], "Aturan yang terus berlaku bisa disimpan di project."),
    p("steps", "AGENTS.MD", "Petunjuk kerja untuk agent", [{ title: "Contoh aturan", detail: "Utamakan solusi sederhana; jangan tambah dependency tanpa alasan; batasi perubahan pada tugas." }, { title: "Tidak wajib", detail: "Project kecil mungkin cukup punya catatan PROJECT.md yang ringkas." }, { title: "Dokumen lain", detail: "Product spec atau architecture docs berguna jika ukuran project membutuhkannya." }], "Aturan project berbeda dari playbook untuk jenis pekerjaan tertentu."),
    p("compare", "AGENTS.MD DAN SKILL.MD", "Aturan project dan playbook", [{ title: "AGENTS.md", detail: "Menyimpan aturan atau konteks yang berlaku di project." }, { title: "SKILL.md", detail: "Menjelaskan kapan dan bagaimana menjalankan jenis pekerjaan tertentu." }, { title: "Pilih yang relevan", detail: "Skill yang tidak diperlukan hanya menambah konteks." }], "MCP memberi agent akses ke tool atau layanan tambahan."),
    p("tiles", "MCP", "Akses ke layanan tambahan", [{ title: "Contoh", detail: "Alat desain, database, dokumentasi, atau pemantauan." }, { title: "Ingat", detail: "Untuk project pertama, MCP tidak wajib." }], "Pilih kebutuhan dulu; jangan menambah integrasi tanpa alasan."),
    p("compare", "AKTIVITAS", "Quiz kecil tanpa login", [{ title: "A · Tambahkan semua alat", detail: "Database, autentikasi, lima skills, dan MCP membuat project lebih rumit dari yang diminta." }, { title: "B · Mulai dari fitur inti", detail: "Tepat. Buat quiz dan tampilan ponsel; tambah layanan lain jika kebutuhan muncul." }], "Sekarang lihat bagaimana project bisa berpindah dari laptop ke internet.", true),
  ],
  [
    p("compare", "LOKAL DAN PUBLIK", "Localhost hanya di laptopmu", [{ title: "localhost:5173", detail: "Alamat ini membuka aplikasi yang berjalan di komputer sendiri." }, { title: "Deployment", detail: "Menerbitkan aplikasi agar dapat diakses pengguna melalui URL publik." }], "Sebelum memilih layanan, tentukan apakah aplikasi butuh data online."),
    p("compare", "DATABASE ATAU TIDAK?", "Tidak semua aplikasi perlu server", [{ title: "Tanpa database", detail: "Pomodoro, calculator, quiz, portfolio, random generator, atau tracker lokal." }, { title: "Database mungkin perlu", detail: "Login, data lintas perangkat, banyak pengguna, atau data online." }, { title: "Supabase", detail: "Salah satu opsi untuk PostgreSQL, autentikasi, storage, dan API." }], "Rahasiakan key dan kredensial yang memberi akses ke layanan."),
    p("statement", "JAGA SECRET", "Jangan unggah API key ke kode publik", [{ title: "Environment variables", detail: "Cara umum menyimpan konfigurasi rahasia di luar kode yang dikirim ke browser." }], "Setelah konsep dasarnya, kita bisa menyiapkan Kilo untuk latihan."),
    p("steps", "SETUP KILO", "Extension utama, CLI sebagai pilihan", [{ title: "VS Code", detail: "Cari Kilo Code di Extensions, pasang, lalu buka dari sidebar. Ikuti instruksi pemasangan resmi terbaru." }, { title: "CLI", detail: "Alternatif terminal: pasang @kilocode/cli dan jalankan `kilo`." }, { title: "Node.js", detail: "Diperlukan untuk menjalankan project yang memakai framework tertentu, seperti React." }], "Pilih model dan izin dengan memperhatikan penggunaan dan privasi."),
    p("tiles", "PENGATURAN LATIHAN", "Mulai dengan kendali yang jelas", [{ title: "Model", detail: "Gunakan Auto Free jika tersedia; periksa batas dan kebijakan provider." }, { title: "Permission", detail: "Membaca boleh; edit dan terminal sebaiknya meminta persetujuan." }, { title: "Autocomplete", detail: "Opsional. Pengaturan modelnya dapat terpisah dari agent utama." }], "Sekarang semua bekal utama sudah siap untuk membuat project."),
  ],
  [
    p("tiles", "PILIH IDE", "Apa yang ingin kamu buat?", [{ title: "Belajar", detail: "Pomodoro, study planner, quiz, flashcard, atau GPA calculator." }, { title: "Keseharian", detail: "Expense calculator, habit tracker, book tracker, atau random meal picker." }, { title: "Karya pribadi", detail: "Portfolio interaktif, event website, mini game, mood journal lokal, atau idemu sendiri." }], "Tentukan fungsi kecil yang membuat ide itu berguna."),
    p("steps", "LANGKAH 1", "Tulis definisi versi pertama", [{ title: "Apa?", detail: "Jelaskan apa yang ingin dibuat." }, { title: "Untuk siapa?", detail: "Tentukan pengguna utamanya." }, { title: "2–4 fungsi", detail: "Pilih beberapa kemampuan inti." }, { title: "Apa yang tidak dibuat?", detail: "Batasi versi pertama agar tetap sederhana." }], "Minta agent merapikan ide, tetapi jangan minta coding dulu."),
    p("steps", "LANGKAH 2–3", "Pahami project dan baca rencana", [{ title: "Ask atau Plan", detail: "Minta fitur minimum, struktur project, dan urutan implementasi." }, { title: "Tinjau", detail: "Baca rencana. Jika terlalu rumit, minta disederhanakan." }, { title: "Rules bila perlu", detail: "Pakai beberapa aturan penting; project sederhana boleh melewatinya." }], "Mulai implementasi dari bagian terkecil yang terlihat."),
    p("steps", "LANGKAH 4–5", "Bangun tampilan, lalu fungsi", [{ title: "Tampilan utama", detail: "Minta satu bagian UI, jalankan aplikasi, lalu lihat hasilnya." }, { title: "Fungsi inti", detail: "Tambahkan timer, input data, kalkulasi, jawaban quiz, atau filter satu per satu." }, { title: "Periksa perubahan", detail: "Lihat file yang berubah dan minta penjelasan bagian penting." }], "Checkpoint ini membandingkan dua cara memulai.", true),
    p("compare", "CHECKPOINT", "Apa yang dibuat lebih dulu?", [{ title: "A · Semua fitur sekaligus", detail: "Sulit menguji bagian mana yang bekerja atau perlu diperbaiki." }, { title: "B · Satu bagian inti", detail: "Tepat. Buat, jalankan, lalu tambahkan fungsi berikutnya." }], "Setelah fungsi inti dibuat, ujilah sendiri di berbagai keadaan."),
  ],
  [
    p("steps", "LANGKAH 6–8", "Uji → Perbaiki → Review", [{ title: "Coba sendiri", detail: "Klik, ketik, ubah ukuran layar, refresh, dan masukkan nilai yang tidak biasa." }, { title: "Cari satu masalah", detail: "Temukan bagian yang membingungkan, rusak, atau kurang nyaman." }, { title: "Minta bukti dan perbaikan", detail: "Minta agent mencari penyebab lalu memperbaiki tanpa merusak bagian lain." }, { title: "Review", detail: "Periksa fungsi, error, perubahan tak perlu, kerumitan, dan pemahamanmu." }], "Kalau ada bagian yang belum kamu pahami, minta agent menjelaskannya."),
    p("compare", "LANGKAH 9", "Pilih jalur deployment", [{ title: "Vercel Drop", detail: "Unggah file atau folder lewat browser; Vercel membangun framework yang dikenali dan memberi URL live." }, { title: "GitHub → Vercel", detail: "Simpan repository sebagai portfolio dan hubungkan ke Vercel untuk deployment dari Git." }, { title: "Bukan syarat", detail: "GitHub opsional. Yang penting project berhasil live dan diuji." }], "Deployment berhasil belum berarti seluruh fitur benar."),
    p("statement", "FINISH LINE", "Orang lain dapat membuka project-mu", [{ title: "Dari ide ke internet", detail: "Tentukan tujuan, arahkan agent, batasi izin, bangun, uji, perbaiki, dan bagikan URL yang berfungsi." }], "Catat keputusan yang kamu buat selama proses."),
    p("tiles", "REFLEKSI", "Empat pertanyaan singkat", [{ title: "Apa yang dibuat?", detail: "Tulis nama dan kegunaan project." }, { title: "AI membantu apa?", detail: "Bagian mana yang paling banyak dibantu agent?" }, { title: "Keputusanmu?", detail: "Apa yang kamu putuskan sendiri?" }, { title: "Apa yang berubah?", detail: "Apa yang kamu ubah setelah melihat hasil AI?" }], "Kalau mau, ceritakan project-mu kepada orang lain."),
    p("compare", "OPSIONAL · BAGIKAN KARYA", "Portfolio, teman, dosen, atau LinkedIn", [{ title: "Ceritakan", detail: "Apa yang kamu buat, mengapa memilihnya, bagaimana AI membantu, dan apa yang kamu putuskan sendiri." }, { title: "Sertakan", detail: "Tautan live. Repository GitHub hanya jika tersedia." }, { title: "Tetap personal", detail: "AI boleh merapikan tulisan, tetapi ceritanya tetap milikmu." }], "Setelah ini, pilih keterampilan lanjutan sesuai kebutuhan project."),
    p("tiles", "LANGKAH BERIKUTNYA", "Tambah kemampuan saat diperlukan", [{ title: "Database dan autentikasi", detail: "Untuk data online lintas perangkat dan akun pengguna." }, { title: "API", detail: "Untuk layanan cuaca, peta, AI, atau data lain." }, { title: "Git dan testing", detail: "Untuk riwayat perubahan, kolaborasi, dan pemeriksaan sistematis." }, { title: "MCP, agents, skills", detail: "Untuk menambah alat atau menyesuaikan workflow saat memang berguna." }], "Rangkum bekal yang sudah kamu pelajari."),
    p("statement", "INTI COURSE", "Ide → Percakapan → Rencana → Bangun → Uji → Perbaiki → Deploy", [{ title: "Pegangan", detail: "Arahkan AI, pertanyakan hasilnya, dan tentukan sendiri kapan software siap digunakan." }], "Kamu sudah menyelesaikan Vibe Coding."),
  ],
];
