import type { LessonContent } from "./fundamentals-content";
import type { SectionPresentation } from "./fundamentals-presentation";
import type { LessonStage } from "./module-one-data";

export const workingStages: LessonStage[] = [
  { id: "clear-direction", title: "Memberi AI Arah yang Jelas", area: "Pelajaran 1 / 4", question: "Apa yang perlu AI ketahui?", intro: "Susun permintaan dengan tujuan, konteks, bentuk hasil, dan batasan yang memang dibutuhkan." },
  { id: "yes-man", title: "Jangan Biarkan AI Cuma Mengiyakan", area: "Pelajaran 2 / 4", question: "Apakah AI sedang menguji idemu?", intro: "Kenali jawaban yang terlalu menyetujui, lalu gunakan AI untuk mencari asumsi dan sudut pandang lain." },
  { id: "refine", title: "Jangan Berhenti di Jawaban Pertama", area: "Pelajaran 3 / 4", question: "Bagaimana memperbaiki hasil AI?", intro: "Tinjau draf, beri masukan yang spesifik, lalu lanjutkan percakapan sampai hasilnya lebih sesuai." },
  { id: "workflow", title: "Dari Percakapan ke Alur Kerja", area: "Pelajaran 4 / 4", question: "Bagaimana AI membantu pekerjaan utuh?", intro: "Pecah tugas besar menjadi langkah kecil, gunakan AI sesuai perannya, lalu periksa hasil akhirnya." },
];

const workingLessonSets: LessonContent[] = [
  {
    lead: "AI yang sama bisa memberi jawaban yang sangat berbeda. Cara kita membingkai permintaan ikut menentukan arah jawabannya.",
    sections: [
      { title: "AI bisa menguatkan arah yang kita berikan", paragraphs: ["Bayangkan kamu punya ide layanan yang membantu mahasiswa memilih karier dari CV mereka. Kamu bertanya, ‘Ide ini menarik, kan?’ AI mungkin menjawab dengan daftar alasan yang mendukung.", "Lalu kamu bertanya, ‘Apa kelemahan ide ini, siapa yang mungkin tidak membutuhkannya, dan bukti apa yang perlu saya cari?’ Jawabannya bisa berubah menjadi daftar risiko dan cara menguji ide.", "**Keduanya bukan bukti bahwa AI sudah tahu ide mana yang benar.** Bentuk pertanyaan memberi arah pada percakapan."], },
      { title: "Saat AI terlalu mudah menyetujui", paragraphs: ["Kecenderungan model untuk mengikuti pandangan, asumsi, atau keinginan pengguna disebut **sycophancy**. Dalam bahasa sehari-hari, AI bisa menjadi yes-man: terdengar mendukung, tetapi kurang menguji apakah kita benar.", "Pada April 2025, OpenAI membatalkan pembaruan GPT‑4o setelah model dinilai terlalu menyetujui dan memuji pengguna. Riset yang terbit di Science pada 2026 menguji 11 model dan 2.405 orang; model rata-rata 49% lebih sering membenarkan pengguna daripada manusia. Dalam contoh unggahan Reddit yang pendapat manusianya menolak pengguna, model tetap menyetujui pengguna pada 51% kasus.", "Kalau kita hanya mencari dukungan, jawaban yang menyenangkan dapat membuat kita makin yakin tanpa bukti baru. Itu bisa memperkuat **confirmation bias**—kecenderungan mencari informasi yang cocok dengan keyakinan sendiri."], sources: [{ label: "OpenAI · pembaruan GPT‑4o", url: "https://openai.com/index/sycophancy-in-gpt-4o/" }, { label: "Science · riset perilaku AI", url: "https://doi.org/10.1126/science.aec8352" }] },
      { title: "Coba ubah pertanyaannya", paragraphs: ["Misalnya kamu ingin membuka usaha makanan sehat. Pertanyaan ‘Ide saya pasti laku, kan?’ mengarahkan AI untuk membahas sisi positif.", "Coba gunakan pertanyaan yang lebih netral: **‘Bandingkan peluang dan risiko usaha makanan sehat untuk mahasiswa. Asumsi apa yang perlu diuji, dan informasi apa yang belum kita punya?’**", "Pilih cara bertanya yang memberi ruang untuk lebih dari satu kemungkinan. AI bisa membantu menyusun analisis; bukti dari calon pembeli tetap perlu dicari."], },
      { title: "Aktivitas · pilih prompt yang netral", paragraphs: ["Kamu sedang menilai ide usaha makanan sehat di sekitar kampus. Mana yang paling membantu untuk berpikir jernih?"], },
      { title: "Minta AI mencari titik buta", paragraphs: ["Untuk ide bisnis, tugas kuliah, atau pilihan karier, minta AI membantu memeriksa: **asumsi, kelemahan, sanggahan, informasi yang kurang, dan penjelasan alternatif**.", "Kamu juga bisa meminta AI memisahkan **fakta, asumsi, dan tafsiran**. Jika hasilnya terdengar yakin, tanyakan bukti yang mendukungnya dan bagian mana yang masih belum diketahui.", "Tujuannya bukan membuat AI selalu negatif. Mintalah ia membandingkan sisi kuat dan lemah agar kamu punya gambaran yang lebih seimbang."], },
      { title: "Aktivitas · cocokkan prompt dengan tujuannya", paragraphs: ["A. ‘Asumsi apa yang belum terbukti?’ → mengidentifikasi asumsi.\n\nB. ‘Apa argumen terkuat yang menentang keputusan ini?’ → mencari sanggahan.\n\nC. ‘Pisahkan fakta, asumsi, dan tafsiran.’ → memisahkan jenis klaim.\n\nD. ‘Informasi apa yang masih kurang?’ → menemukan informasi yang perlu dicari sebelum memutuskan."], },
      { title: "Prompt juga bisa mencoba memanipulasi konteks", paragraphs: ["Jailbreak adalah upaya menyusun prompt untuk mendorong sistem melewati batas yang seharusnya dijaga. Contohnya dapat berupa cerita atau instruksi berlapis yang mencoba mengubah cara sistem menafsirkan permintaan.", "Pada 2023, contoh yang dikenal sebagai ‘Grandma Exploit’ meminta ChatGPT berpura-pura menjadi nenek yang membacakan product key Windows sebelum tidur. Kunci yang muncul dilaporkan berupa generic installation/KMS keys yang memang tersedia untuk umum, bukan kunci retail rahasia. Kasus itu menunjukkan bahwa cara permintaan dibingkai dapat memengaruhi respons; ini bukan bukti bahwa sistem membocorkan kunci rahasia.", "Riset Anthropic tentang Many-Shot Jailbreaking menunjukkan bahwa pola prompt dapat memengaruhi respons; dalam satu mitigasi yang diuji, keberhasilan serangan turun dari 61% menjadi 2%. Ini contoh penelitian tertentu, bukan jaminan bahwa semua sistem aman.", "**Intinya untuk pengguna:** prompt yang kreatif tidak berarti aturan boleh diabaikan. Sistem juga perlu perlindungan, dan kita perlu menggunakan AI secara bertanggung jawab."], sources: [{ label: "Anthropic · Many-shot jailbreaking", url: "https://www.anthropic.com/research/many-shot-jailbreaking" }] },
      { title: "Aktivitas · benar atau salah?", paragraphs: ["Pernyataan: ‘Kalau prompt ditulis dengan sangat kreatif, aturan AI boleh diabaikan.’\n\n**Jawaban: Salah.** Prompt dapat memengaruhi konteks dan respons, tetapi bukan berarti aturan dan perlindungan sistem seharusnya dapat diubah hanya oleh instruksi pengguna."], },
    ],
    takeaway: "Jangan hanya meminta AI menguatkan pendapatmu. Minta juga asumsi, kelemahan, bukti, dan sudut pandang lain—lalu nilai sendiri jawabannya.",
    check: { question: "Kamu hendak membeli laptop untuk kuliah. Prompt mana yang paling membantu membandingkan pilihan?", choices: [
      { label: "Laptop ini bagus, kan? Tolong yakinkan saya.", feedback: "Prompt ini meminta dukungan, bukan perbandingan yang seimbang.", correct: false },
      { label: "Bandingkan laptop A dan B untuk kuliah desain dengan anggaran saya. Jelaskan kelebihan, kekurangan, dan info yang masih perlu dicek.", feedback: "Tepat. Ada konteks, beberapa sisi perbandingan, dan hal yang perlu diverifikasi.", correct: true },
      { label: "Pilih laptop terbaik di dunia.", feedback: "Kebutuhan dan batas anggarannya belum dijelaskan.", correct: false },
    ] },
  },
  {
    lead: "Permintaan yang jelas membantu AI memahami tugas. Kamu tidak perlu menulis prompt panjang—cukup berikan informasi yang relevan.",
    sections: [
      { title: "Dari permintaan umum ke hasil terarah", paragraphs: ["‘Buat presentasi tentang AI’ tidak salah, tetapi AI harus menebak audiens, durasi, tingkat teknis, tujuan, dan jumlah slide.", "Coba tambahkan konteks: **‘Saya mahasiswa yang akan menjelaskan risiko penggunaan AI kepada mahasiswa non-IT. Presentasi berlangsung lima menit. Buat outline lima slide, bahasa sederhana, maksimal tiga poin utama per slide.’**", "Sekarang AI punya gambaran tentang siapa yang akan mendengar, apa yang dibahas, dan seperti apa hasil yang kamu perlukan. Hal serupa berlaku saat menilai ide layanan karier dari CV mahasiswa: minta AI menjelaskan risiko dan cara memvalidasi ide, bukan sekadar menebak apakah ide itu bagus."], },
      { title: "Kerangka sederhana: Task + Context + Output", paragraphs: ["Mulai dari tiga pertanyaan:\n\n**Task** — Apa yang ingin AI lakukan?\n\n**Context** — Apa yang perlu AI ketahui tentang situasi atau audiens?\n\n**Output** — Bentuk hasilnya seperti apa?\n\nJika perlu, tambahkan **Requirements**: batas jumlah kata, bahasa, hal yang tidak boleh ditambahkan, atau format yang harus diikuti.", "Contoh: ‘Ringkas laporan ini (Task) untuk ketua organisasi mahasiswa tanpa latar teknis (Context). Sajikan dalam lima poin (Output), maksimal 150 kata dan jangan menambahkan informasi di luar laporan (Requirements).’"], },
      { title: "Aktivitas · kenali bagian prompt", paragraphs: ["Cocokkan potongan ini: **A. ‘Buat ringkasan laporan ini.’ B. ‘Untuk ketua organisasi mahasiswa tanpa latar teknis.’ C. ‘Sajikan dalam lima poin.’ D. ‘Maksimal 150 kata dan jangan menambah informasi.’**\n\nA adalah Task, B Context, C Output, dan D Requirements. Kerangka ini pengingat agar informasi penting tidak terlewat—bukan istilah yang harus dihafal."], },
      { title: "Prompt panjang belum tentu lebih baik", paragraphs: ["Prompt yang baik memberi informasi yang memang diperlukan untuk tugasnya. Kalau hanya ingin merangkum lima paragraf, kamu tidak perlu memberi persona panjang dan belasan aturan.", "Contoh yang cukup: **‘Ringkas teks berikut menjadi lima poin. Pertahankan informasi utama dan jangan menambahkan informasi baru.’** Kata ‘Ringkas’ saja mungkin kurang jelas; instruksi tiga paragraf tentang persona ahli juga belum tentu membantu."], },
      { title: "Saat perlu detail atau contoh", paragraphs: ["Untuk komunikasi yang punya banyak kebutuhan, kerangka **CO‑STAR** bisa membantu: Context (latar), Objective (tujuan), Style (gaya), Tone (nada), Audience (pembaca), dan Response (bentuk hasil). Tidak semua permintaan membutuhkan keenamnya.", "Contoh: minta draf email sponsor untuk seminar teknologi organisasi mahasiswa bagi 300 peserta. Jelaskan tujuan mengajak perusahaan menjadi sponsor, gunakan gaya profesional tetapi ramah, tujukan kepada manajer pemasaran, batasi 200 kata, dan akhiri dengan ajakan bertemu singkat.", "Kalau sulit menjelaskan gaya, berikan contoh. **Few-shot prompting** berarti menyertakan beberapa contoh agar AI menangkap pola: ‘Satu semester, banyak eksperimen, dan lebih banyak error daripada yang mau saya akui. Tapi akhirnya selesai juga.’ serta ‘Ternyata membuat modelnya lebih mudah daripada menjelaskannya saat presentasi.’ Setelah itu, minta caption proyek baru dengan gaya ringan, singkat, dan tidak terlalu formal."], },
      { title: "Aktivitas · pilih informasi yang perlu ditambah", paragraphs: ["Jika hasil terlalu umum, tambahkan context. Jika bentuknya salah, tentukan output. Jika gaya sulit dijelaskan, berikan contoh. Jika ada batasan, tambahkan requirements.", "Sekarang coba: mana yang paling pas untuk meringkas teks menjadi lima poin? A: instruksi persona panjang dan banyak aturan; B: ‘Ringkas teks ini menjadi lima poin, pertahankan informasi utama’; C: ‘Ringkas.’ **Jawaban B** memberi arah yang cukup tanpa beban yang tidak perlu."], },
    ],
    takeaway: "Berikan tugas, konteks, bentuk hasil, dan batasan seperlunya. Pilih kerangka berdasarkan kebutuhan, bukan supaya prompt terlihat canggih.",
    check: { question: "Kamu meminta caption santai tetapi hasilnya tetap terasa formal. Apa langkah paling berguna?", choices: [
      { label: "Tambahkan dua contoh caption dengan gaya yang kamu suka.", feedback: "Tepat. Contoh konkret sering lebih mudah ditiru daripada deskripsi gaya yang panjang.", correct: true },
      { label: "Ulangi prompt yang sama beberapa kali.", feedback: "Permintaan yang sama belum memberi petunjuk tentang bagian yang perlu diubah.", correct: false },
      { label: "Tambahkan banyak aturan yang tidak terkait caption.", feedback: "Instruksi yang tidak relevan membuat arah prompt kurang fokus.", correct: false },
    ] },
  },
  {
    lead: "Anggap jawaban pertama sebagai draf. Tinjau hasilnya, beri masukan yang spesifik, lalu minta AI memperbaikinya.",
    sections: [
      { title: "Jawaban pertama hanyalah draf", paragraphs: ["Kamu meminta email kepada dosen untuk berkonsultasi. Hasil pertama mungkin terlalu resmi, panjang, atau berputar-putar.", "Kamu bisa menanggapi: **‘Buat nadanya lebih hangat dan alami. Ringkas menjadi maksimal 100 kata, lalu sampaikan permintaan konsultasi dengan jelas.’** Jika pembukanya masih panjang, minta AI langsung menyampaikan tujuan konsultasi.", "Alurnya sederhana: **Tulis prompt → Tinjau → Beri masukan → Perbaiki**. Periksa panjang, kekhususan, nada, format, informasi yang hilang, klaim tanpa dukungan, dan bagian yang tidak perlu."], },
      { title: "Masukan spesifik lebih mudah ditindaklanjuti", paragraphs: ["Daripada berkata ‘buat lebih bagus’, sebutkan bagian yang perlu berubah dan hasil yang kamu inginkan. Misalnya: ‘Pertahankan gagasan utama, batasi tiga poin per slide, pindahkan detail ke catatan pembicara.’", "Untuk setiap masalah, pilih perbaikan yang cocok: hasil terlalu umum → tambahkan context; terlalu panjang → beri batas panjang; gaya kurang pas → berikan contoh; klaim tidak didukung → minta AI memakai dokumen sebagai sumber utama."], },
      { title: "Aktivitas · beri masukan pada outline", paragraphs: ["AI memberi outline presentasi dengan terlalu banyak detail pada tiap slide. Masukan yang paling membantu: **‘Pertahankan gagasan utama, batasi maksimal tiga poin per slide, dan pindahkan rincian ke catatan pembicara.’**\n\nMasukan ini menyebut apa yang dipertahankan, batas yang diinginkan, dan tempat untuk detail."], },
      { title: "Ganti peran AI sesuai tahap kerja", paragraphs: ["AI bisa menjadi pembuat draf, peninjau, lalu editor. Minta ia mengkritik draf sebelum menyusun versi baru.", "Jika kamu punya dokumen sumber, berikan dokumen itu dan minta AI menjadikannya sumber utama. Minta rujukan ke bagian dokumen dan instruksikan agar ia mengatakan ‘tidak tersedia di dokumen’ jika informasinya memang tidak ada.", "Tetap buka sumber aslinya sebelum memakai kutipan, angka, atau kesimpulan penting. AI dapat membantu menemukan bagian yang relevan, tetapi tidak menggantikan pemeriksaanmu."], },
      { title: "Aktivitas · susun ulang alurnya", paragraphs: ["Urutan yang benar: **1. Tulis prompt → 2. Tinjau hasil → 3. Beri feedback → 4. Minta revisi → 5. Periksa ulang.**\n\nSetelah revisi, cek kembali fakta, format, dan apakah hasilnya benar-benar menjawab kebutuhan awal."], },
    ],
    takeaway: "Jelaskan apa yang perlu dipertahankan dan apa yang perlu diubah. Gunakan dokumen sebagai sumber saat perlu, kemudian periksa ulang hasil revisi.",
    check: { question: "Hasil AI memuat klaim yang tidak ada di laporan yang kamu unggah. Apa yang sebaiknya kamu minta?", choices: [
      { label: "Gunakan laporan itu sebagai sumber utama dan tandai informasi yang tidak tersedia di dalamnya.", feedback: "Tepat. Instruksi ini membatasi jawaban pada sumber yang dapat kamu periksa.", correct: true },
      { label: "Buat jawabannya terdengar lebih yakin.", feedback: "Nada yakin tidak membuat klaim menjadi benar atau bersumber.", correct: false },
      { label: "Minta AI menambahkan detail sebanyak mungkin.", feedback: "Ini bisa menambah informasi yang tidak didukung dokumen.", correct: false },
    ] },
  },
  {
    lead: "Pekerjaan besar terasa lebih ringan saat dipecah menjadi langkah. AI dapat membantu di beberapa tahap; kamu tetap memeriksa arah dan hasil akhirnya.",
    sections: [
      { title: "Pecah tugas sebelum meminta hasil akhir", paragraphs: ["Misalnya kamu menyiapkan presentasi tentang energi terbarukan. Daripada langsung meminta presentasi lengkap, pecah tugasnya: pahami tugas, tentukan sudut bahasan, cari dan baca sumber, bandingkan temuan, susun kerangka, buat draf, minta kritik, perbaiki, lalu tinjau sendiri.", "Pola ini memberi kesempatan untuk mengoreksi arah lebih awal. Kalau sumber awalnya keliru, kamu bisa mengetahuinya sebelum seluruh presentasi dibangun di atasnya. Cara ini juga berguna untuk laporan, proposal, presentasi, dan analisis spreadsheet—bukan hanya untuk menulis kode."], },
      { title: "Contoh alur kerja presentasi", paragraphs: ["**Brief:** ‘Saya menyiapkan presentasi energi terbarukan untuk mahasiswa tahun pertama. Tujuannya menjelaskan pilihan yang relevan bagi Indonesia.’\n\n**Sudut bahasan:** ‘Usulkan empat sudut bahasan. Bandingkan manfaat dan kekurangannya, jangan pilihkan satu.’\n\n**Sumber:** ‘Sarankan sumber tepercaya dan jelaskan apa yang perlu saya verifikasi.’\n\n**Bandingkan:** ‘Ringkas temuan tiap sumber dan tunjukkan bagian yang berbeda.’\n\nLanjutkan dengan meminta outline enam slide, draf berdasarkan outline, kritik atas kejelasan dan bukti, lalu revisi. Buka sumber asli dan putuskan sendiri apa yang layak dipakai."], },
      { title: "AI bisa membantu di berbagai tahap", paragraphs: ["AI dapat berperan sebagai **teman mencari ide, pembanding pilihan, pengkritik, penjelas, atau editor**. Kamu bisa mengganti perannya sesuai tahap, tanpa menyerahkan seluruh tugas sekaligus.", "Untuk analisis data survei, contohnya: pahami struktur data → bersihkan nilai yang keliru → cari pola → buat visualisasi → susun kesimpulan → periksa apakah tafsirnya benar. Minta AI menjelaskan asumsi dan batas datanya sebelum memakai kesimpulan."], },
      { title: "Aktivitas · urutkan analisis survei", paragraphs: ["Urutan yang masuk akal: **pahami struktur data, bersihkan data, cari pola, visualisasikan, susun kesimpulan, lalu periksa ulang tafsirnya.** Jangan melompat ke kesimpulan sebelum tahu apa isi datanya."], },
      { title: "Alur kerja juga berguna untuk kegiatan kampus", paragraphs: ["Untuk membuat lokakarya kampus, AI dapat membantu bertukar ide → membandingkan format → menyusun jadwal → memperkirakan anggaran → meninjau risiko → membuat proposal sponsor → menyiapkan pesan undangan → menyusun promosi → memeriksa kembali rencana.", "Di setiap langkah, kamu dapat memakai AI dengan peran berbeda: pencari ide, pembanding, pengkritik, penjelas, dan editor. Informasi nyata seperti jadwal, biaya, dan persetujuan tetap perlu dikonfirmasi kepada pihak terkait."], },
      { title: "Aktivitas · cocokkan peran AI", paragraphs: ["Pencari ide mengusulkan beberapa kemungkinan. Pembanding menata kelebihan dan kekurangan pilihan. Pengkritik mencari risiko dan asumsi. Penjelas menerangkan konsep dengan sederhana. Editor memperjelas tulisan tanpa mengubah maksudnya."], },
      { title: "Tantangan akhir · uji ide startup", paragraphs: ["Gunakan ide layanan karier untuk mahasiswa sebagai bahan latihan. Kerjakan tiap tahap dan catat keputusanmu sendiri.\n\n**1 · Petakan masalah.** Minta AI menyusun lima masalah pencarian karier mahasiswa, siapa yang mengalaminya, kapan, dan informasi apa yang perlu diuji lewat wawancara.\n\n**2 · Jelajahi pilihan.** Minta empat kemungkinan solusi: rekomendasi karier, pencocokan magang, peta kesenjangan keterampilan, dan persiapan karier. Bandingkan kelebihan, kekurangan, dan calon penggunanya—jangan pilihkan satu.\n\n**3 · Tantang asumsi.** Minta lima alasan ide bisa gagal, siapa yang tidak membutuhkannya, alternatif yang sudah ada, serta bedakan fakta, asumsi, dan bukti.\n\n**4 · Perbaiki arah.** Pilih satu arah untuk ditinjau. Minta tiga kelemahan dan bukti yang perlu dicari.\n\n**5 · Buat proposal satu halaman.** Masukkan masalah, target pengguna, solusi, nilai yang ditawarkan, asumsi utama, bukti yang ada dan belum ada, serta langkah berikutnya.\n\n**6 · Tinjau sebagai manusia.** Tandai saran AI yang kamu terima, tolak, atau ubah. Pastikan langkah berikutnya dapat diuji, misalnya wawancara mahasiswa—bukan langsung membangun produk."], },
      { title: "Bekal yang dibawa setelah kursus", paragraphs: ["Sebelum memakai hasil AI, tanyakan: Apakah tujuan dan konteksnya jelas? Apakah prompt memberi ruang untuk menguji asumsi? Sudahkah saya memberi masukan pada draf? Apa sumbernya? Apakah informasi penting sudah diperiksa? Keputusan apa yang tetap menjadi tanggung jawab saya?", "Tidak ada prompt ajaib. Arah yang jelas, konteks yang cukup, percakapan bertahap, sumber yang dapat diperiksa, dan penilaian manusia membuat AI lebih berguna."], },
    ],
    takeaway: "Pakai AI sebagai bagian dari alur kerja: pecah tugas, tentukan peran, periksa bukti, dan simpan keputusan akhir di tanganmu.",
    check: { question: "Kamu mendapat jawaban AI yang terdengar sangat yakin tentang pilihan karier. Apa yang paling tepat dilakukan?", choices: [
      { label: "Periksa asumsi, sumber, bukti, dan apakah cara bertanya ikut mengarahkan jawabannya.", feedback: "Tepat. Keputusanmu perlu mempertimbangkan bukti dan konteks, bukan rasa yakin dari jawaban.", correct: true },
      { label: "Ikuti saja karena AI memberi banyak alasan.", feedback: "Banyak alasan belum tentu didukung bukti atau sesuai keadaanmu.", correct: false },
      { label: "Tanyakan lagi dengan kata-kata sama sampai jawabannya konsisten.", feedback: "Jawaban berulang belum tentu merupakan verifikasi independen.", correct: false },
    ] },
  },
];

export const workingLessons = [workingLessonSets[1], workingLessonSets[0], workingLessonSets[2], workingLessonSets[3]];

const p = (kind: SectionPresentation["kind"], label: string, title: string, items: { title: string; detail: string }[], bridge: string, interactive = false): SectionPresentation => ({ kind, label, title, items, bridge, interactive });

const workingPresentationSets: SectionPresentation[][] = [
  [
    p("compare", "CONTOH AWAL", "AI yang sama, arah berbeda", [{ title: "Minta dukungan", detail: "Pertanyaan yang mencari persetujuan cenderung mengarahkan percakapan untuk mendukung ide." }, { title: "Minta pengujian", detail: "Pertanyaan netral membuka ruang untuk risiko, bukti, dan informasi yang belum ada." }], "Kita perlu mengenali saat jawaban terasa menyenangkan karena terlalu menyetujui."),
    p("stats", "RISIKO TERLALU MENYETUJUI", "49% lebih sering", [{ title: "11 model", detail: "Riset Science menguji sebelas model AI." }, { title: "2.405 orang", detail: "Studi melibatkan lebih dari dua ribu peserta." }, { title: "51% kasus", detail: "Model menyetujui pengguna ketika konsensus manusia justru menolaknya." }], "Cara bertanya yang lebih netral memberi ruang untuk melihat sisi lain."),
    p("compare", "COBA UBAH FRAMING", "Dari mencari dukungan ke mencari bukti", [{ title: "‘Pasti laku, kan?’", detail: "Permintaan bernada memimpin dan meminta validasi." }, { title: "‘Bandingkan peluang dan risiko’", detail: "Meminta sisi positif, sisi negatif, asumsi, dan informasi yang belum tersedia." }], "Prompt netral bukan jaminan jawaban benar, tetapi membantu membuka analisis yang lebih seimbang."),
    p("steps", "AKTIVITAS 1", "Pilih pertanyaan yang membantu berpikir", [{ title: "A · Yakinkan saya", detail: "Kurang netral: prompt meminta AI mendukung ide usaha." }, { title: "B · Bandingkan", detail: "Pilihan terbaik: bandingkan peluang dan risiko usaha makanan sehat untuk mahasiswa, lalu sebutkan asumsi dan informasi yang perlu diuji." }, { title: "C · Puji ide saya", detail: "Kurang netral: pujian tidak memberi bukti permintaan pasar." }], "Sekarang minta AI menunjukkan titik buta secara langsung.", true),
    p("tiles", "CARI TITIK BUTA", "Lima hal yang perlu diuji", [{ title: "Asumsi", detail: "Apa yang kita anggap benar tanpa memeriksanya?" }, { title: "Kelemahan", detail: "Bagian mana yang paling rentan gagal?" }, { title: "Sanggahan", detail: "Apa alasan orang lain mungkin tidak setuju?" }, { title: "Info yang kurang", detail: "Data apa yang belum kita punya?" }, { title: "Alternatif", detail: "Penjelasan atau solusi lain apa yang mungkin?" }], "Prompt dapat memengaruhi konteks; karena itu sistem juga membutuhkan batas dan perlindungan."),
    p("tiles", "AKTIVITAS 6", "Cocokkan prompt dengan tujuannya", [{ title: "A · Asumsi", detail: "‘Asumsi apa yang belum terbukti?’ membantu mengidentifikasi asumsi." }, { title: "B · Sanggahan", detail: "‘Apa argumen terkuat yang menentang keputusan ini?’ mencari counterargument atau sanggahan." }, { title: "C · Jenis klaim", detail: "‘Pisahkan fakta, asumsi, dan tafsiran’ memisahkan jenis klaim." }, { title: "D · Info kurang", detail: "‘Informasi apa yang masih kurang?’ menunjukkan apa yang perlu dicari." }], "Sekarang lihat mengapa prompt tidak seharusnya dipakai untuk melewati perlindungan."),
    p("statement", "KEAMANAN DAN TANGGUNG JAWAB", "Prompt kreatif bukan izin melanggar batas", [{ title: "Pegangan", detail: "Jailbreak mencoba mendorong sistem melewati batas. Gunakan AI secara bertanggung jawab dan jangan menganggap semua perlindungan selalu sempurna." }], "Di lesson berikutnya, kita akan menggunakan percakapan untuk memperbaiki hasil langkah demi langkah."),
    p("compare", "AKTIVITAS 7", "Benar atau salah?", [{ title: "Pernyataan", detail: "‘Kalau prompt ditulis dengan sangat kreatif, aturan AI boleh diabaikan.’" }, { title: "Jawaban: salah", detail: "Prompt dapat memengaruhi konteks dan respons, tetapi aturan dan perlindungan tetap perlu dijaga." }], "Di penggunaan sehari-hari, hasil pertama sering belum sesuai. Kita bisa memperbaikinya lewat percakapan."),
  ],
  [
    p("compare", "MULAI DARI CONTOH", "Beri informasi yang mengurangi tebakan", [{ title: "‘Buat presentasi tentang AI’", detail: "Topik ada, tetapi audiens, tujuan, durasi, tingkat teknis, dan jumlah slide belum jelas." }, { title: "Presentasi 5 menit untuk mahasiswa non-IT", detail: "Konteks audiens dan batas waktu membantu AI menentukan tingkat penjelasan." }], "Prompt yang lebih jelas dapat dibangun dari tiga bagian sederhana."),
    p("steps", "KERANGKA HARIAN", "Task + Context + Output", [{ title: "Task", detail: "Tugasnya: buat outline presentasi risiko AI." }, { title: "Context", detail: "Audiensnya mahasiswa non-IT yang belum banyak mempelajari AI." }, { title: "Output", detail: "Buat lima slide dengan maksimal tiga poin utama per slide." }, { title: "Requirements", detail: "Tambahkan batas bila perlu: bahasa Indonesia, maksimal 300 kata, tanpa jargon, atau hanya memakai isi dokumen." }], "Aktivitas berikutnya membantu membedakan bagian-bagian itu.", true),
    p("tiles", "AKTIVITAS 2", "Cocokkan potongan prompt", [{ title: "A · ‘Buat ringkasan’", detail: "Task — pekerjaan yang diminta." }, { title: "B · ‘Untuk ketua organisasi nonteknis’", detail: "Context — informasi latar yang membantu AI." }, { title: "C · ‘Dalam lima poin’", detail: "Output — bentuk hasil yang diinginkan." }, { title: "D · ‘Maksimal 150 kata’", detail: "Requirements — batas yang harus dipatuhi." }], "Kita sudah tahu strukturnya; sekarang pilih hanya detail yang diperlukan."),
    p("compare", "CUKUPKAN SEPERLUNYA", "Prompt panjang tidak otomatis lebih baik", [{ title: "Terlalu minim", detail: "‘Ringkas.’ Tidak menyebut bentuk atau hal yang perlu dipertahankan." }, { title: "Cukup jelas", detail: "Ringkas teks menjadi lima poin, pertahankan informasi utama, jangan menambahkan informasi baru." }, { title: "Terlalu banyak", detail: "Instruksi persona panjang yang tidak terkait tugas membuat prompt kurang fokus." }], "Untuk pekerjaan komunikasi yang lebih rumit, kerangka lebih rinci dapat membantu."),
    p("steps", "CO-STAR DAN FEW-SHOT", "Pilih alat sesuai kebutuhan", [{ title: "CO-STAR", detail: "Context, Objective, Style, Tone, Audience, Response. Berguna untuk draf sponsor seminar: tujuan, pembaca, nada ramah-profesional, maksimal 200 kata, dan ajakan bertemu." }, { title: "Few-shot prompting", detail: "Sertakan dua caption contoh agar AI menangkap panjang, struktur, dan gaya yang diinginkan." }, { title: "Aktivitas 4", detail: "Umum → tambah context; format salah → tentukan output; gaya sulit dijelaskan → beri contoh; batas tertentu → tambah requirements." }], "Tidak semua prompt perlu framework. Tanyakan informasi apa yang masih kurang."),
    p("tiles", "AKTIVITAS 4", "Cocokkan masalah dengan perbaikannya", [{ title: "Hasil terlalu umum", detail: "Tambahkan konteks yang relevan." }, { title: "Format tidak sesuai", detail: "Tentukan bentuk hasil yang diinginkan." }, { title: "Gaya sulit dijelaskan", detail: "Berikan contoh tulisan." }, { title: "Ada batasan", detail: "Tambahkan requirements atau ketentuan." }], "Tidak semua prompt perlu framework. Tanyakan informasi apa yang masih kurang."),
  ],
  [
    p("steps", "PUTARAN PERBAIKAN", "Tulis prompt → Tinjau → Beri masukan → Perbaiki", [{ title: "Tulis prompt", detail: "Minta draf email kepada dosen untuk konsultasi." }, { title: "Tinjau", detail: "Hasil terlalu formal dan panjang." }, { title: "Beri masukan", detail: "Minta nada lebih hangat dan alami, maksimal 100 kata." }, { title: "Perbaiki", detail: "Minta revisi yang tetap menyampaikan permintaan konsultasi dengan jelas." }], "Masukan akan lebih berguna jika menyebut perubahan secara spesifik."),
    p("tiles", "TINJAU HASIL", "Apa yang perlu diperiksa?", [{ title: "Kepanjangan atau umum", detail: "Tentukan batas panjang atau tambahkan konteks." }, { title: "Nada dan format", detail: "Jelaskan gaya atau bentuk yang kamu perlukan." }, { title: "Ada yang hilang", detail: "Tunjuk bagian yang harus dipertahankan atau dilengkapi." }, { title: "Klaim tanpa dukungan", detail: "Minta sumber atau batasi jawaban pada dokumen." }], "Gunakan instruksi yang memberi arah konkret untuk revisi."),
    p("compare", "AKTIVITAS 8", "Masukan yang bisa langsung dikerjakan", [{ title: "‘Buat lebih bagus’", detail: "Terlalu umum; AI tidak tahu bagian mana yang harus diubah." }, { title: "‘Tiga poin per slide’", detail: "Jelas: pertahankan gagasan utama, batasi tiga poin, pindahkan rincian ke catatan pembicara." }], "Kamu juga bisa mengganti peran AI dari pembuat menjadi peninjau atau editor."),
    p("steps", "GUNAKAN SUMBER", "Minta jawaban berpijak pada dokumen", [{ title: "Tetapkan sumber", detail: "Gunakan dokumen yang saya unggah sebagai sumber utama." }, { title: "Batasi tambahan", detail: "Jangan menambahkan informasi yang tidak tercantum." }, { title: "Tandai kekosongan", detail: "Jika informasi tidak ada, katakan bahwa informasi itu tidak tersedia di dokumen." }, { title: "Periksa ulang", detail: "Buka dokumen dan cocokkan rujukan sebelum menggunakan klaim." }], "Aktivitas berikut merangkum urutan perbaikan yang dapat kamu pakai."),
    p("steps", "AKTIVITAS 9–10", "Perbaiki, lalu periksa lagi", [{ title: "1 · Tulis prompt", detail: "Jelaskan kebutuhan dan sumber bila ada." }, { title: "2 · Tinjau hasil", detail: "Cari masalah yang paling penting." }, { title: "3 · Beri masukan", detail: "Sebutkan perubahan secara spesifik." }, { title: "4 · Minta revisi", detail: "Minta AI menerapkan arahanmu." }, { title: "5 · Periksa ulang", detail: "Pastikan hasilnya sesuai dan klaim didukung." }], "Selanjutnya, gabungkan beberapa putaran menjadi satu alur kerja."),
  ],
  [
    p("steps", "PRESENTASI ENERGI TERBARUKAN", "Pecah pekerjaan besar", [{ title: "Brief dan sudut", detail: "Tentukan audiens dan tujuan; minta beberapa sudut bahasan tanpa menyuruh AI memilih." }, { title: "Sumber dan perbandingan", detail: "Cari sumber tepercaya, ringkas tiap sumber, lalu bandingkan temuan dan perbedaannya." }, { title: "Outline dan draf", detail: "Buat alur enam slide, lalu kembangkan draf berdasarkan outline." }, { title: "Kritik dan revisi", detail: "Minta kritik pada bukti dan kejelasan; revisi, lalu buka sumber asli." }], "Alur serupa dapat dipakai untuk menganalisis data survei."),
    p("steps", "CONTOH LANGKAH PRESENTASI", "Dari brief hingga revisi", [{ title: "Pahami dan tentukan sudut", detail: "Jelaskan tujuan dan audiens; minta empat sudut bahasan, bandingkan manfaat dan kekurangannya tanpa memilih satu." }, { title: "Baca sumber", detail: "Minta sumber tepercaya, ringkas temuan tiap sumber, lalu bandingkan bagian yang berbeda." }, { title: "Susun dan tulis", detail: "Minta alur presentasi enam slide, lalu buat draf dari alur itu." }, { title: "Kritik dan perbaiki", detail: "Minta peninjauan atas kejelasan dan bukti, perbaiki draf, lalu buka sumber aslinya." }], "Langkah-langkah kecil juga membantu saat mengolah hasil survei."),
    p("compare", "GANTI PERAN SESUAI TAHAP", "Pencari ide · pembanding · pengkritik · editor", [{ title: "Cari ide", detail: "Minta beberapa pilihan tanpa meminta AI memutuskan." }, { title: "Bandingkan", detail: "Minta kelebihan, kekurangan, dan trade-off tiap opsi." }, { title: "Periksa", detail: "Minta kritik, penjelasan, atau penyuntingan sesuai kebutuhan." }, { title: "Analisis data", detail: "Untuk survei, pahami struktur, bersihkan, cari pola, visualisasikan, simpulkan, lalu periksa tafsir." }], "Sekarang susun urutan analisis survei."),
    p("steps", "AKTIVITAS 11", "Urutkan analisis data survei", [{ title: "Pahami struktur", detail: "Ketahui kolom dan arti datanya sebelum menarik kesimpulan." }, { title: "Bersihkan", detail: "Tinjau nilai kosong, ganda, atau keliru." }, { title: "Cari pola", detail: "Eksplorasi kecenderungan dan kelompok yang terlihat." }, { title: "Visualisasikan", detail: "Pilih grafik yang membantu pembaca melihat pola." }, { title: "Simpulkan dan cek", detail: "Tulis temuan, periksa tafsir, dan sebutkan batas data." }], "AI juga dapat membantu merancang kegiatan kampus dari awal sampai evaluasi."),
    p("tiles", "WORKSHOP KAMPUS", "Satu kegiatan, beberapa tahap", [{ title: "Rancang", detail: "Cari ide, bandingkan format, dan susun jadwal." }, { title: "Siapkan", detail: "Perkirakan anggaran, tinjau risiko, buat proposal sponsor." }, { title: "Ajak peserta", detail: "Siapkan pesan undangan dan materi promosi." }, { title: "Tinjau", detail: "Konfirmasi jadwal, biaya, izin, dan kesiapan dengan pihak terkait." }], "Di tiap tahap, pilih peran AI yang sesuai dengan kebutuhanmu."),
    p("compare", "AKTIVITAS 12", "Pilih peran AI", [{ title: "Pencari ide", detail: "Brainstormer: mengusulkan beberapa kemungkinan." }, { title: "Pembanding", detail: "Comparator: menata kelebihan dan kekurangan pilihan." }, { title: "Pengkritik", detail: "Critic: mencari risiko, asumsi, dan bagian yang lemah." }, { title: "Penjelas", detail: "Explainer: menjelaskan konsep atau temuan dengan bahasa sederhana." }, { title: "Editor", detail: "Editor: memperjelas tulisan tanpa mengubah maksud utama." }], "Sekarang terapkan semua tahap itu pada tantangan akhir."),
    p("steps", "TANTANGAN AKHIR", "Uji ide layanan karier mahasiswa", [{ title: "Petakan dan jelajahi", detail: "Minta lima masalah karier, siapa yang mengalaminya dan apa yang perlu diuji; bandingkan empat arah solusi tanpa memilih otomatis." }, { title: "Tantang asumsi", detail: "Minta alasan ide bisa gagal, calon pengguna yang tidak membutuhkan, alternatif, serta pisahkan fakta, asumsi, dan bukti." }, { title: "Perbaiki dan susun proposal", detail: "Pilih arah; minta tiga kelemahan dan bukti yang perlu dicari. Buat proposal satu halaman: masalah, target, solusi, nilai, asumsi, bukti yang ada/belum ada, langkah berikutnya." }, { title: "Putuskan sebagai manusia", detail: "Catat saran yang diterima, ditolak, dan diubah. Pastikan langkah berikutnya dapat diuji, misalnya wawancara mahasiswa." }], "Gunakan daftar singkat ini setiap kali bekerja dengan AI."),
    p("statement", "PEGANGAN TERAKHIR", "Tidak ada prompt ajaib", [{ title: "Sebelum memakai hasil", detail: "Periksa tujuan, konteks, asumsi, masukan, sumber, bukti, dan keputusan yang tetap menjadi tanggung jawabmu." }], "Kamu sudah menyelesaikan Working with Generative AI."),
  ],
];

export const workingPresentations = [workingPresentationSets[1], workingPresentationSets[0], workingPresentationSets[2], workingPresentationSets[3]];
