import type { LessonContent } from "./fundamentals-content";
import type { Activity } from "./activities/types";
import type { SectionPresentation } from "./fundamentals-presentation";
import type { LessonStage } from "./module-one-data";

export const workingStages: LessonStage[] = [
  { id: "clear-direction", title: "Memberi AI Arah yang Jelas", area: "Pelajaran 1 / 4", question: "Apa yang perlu AI ketahui?", intro: "Kamu diminta membuat presentasi lima menit. Lihat bagaimana sedikit konteks mengubah jawaban AI dari tebakan umum menjadi draf yang bisa dipakai." },
  { id: "yes-man", title: "Jangan Biarkan AI Cuma Mengiyakan", area: "Pelajaran 2 / 4", question: "Apakah AI sedang menguji idemu?", intro: "Sebuah ide terdengar hebat ketika AI terus memujinya. Kita coba pertanyaan lain agar kelemahan dan bukti yang belum ada ikut terlihat." },
  { id: "refine", title: "Jangan Berhenti di Jawaban Pertama", area: "Pelajaran 3 / 4", question: "Bagaimana memperbaiki hasil AI?", intro: "Draf email untuk dosen sudah ada, tetapi nadanya kaku. Kamu akan belajar memberi arahan yang jelas agar revisinya lebih sesuai." },
  { id: "workflow", title: "Dari Percakapan ke Alur Kerja", area: "Pelajaran 4 / 4", question: "Bagaimana AI membantu pekerjaan utuh?", intro: "Presentasi, survei, atau acara kampus punya banyak tahap. Ikuti satu pekerjaan dari ide sampai selesai sambil memeriksa keputusan di setiap belokan." },
];

const workingLessonSets: LessonContent[] = [
  {
    lead: "Teman sekelompokmu mengusulkan layanan pencarian karier untuk mahasiswa. Saat kamu meminta pendapat AI, jawabannya terdengar sangat mendukung. Sebelum ikut yakin, coba lihat apa yang terjadi jika pertanyaannya diubah.",
    sections: [
      { title: "AI bisa menguatkan arah yang kita berikan", paragraphs: ["Untuk menguji ide layanan karier tadi, kamu mulai dengan pertanyaan yang mencari dukungan. Kamu bertanya, ‘Ide ini menarik, kan?’ AI mungkin menjawab dengan daftar alasan yang mendukung.", "Lalu kamu bertanya, ‘Apa kelemahan ide ini, siapa yang mungkin tidak membutuhkannya, dan bukti apa yang perlu saya cari?’ Jawabannya bisa berubah menjadi daftar risiko dan cara menguji ide.", "**Keduanya bukan bukti bahwa AI sudah tahu ide mana yang benar.** Bentuk pertanyaan memberi arah pada percakapan."], },
      { title: "Saat AI terlalu mudah menyetujui", paragraphs: ["Jika AI terus memuji ide layanan karier tanpa menanyakan siapa yang membutuhkannya, kamu belum mendapat penilaian yang seimbang. Kecenderungan model mengikuti pandangan atau keinginan pengguna disebut **sycophancy**. Dalam bahasa sehari-hari, AI bisa menjadi yes-man: terdengar mendukung, tetapi kurang menguji apakah kita benar.", "Pada April 2025, OpenAI membatalkan pembaruan GPT‑4o setelah model dinilai terlalu menyetujui dan memuji pengguna. Riset yang terbit di Science pada 2026 menguji 11 model dan 2.405 orang; model rata-rata 49% lebih sering membenarkan pengguna daripada manusia. Dalam contoh unggahan Reddit yang pendapat manusianya menolak pengguna, model tetap menyetujui pengguna pada 51% kasus.", "Kalau kita hanya mencari dukungan, jawaban yang menyenangkan dapat membuat kita makin yakin tanpa bukti baru. Itu bisa memperkuat **confirmation bias**, yaitu kecenderungan mencari informasi yang cocok dengan keyakinan sendiri."], sources: [{ label: "OpenAI · pembaruan GPT‑4o", url: "https://openai.com/index/sycophancy-in-gpt-4o/" }, { label: "Science · riset perilaku AI", url: "https://doi.org/10.1126/science.aec8352" }] },
      { title: "Coba ubah pertanyaannya", paragraphs: ["Sekarang coba cara bertanya yang sama pada ide lain: usaha makanan sehat di sekitar kampus. Pertanyaan ‘Ide saya pasti laku, kan?’ mengarahkan AI untuk membahas sisi positif.", "Pilih cara bertanya yang memberi ruang untuk lebih dari satu kemungkinan. AI bisa membantu menyusun analisis; bukti dari calon pembeli tetap perlu dicari."], reveal: { label: "Lihat satu contoh rumusan", paragraphs: ["**‘Bandingkan peluang dan risiko usaha makanan sehat untuk mahasiswa. Asumsi apa yang perlu diuji, dan informasi apa yang belum kita punya?’**", "Ini hanya satu contoh. Rumusanmu sendiri boleh berbeda selama ketiga syarat di latihan terpenuhi."] }, },
      { title: "Aktivitas · pilih prompt yang netral", paragraphs: ["Kamu sedang menilai ide usaha makanan sehat di sekitar kampus. Dari pilihan berikut, rumusan pertanyaan mana yang paling membantumu menilai ide itu dengan jernih?"], },
      { title: "Minta AI mencari titik buta", paragraphs: ["Baik untuk layanan karier maupun usaha makanan tadi, minta AI membantu memeriksa: **asumsi, kelemahan, sanggahan, informasi yang kurang, dan penjelasan alternatif**.", "Kamu juga bisa meminta AI memisahkan **fakta, asumsi, dan tafsiran**. Jika hasilnya terdengar yakin, tanyakan bukti yang mendukungnya dan bagian mana yang masih belum diketahui.", "Tujuannya bukan membuat AI selalu negatif. Mintalah ia membandingkan sisi kuat dan lemah agar kamu punya gambaran yang lebih seimbang."], },
      { title: "Aktivitas · cocokkan prompt dengan tujuannya", paragraphs: ["Kamu sudah mencoba pertanyaan yang lebih netral. Empat prompt berikut membuka titik buta yang berbeda-beda. Cocokkan dulu sebelum melihat kunci."], },
      { title: "Prompt juga bisa mencoba memanipulasi konteks", paragraphs: ["Cara menulis permintaan juga punya batas. Ada prompt yang sengaja disusun untuk mendorong sistem melewati aturan yang seharusnya dijaga; upaya ini disebut **jailbreak**. Contohnya dapat berupa cerita atau instruksi berlapis yang mencoba mengubah cara sistem menafsirkan permintaan.", "Misalnya, seseorang menyisipkan instruksi baru di dalam cerita panjang agar permintaan yang seharusnya ditolak terlihat seperti bagian dari permainan peran. Bentuk ceritanya dapat memengaruhi respons, tetapi tidak mengubah batas yang seharusnya berlaku.", "Riset Anthropic tentang Many-Shot Jailbreaking menunjukkan bahwa banyak contoh yang disusun berulang dalam satu prompt juga dapat memengaruhi respons. Perlindungan sistem perlu diuji dan diperbaiki; pengguna tetap perlu menghormati batasnya.", "**Intinya untuk pengguna:** prompt yang kreatif tidak berarti aturan boleh diabaikan. Sistem juga perlu perlindungan, dan kita perlu menggunakan AI secara bertanggung jawab."], sources: [{ label: "Anthropic · Many-shot jailbreaking", url: "https://www.anthropic.com/research/many-shot-jailbreaking" }] },
      { title: "Aktivitas · benar atau salah?", paragraphs: ["Setelah membaca contoh prompt yang mencoba melewati batas, nilai pernyataan berikut sebelum membuka alasannya."], },
    ],
    takeaway: "Untuk ide layanan karier tadi, pujian AI belum cukup. Minta ia mencari calon pengguna yang mungkin tidak terbantu, lalu cari bukti dari orang sungguhan sebelum memutuskan langkah berikutnya.",
    check: { question: "Kamu hendak membeli laptop untuk kuliah. Prompt mana yang paling membantu membandingkan pilihan?", choices: [
      { label: "Laptop ini bagus, kan? Tolong yakinkan saya.", feedback: "Prompt ini meminta dukungan, bukan perbandingan yang seimbang.", correct: false },
      { label: "Bandingkan laptop A dan B untuk kuliah desain dengan anggaran saya. Jelaskan kelebihan, kekurangan, dan info yang masih perlu dicek.", feedback: "Tepat. Ada konteks, beberapa sisi perbandingan, dan hal yang perlu diverifikasi.", correct: true },
      { label: "Pilih laptop terbaik di dunia.", feedback: "Kebutuhan dan batas anggarannya belum dijelaskan.", correct: false },
    ] },
  },
  {
    lead: "Kelompokmu mendapat tugas menjelaskan AI kepada teman sekelas dalam lima menit. Kamu meminta bantuan AI membuat presentasi, tetapi draf yang muncul terlalu panjang dan penuh istilah. Apa yang perlu kamu ceritakan agar ia paham tugasnya?",
    sections: [
      { title: "Dari permintaan umum ke hasil terarah", paragraphs: ["Lihat draf yang datang: slide pertama menjelaskan sejarah AI, slide kedua penuh istilah, dan pesan yang ingin kamu sampaikan belum tampak. AI menebak karena ia belum tahu siapa pendengarnya, berapa lama waktumu, atau tujuan presentasimu.\n\n> Draf AI — Slide 1: Sejarah AI. Slide 2: Istilah teknis. Slide 3: Daftar teknologi. Belum ada pesan utama untuk teman sekelasmu.", "Coba tambahkan konteks: ‘Saya mahasiswa yang akan menjelaskan risiko penggunaan AI kepada mahasiswa non-IT. Presentasi berlangsung lima menit. Buat outline lima slide, bahasa sederhana, maksimal tiga poin utama per slide.’", "Sekarang AI punya gambaran tentang siapa yang akan mendengar, apa yang dibahas, dan seperti apa hasil yang kamu perlukan. Cara yang sama membantu saat menilai ide layanan karier dari CV mahasiswa: minta AI menjelaskan risiko dan cara memvalidasi ide, bukan sekadar menebak apakah ide itu bagus."], },
      { title: "Kerangka sederhana: Task + Context + Output", paragraphs: ["Draf slide tadi meleset karena AI harus menebak. Sebelum meminta versi baru, jawab tiga pertanyaan ini:\n\n**Task**: apa yang ingin AI lakukan?\n\n**Context**: apa yang perlu AI ketahui tentang situasi atau audiensnya?\n\n**Output**: bentuk hasilnya seperti apa?\n\nJika perlu, tambahkan **Requirements**: batas jumlah kata, bahasa, hal yang tidak boleh ditambahkan, atau format yang harus diikuti.", "Contoh: ‘Ringkas laporan ini (Task) untuk ketua organisasi mahasiswa tanpa latar teknis (Context). Sajikan dalam lima poin (Output), maksimal 150 kata dan jangan menambahkan informasi di luar laporan (Requirements).’"], },
      { title: "Aktivitas · kenali bagian prompt", paragraphs: ["Cara membaca prompt tadi bisa dipakai pada tugas lain. Dalam contoh ringkasan laporan berikut, tunjuk bagian yang menjelaskan tugas, pembaca, bentuk hasil, dan batasannya."], },
      { title: "Prompt panjang belum tentu lebih baik", paragraphs: ["Untuk presentasi lima menit tadi, keterangan tentang audiens dan durasi membantu. Namun menambah instruksi yang tidak berhubungan justru membuat permintaan sulit dibaca. Kalau hanya ingin merangkum lima paragraf, kamu tidak perlu memberi persona panjang dan belasan aturan.", "Contoh yang cukup: **‘Ringkas teks berikut menjadi lima poin. Pertahankan informasi utama dan jangan menambahkan informasi baru.’** Kata ‘Ringkas’ saja mungkin kurang jelas; instruksi tiga paragraf tentang persona ahli juga belum tentu membantu."], },
      { title: "Saat perlu detail atau contoh", paragraphs: ["Jika tugasmu lebih rumit, misalnya menulis email sponsor seminar, kamu mungkin perlu menjelaskan nada dan pembacanya juga. Kerangka **CO‑STAR** bisa membantu: Context (latar), Objective (tujuan), Style (gaya), Tone (nada), Audience (pembaca), dan Response (bentuk hasil). Tidak semua permintaan membutuhkan keenamnya.", "Contoh: minta draf email sponsor untuk seminar teknologi organisasi mahasiswa bagi 300 peserta. Jelaskan tujuan mengajak perusahaan menjadi sponsor, gunakan gaya profesional tetapi ramah, tujukan kepada manajer pemasaran, batasi 200 kata, dan akhiri dengan ajakan bertemu singkat.", "Kalau sulit menjelaskan gaya, berikan contoh. **Few-shot prompting** berarti menyertakan beberapa contoh agar AI menangkap pola: ‘Satu semester, banyak eksperimen, dan lebih banyak error daripada yang mau saya akui. Tapi akhirnya selesai juga.’ serta ‘Ternyata membuat modelnya lebih mudah daripada menjelaskannya saat presentasi.’ Setelah itu, minta caption proyek baru dengan gaya ringan, singkat, dan tidak terlalu formal."], },
      { title: "Aktivitas · pilih informasi yang perlu ditambah", paragraphs: ["Setelah mencoba beberapa bentuk permintaan, kamu bisa memilih perbaikan sesuai masalah hasilnya. Jika hasil terlalu umum, tambahkan context. Jika bentuknya salah, tentukan output. Jika gaya sulit dijelaskan, berikan contoh. Jika ada batasan, tambahkan requirements.", "Sekarang coba: mana yang paling pas untuk meringkas teks menjadi lima poin?\n\n**A.** Instruksi persona panjang dan banyak aturan.\n\n**B.** ‘Ringkas teks ini menjadi lima poin, pertahankan informasi utama.’\n\n**C.** ‘Ringkas.’"], reveal: { paragraphs: ["**B.** Pilihan itu memberi arah yang cukup tanpa beban yang tidak perlu. A menambah aturan yang tidak terkait tugas; C belum menyebut bentuk hasil atau apa yang perlu dipertahankan."] }, },
    ],
    takeaway: "Untuk presentasi lima menit, sebutkan siapa pendengarnya, pesan yang ingin dibawa pulang, dan berapa slide yang kamu butuhkan. Detail yang relevan membuat draf lebih mudah dipakai.",
    check: { question: "Kamu meminta caption santai tetapi hasilnya tetap terasa formal. Apa langkah paling berguna?", choices: [
      { label: "Tambahkan dua contoh caption dengan gaya yang kamu suka.", feedback: "Tepat. Contoh konkret sering lebih mudah ditiru daripada deskripsi gaya yang panjang.", correct: true },
      { label: "Ulangi prompt yang sama beberapa kali.", feedback: "Permintaan yang sama belum memberi petunjuk tentang bagian yang perlu diubah.", correct: false },
      { label: "Tambahkan banyak aturan yang tidak terkait caption.", feedback: "Instruksi yang tidak relevan membuat arah prompt kurang fokus.", correct: false },
    ] },
  },
  {
    lead: "Kamu ingin meminta waktu konsultasi kepada dosen, lalu meminta AI menulis emailnya. Draf yang datang terlalu panjang dan tujuanmu baru muncul di akhir. Bagian mana yang perlu diperbaiki lebih dulu?",
    sections: [
      { title: "Jawaban pertama hanyalah draf", paragraphs: ["Saat membaca email itu lagi, kamu harus mencari-cari kalimat yang benar-benar meminta waktu konsultasi. Berarti masalahnya bukan sekadar panjangnya: tujuan utama tersembunyi. Tandai bagian itu sebelum meminta revisi.\n\n> Draf email — Dengan hormat, melalui surat ini saya bermaksud menyampaikan permohonan untuk dapat mengajukan kesempatan berkonsultasi...", "Kamu bisa menanggapi: ‘Buat nadanya lebih hangat dan alami. Ringkas menjadi maksimal 100 kata, lalu sampaikan permintaan konsultasi dengan jelas.’ Jika pembukanya masih panjang, minta AI langsung menyampaikan tujuan konsultasi.", "Setelah revisi datang, baca lagi seolah kamu penerimanya. Apakah tujuan mudah ditemukan? Apakah nadanya cocok? Dari situ alurnya menjadi **Tulis prompt → Tinjau → Beri masukan → Perbaiki**."], },
      { title: "Arahan spesifik lebih mudah diikuti", paragraphs: ["Untuk email dosen tadi, permintaan ‘buat lebih bagus’ belum menjelaskan bagian mana yang perlu diubah. Sebutkan perubahan yang kamu inginkan: ‘Pindahkan tujuan konsultasi ke paragraf pertama, pertahankan waktu yang saya usulkan, dan ringkas pembukanya.’", "Masalah lain membutuhkan arahan yang berbeda. Jika hasil terlalu umum, tambahkan konteks; jika terlalu panjang, tentukan batasnya; jika klaim tidak didukung, minta AI kembali ke dokumen sumber."], },
      { title: "Aktivitas · pilih arahan revisi", paragraphs: ["AI sudah membuat outline presentasi, tetapi tiap slide terlalu padat. Kamu ingin mempertahankan gagasan utamanya sekaligus membuat isi lebih mudah diikuti. Pilih instruksi yang akan kamu kirim untuk memperbaiki outline."], },
      { title: "Ganti peran AI sesuai tahap kerja", paragraphs: ["Setelah membuat draf email atau presentasi, kamu bisa meminta AI membaca hasilnya dengan tugas berbeda: sebagai peninjau, lalu editor. Minta ia mengkritik draf sebelum menyusun versi baru.", "Jika kamu punya dokumen sumber, berikan dokumen itu dan minta AI menjadikannya sumber utama. Minta rujukan ke bagian dokumen dan instruksikan agar ia mengatakan ‘tidak tersedia di dokumen’ jika informasinya memang tidak ada.", "Tetap buka sumber aslinya sebelum memakai kutipan, angka, atau kesimpulan penting. AI dapat membantu menemukan bagian yang relevan, tetapi tidak menggantikan pemeriksaanmu."], },
      { title: "Aktivitas · susun ulang alurnya", paragraphs: ["Dari draf pertama sampai hasil yang siap dipakai, ada beberapa keputusan kecil. Susun urutannya sebelum melihat contoh jawaban."], },
    ],
    takeaway: "Pada email tadi, pertahankan permintaan konsultasi, pindahkan tujuannya ke awal, dan ringkas pembukanya. Baca kembali hasil revisi sebelum mengirimnya.",
    check: { question: "Hasil AI memuat klaim yang tidak ada di laporan yang kamu unggah. Apa yang sebaiknya kamu minta?", choices: [
      { label: "Gunakan laporan itu sebagai sumber utama dan tandai informasi yang tidak tersedia di dalamnya.", feedback: "Tepat. Instruksi ini membatasi jawaban pada sumber yang dapat kamu periksa.", correct: true },
      { label: "Buat jawabannya terdengar lebih yakin.", feedback: "Nada yakin tidak membuat klaim menjadi benar atau bersumber.", correct: false },
      { label: "Minta AI menambahkan detail sebanyak mungkin.", feedback: "Ini bisa menambah informasi yang tidak didukung dokumen.", correct: false },
    ] },
  },
  {
    lead: "Kelasmu mendapat tugas membuat presentasi tentang energi terbarukan di Indonesia. AI sudah menyiapkan slide, tetapi sumber utamanya membahas negara lain. Kita akan menyusun ulang cara kerjanya supaya kekeliruan seperti ini terlihat lebih awal.",
    sections: [
      { title: "Pecah tugas sebelum meminta hasil akhir", paragraphs: ["Sumber yang keliru tadi baru terlihat ketika slide hampir selesai. Untuk putaran berikutnya, pilih sudut bahasan dan baca sumber lebih dulu. Setelah tahu apa yang benar-benar didukung sumber, susun kerangka, buat draf, minta kritik, lalu perbaiki.", "Setiap langkah memberi kesempatan untuk membetulkan arah lebih awal. Kalau sumber pertama ternyata kurang tepat, kamu bisa menggantinya sebelum seluruh presentasi dibangun di atasnya. Pola ini juga berguna untuk laporan, proposal, dan analisis spreadsheet."], },
      { title: "Contoh alur kerja presentasi", paragraphs: ["Mulai dengan menjelaskan tugasnya: ‘Saya menyiapkan presentasi energi terbarukan untuk mahasiswa tahun pertama. Tujuannya menjelaskan pilihan yang relevan bagi Indonesia.’\n\nSebelum membuat slide, minta empat kemungkinan sudut bahasan beserta kelebihan dan kekurangannya. Pilih satu yang sesuai tugasmu. Baru setelah itu cari sumber yang dapat kamu buka sendiri, bandingkan temuannya, dan catat bagian yang belum pasti.\n\nDengan bahan itu, minta kerangka enam slide. Baca drafnya, minta kritik atas bagian yang belum jelas, lalu revisi. Jika sebuah klaim tidak didukung sumber yang kamu baca, keluarkan dari slide."], },
      { title: "AI bisa membantu di berbagai tahap", paragraphs: ["Dalam presentasi tadi, AI bisa membantu pada tahap berbeda: sebagai **teman mencari ide, pembanding pilihan, pengkritik, penjelas, atau editor**. Kamu bisa mengganti perannya sesuai tahap, tanpa menyerahkan seluruh tugas sekaligus.", "Untuk analisis data survei, contohnya: pahami struktur data → bersihkan nilai yang keliru → cari pola → buat visualisasi → susun kesimpulan → periksa apakah tafsirnya benar. Minta AI menjelaskan asumsi dan batas datanya sebelum memakai kesimpulan."], },
      { title: "Aktivitas · urutkan analisis survei", paragraphs: ["Urutan kerja yang sama bisa dicoba pada data survei. Sebelum meminta kesimpulan, apa yang perlu diperiksa lebih dulu? Susun sendiri dulu, lalu bandingkan."], },
      { title: "Alur kerja juga berguna untuk kegiatan kampus", paragraphs: ["Misalnya organisasi kampusmu hendak mengadakan lokakarya. Mulailah dengan memilih format dan waktu yang mungkin, lalu susun jadwal serta perkiraan biaya. Setelah rencananya masuk akal, AI bisa membantu menulis proposal sponsor dan undangan. Sebelum dikirim, periksa lagi jadwal, anggaran, dan siapa yang harus memberi izin.", "Di setiap langkah, kamu dapat memakai AI dengan peran berbeda: pencari ide, pembanding, pengkritik, penjelas, dan editor. Informasi nyata seperti jadwal, biaya, dan persetujuan tetap perlu dikonfirmasi kepada pihak terkait."], },
      { title: "Aktivitas · cocokkan peran AI", paragraphs: ["Dalam rencana lokakarya tadi, kamu mungkin butuh ide acara pada satu tahap dan kritik anggaran pada tahap lain. Cocokkan tiap kebutuhan dengan peran AI yang sesuai."], },
      { title: "Tantangan akhir · uji ide startup", paragraphs: ["Sekarang gunakan ide layanan karier dari pelajaran sebelumnya sebagai latihan lengkap. Kerjakan tiap tahap dan catat keputusanmu sendiri.\n\n**1 · Petakan masalah.** Minta AI menyusun lima masalah pencarian karier mahasiswa, siapa yang mengalaminya, kapan, dan informasi apa yang perlu diuji lewat wawancara.\n\n**2 · Jelajahi pilihan.** Minta empat kemungkinan solusi: rekomendasi karier, pencocokan magang, peta kesenjangan keterampilan, dan persiapan karier. Bandingkan kelebihan, kekurangan, dan calon penggunanya, dan jangan minta AI memilihkan satu.\n\n**3 · Tantang asumsi.** Minta lima alasan ide bisa gagal, siapa yang tidak membutuhkannya, alternatif yang sudah ada, serta bedakan fakta, asumsi, dan bukti.\n\n**4 · Perbaiki arah.** Pilih satu arah untuk ditinjau. Minta tiga kelemahan dan bukti yang perlu dicari.\n\n**5 · Buat proposal satu halaman.** Masukkan masalah, target pengguna, solusi, nilai yang ditawarkan, asumsi utama, bukti yang ada dan belum ada, serta langkah berikutnya.\n\n**6 · Tinjau sebagai manusia.** Tandai saran AI yang kamu terima, tolak, atau ubah. Pastikan langkah berikutnya dapat diuji, misalnya wawancara mahasiswa, bukan langsung membangun produk."], },
      { title: "Bekal yang dibawa setelah kursus", paragraphs: ["Sebelum memakai hasil AI untuk tugas berikutnya, kembali ke tiga pertanyaan: Apa tujuanmu? Bagian mana yang didukung sumber? Keputusan apa yang harus kamu ambil sendiri? Jika jawabannya belum jelas, lanjutkan percakapan atau periksa bukti sebelum memakai hasilnya.", "Tidak ada prompt ajaib. Arah yang jelas, konteks yang cukup, percakapan bertahap, sumber yang dapat diperiksa, dan penilaian manusia membuat AI lebih berguna."], },
    ],
    takeaway: "Untuk presentasi tadi, pilih sudut bahasan dan baca sumber sebelum meminta draf slide. AI boleh membantu tiap tahap, tetapi kamu yang memutuskan klaim mana yang layak masuk.",
    check: { question: "Kamu mendapat jawaban AI yang terdengar sangat yakin tentang pilihan karier. Apa yang paling tepat dilakukan?", choices: [
      { label: "Periksa asumsi, sumber, bukti, dan apakah cara bertanya ikut mengarahkan jawabannya.", feedback: "Tepat. Keputusanmu perlu mempertimbangkan bukti dan konteks, bukan rasa yakin dari jawaban.", correct: true },
      { label: "Ikuti saja karena AI memberi banyak alasan.", feedback: "Banyak alasan belum tentu didukung bukti atau sesuai keadaanmu.", correct: false },
      { label: "Tanyakan lagi dengan kata-kata sama sampai jawabannya konsisten.", feedback: "Jawaban berulang belum tentu merupakan verifikasi independen.", correct: false },
    ] },
  },
];

export const workingLessons = [workingLessonSets[1], workingLessonSets[0], workingLessonSets[2], workingLessonSets[3]];

const p = (kind: SectionPresentation["kind"], label: string, title: string, items: { title: string; detail: string }[], bridge: string, interactive = false, activity?: Activity, visual?: SectionPresentation["visual"]): SectionPresentation => ({ kind, label, title, items, bridge, interactive, activity, visual });

const workingPresentationSets: SectionPresentation[][] = [
  [
    p("compare", "CONTOH AWAL", "AI yang sama, arah berbeda", [{ title: "Minta dukungan", detail: "Pertanyaan yang mencari persetujuan cenderung mengarahkan percakapan untuk mendukung ide." }, { title: "Minta pengujian", detail: "Pertanyaan netral membuka ruang untuk risiko, bukti, dan informasi yang belum ada." }], "Kita perlu mengenali saat jawaban terasa menyenangkan karena terlalu menyetujui."),
    p("stats", "RISIKO TERLALU MENYETUJUI", "49% lebih sering", [{ title: "11 model", detail: "Riset Science menguji sebelas model AI." }, { title: "2.405 orang", detail: "Studi melibatkan lebih dari dua ribu peserta." }, { title: "51% kasus", detail: "Model menyetujui pengguna ketika konsensus manusia justru menolaknya." }], "Cara bertanya yang lebih netral memberi ruang untuk melihat sisi lain."),
    p("compare", "COBA UBAH FRAMING", "Dari mencari dukungan ke mencari bukti", [], "Prompt netral bukan jaminan jawaban benar, tetapi membantu membuka analisis yang lebih seimbang.", false, { kind: "predict", prompt: "Kamu mempertimbangkan usaha makanan sehat dekat kampus dan belum punya data minat pembeli. Prompt mana yang paling membantu menilai idenya tanpa menganggap asumsi sebagai fakta?", options: [
      { label: "‘Uraikan kebutuhan mahasiswa, persaingan, dan harga makanan sehat di sekitar kampus. Berdasarkan faktor itu, simpulkan apakah usaha ini layak.’", correct: false, feedback: "Analisisnya terdengar menyeluruh, tetapi tetap meminta kesimpulan tegas tanpa membedakan fakta yang tersedia dari hal yang belum diketahui." },
      { label: "‘Bandingkan peluang dan risiko menjual makanan sehat dekat kampus. Tandai informasi yang belum tersedia dan sarankan cara kecil menguji minat calon pembeli sebelum saya mengeluarkan modal.’", correct: true, feedback: "Tepat. Prompt ini meminta dua sisi, memisahkan informasi yang belum ada, dan mengarahkan langkah berikut yang bisa diuji." },
      { label: "‘Tinjau usaha makanan sehat untuk mahasiswa dengan melihat contoh usaha serupa. Jelaskan daya tarik produknya dan cara mengatasi hambatan awal.’", correct: false, feedback: "Contoh usaha serupa dapat memberi gambaran, tetapi prompt ini lebih banyak membahas daya tarik dan tidak meminta pemeriksaan asumsi atau data minat calon pembeli." },
    ], reveal: "Prompt yang seimbang tidak hanya meminta daftar peluang dan risiko. Prompt juga membedakan informasi yang tersedia dari asumsi, lalu mencari cara untuk menguji hal yang belum diketahui." }),
    p("steps", "AKTIVITAS 1", "Periksa jawaban sebelum mengambil keputusan", [], "Setelah melihat apa yang perlu diuji, tentukan langkah saat jawaban AI terdengar yakin tetapi belum memberi bukti.", false, { kind: "predict", prompt: "AI menyimpulkan bahwa usaha makanan sehat dekat kampus akan laku, tetapi tidak menunjukkan data. Langkah mana yang paling membantu sebelum kamu memutuskan?", options: [
      { label: "Minta AI menjelaskan faktor pendukung dan menambahkan perkiraan permintaan berdasarkan usaha sejenis.", correct: false, feedback: "Penjelasan tambahan bisa berguna, tetapi perkiraan dari usaha lain belum membuktikan minat pembeli di kampusmu." },
      { label: "Tanyakan asumsi dan data yang mendasari kesimpulan, lalu uji minat calon pembeli secara langsung.", correct: true, feedback: "Tepat. Kamu memeriksa dasar kesimpulan dan mencari bukti dari calon pengguna, bukan mengandalkan keyakinan AI." },
      { label: "Bandingkan kesimpulan dengan chatbot lain, lalu gunakan jawaban yang paling konsisten.", correct: false, feedback: "Kesepakatan beberapa chatbot bukan bukti independen; semuanya bisa membuat asumsi serupa tanpa data lokal." },
    ], reveal: "Jawaban AI dapat membantu menyusun pertanyaan, tetapi keputusan perlu ditopang informasi yang bisa diperiksa dan bukti dari situasi yang sebenarnya." }),
    p("tiles", "CARI TITIK BUTA", "Lima hal yang perlu diuji", [{ title: "Asumsi", detail: "Apa yang kita anggap benar tanpa memeriksanya?" }, { title: "Kelemahan", detail: "Bagian mana yang paling rentan gagal?" }, { title: "Sanggahan", detail: "Apa alasan orang lain mungkin tidak setuju?" }, { title: "Info yang kurang", detail: "Data apa yang belum kita punya?" }, { title: "Alternatif", detail: "Penjelasan atau solusi lain apa yang mungkin?" }], "Prompt dapat memengaruhi konteks; karena itu sistem juga membutuhkan batas dan perlindungan."),
    p("tiles", "AKTIVITAS 6", "Cocokkan prompt dengan tujuannya", [], "Sekarang lihat mengapa prompt tidak seharusnya dipakai untuk melewati perlindungan.", false, { kind: "arrange", instruction: "Tiap prompt ini membuka titik buta yang berbeda. Cocokkan dengan tujuannya.", items: [{ id: "asumsi", label: "‘Asumsi apa yang belum terbukti?’" }, { id: "lawan", label: "‘Apa argumen terkuat yang menentang keputusan ini?’" }, { id: "pisah", label: "‘Pisahkan fakta, asumsi, dan tafsiran.’" }, { id: "kurang", label: "‘Informasi apa yang masih kurang?’" }], buckets: [{ id: "identifikasi", label: "Mengidentifikasi asumsi" }, { id: "sanggah", label: "Mencari sanggahan" }, { id: "jenis", label: "Memisahkan jenis klaim" }, { id: "cari", label: "Menemukan yang perlu dicari" }], answer: { asumsi: "identifikasi", lawan: "sanggah", pisah: "jenis", kurang: "cari" }, hint: "Bedakan ‘apa yang belum terbukti’ dari ‘apa yang belum kita punya’.", reveal: "Keempatnya membuka titik buta yang berbeda: asumsi yang belum diuji, argumen yang melawan, batas antara fakta dan tafsiran, serta informasi yang masih harus dicari." }),
    p("statement", "KEAMANAN DAN TANGGUNG JAWAB", "Prompt kreatif bukan izin melanggar batas", [{ title: "Pegangan", detail: "Jailbreak mencoba mendorong sistem melewati batas. Gunakan AI secara bertanggung jawab dan jangan menganggap semua perlindungan selalu sempurna." }], "Di pelajaran berikutnya, kita akan memakai percakapan untuk memperbaiki hasil langkah demi langkah."),
    p("compare", "AKTIVITAS 7", "Benar atau salah?", [], "Di penggunaan sehari-hari, hasil pertama sering belum sesuai. Kita bisa memperbaikinya lewat percakapan.", false, { kind: "predict", prompt: "‘Kalau prompt ditulis dengan sangat kreatif, aturan AI boleh diabaikan.’ Benar atau salah?", options: [{ label: "Benar", correct: false, feedback: "Prompt memang bisa memengaruhi respons, tetapi itu bukan alasan aturan boleh diabaikan." }, { label: "Salah", correct: true, feedback: "Tepat. Prompt dapat memengaruhi konteks dan respons, tetapi aturan dan perlindungan sistem tetap perlu dijaga." }], reveal: "Jailbreak menunjukkan bahwa cara permintaan dibingkai dapat memengaruhi respons. Itu alasan sistem perlu perlindungan, bukan izin untuk menembusnya." }),
  ],
  [
    p("compare", "MULAI DARI CONTOH", "Beri informasi yang mengurangi tebakan", [{ title: "‘Buat presentasi tentang AI’", detail: "Topik ada, tetapi audiens, tujuan, durasi, tingkat teknis, dan jumlah slide belum jelas." }, { title: "Presentasi 5 menit untuk mahasiswa non-IT", detail: "Konteks audiens dan batas waktu membantu AI menentukan tingkat penjelasan." }], "Prompt yang lebih jelas dapat dibangun dari tiga bagian sederhana."),
    p("steps", "KERANGKA HARIAN", "Task + Context + Output", [{ title: "Task", detail: "Tugasnya: buat outline presentasi risiko AI." }, { title: "Context", detail: "Audiensnya mahasiswa non-IT yang belum banyak mempelajari AI." }, { title: "Output", detail: "Buat lima slide dengan maksimal tiga poin utama per slide." }, { title: "Requirements", detail: "Tambahkan batas bila perlu: bahasa Indonesia, maksimal 300 kata, tanpa jargon, atau hanya memakai isi dokumen." }], "Aktivitas berikutnya membantu membedakan bagian-bagian itu.", true),
    p("tiles", "AKTIVITAS 2", "Cocokkan potongan prompt", [], "Kita sudah tahu strukturnya; sekarang pilih hanya detail yang diperlukan.", false, { kind: "arrange", instruction: "Tiap potongan prompt ini mengisi satu peran. Cocokkan semuanya.", items: [{ id: "ringkas", label: "‘Buat ringkasan laporan ini.’" }, { id: "audiens", label: "‘Untuk ketua organisasi mahasiswa tanpa latar teknis.’" }, { id: "poin", label: "‘Sajikan dalam lima poin.’" }, { id: "batas", label: "‘Maksimal 150 kata dan jangan menambah informasi.’" }], buckets: [{ id: "task", label: "Task" }, { id: "context", label: "Context" }, { id: "output", label: "Output" }, { id: "requirements", label: "Requirements" }], answer: { ringkas: "task", audiens: "context", poin: "output", batas: "requirements" }, hint: "Bedakan ‘apa hasilnya’ dari ‘batas yang harus dipatuhi’.", reveal: "Task adalah pekerjaannya, Context latar yang membantu AI, Output bentuk hasilnya, dan Requirements batas yang harus dipatuhi. Kerangka ini pengingat, bukan istilah yang harus dihafal." }),
    p("compare", "CUKUPKAN SEPERLUNYA", "Prompt panjang tidak otomatis lebih baik", [{ title: "Terlalu minim", detail: "‘Ringkas.’ Tidak menyebut bentuk atau hal yang perlu dipertahankan." }, { title: "Cukup jelas", detail: "Ringkas teks menjadi lima poin, pertahankan informasi utama, jangan menambahkan informasi baru." }, { title: "Terlalu banyak", detail: "Instruksi persona panjang yang tidak terkait tugas membuat prompt kurang fokus." }], "Untuk pekerjaan komunikasi yang lebih rumit, kerangka lebih rinci dapat membantu."),
    p("steps", "CO-STAR DAN FEW-SHOT", "Pilih alat sesuai kebutuhan", [{ title: "CO-STAR", detail: "Context, Objective, Style, Tone, Audience, Response. Berguna untuk draf sponsor seminar: tujuan, pembaca, nada ramah-profesional, maksimal 200 kata, dan ajakan bertemu." }, { title: "Few-shot prompting", detail: "Sertakan dua caption contoh agar AI menangkap panjang, struktur, dan gaya yang diinginkan." }, { title: "Aktivitas 4", detail: "Umum → tambah context; format salah → tentukan output; gaya sulit dijelaskan → beri contoh; batas tertentu → tambah requirements." }], "Tidak semua prompt perlu framework. Tanyakan informasi apa yang masih kurang."),
    p("tiles", "AKTIVITAS 4", "Cocokkan masalah dengan perbaikannya", [], "Tidak semua prompt perlu framework. Tanyakan informasi apa yang masih kurang.", false, { kind: "arrange", instruction: "Tiap keluhan tentang hasil AI punya perbaikan yang paling pas. Cocokkan.", items: [{ id: "umum", label: "Hasilnya terlalu umum" }, { id: "format", label: "Bentuk hasilnya tidak sesuai" }, { id: "gaya", label: "Gayanya sulit dijelaskan dengan kata-kata" }, { id: "batas", label: "Ada batas yang harus dipatuhi" }], buckets: [{ id: "context", label: "Tambah context" }, { id: "output", label: "Tentukan output" }, { id: "contoh", label: "Beri contoh" }, { id: "requirements", label: "Tambah requirements" }], answer: { umum: "context", format: "output", gaya: "contoh", batas: "requirements" }, hint: "Kalau gayanya sulit dijelaskan, tunjukkan contohnya.", reveal: "Hasil umum butuh konteks, bentuk yang salah butuh output yang ditentukan, gaya yang sulit dijelaskan butuh contoh, dan batas butuh requirements." }),
  ],
  [
    p("steps", "PUTARAN PERBAIKAN", "Tulis prompt → Tinjau → Beri masukan → Perbaiki", [{ title: "Tulis prompt", detail: "Minta draf email kepada dosen untuk konsultasi." }, { title: "Tinjau", detail: "Hasil terlalu formal dan panjang." }, { title: "Beri masukan", detail: "Minta nada lebih hangat dan alami, maksimal 100 kata." }, { title: "Perbaiki", detail: "Minta revisi yang tetap menyampaikan permintaan konsultasi dengan jelas." }], "Masukan akan lebih berguna jika menyebut perubahan secara spesifik."),
    p("tiles", "TINJAU HASIL", "Apa yang perlu diperiksa?", [{ title: "Kepanjangan atau umum", detail: "Tentukan batas panjang atau tambahkan konteks." }, { title: "Nada dan format", detail: "Jelaskan gaya atau bentuk yang kamu perlukan." }, { title: "Ada yang hilang", detail: "Tunjuk bagian yang harus dipertahankan atau dilengkapi." }, { title: "Klaim tanpa dukungan", detail: "Minta sumber atau batasi jawaban pada dokumen." }], "Gunakan instruksi yang memberi arah konkret untuk revisi."),
    p("compare", "AKTIVITAS 8", "Pilih arahan revisi", [], "Kamu juga bisa meminta AI berganti peran: dari pembuat menjadi peninjau atau editor.", false, { kind: "predict", prompt: "Instruksi mana yang paling membantu AI memperbaiki outline tanpa mengubah gagasan utamanya?", options: [
      { label: "‘Ringkas isi tiap slide agar audiens lebih mudah mengikuti alurnya. Pertahankan urutan topik yang sekarang.’", correct: false, feedback: "Tujuan dan bagian yang dipertahankan sudah disebut, tetapi belum ada batas atau arahan tentang ke mana rincian perlu dipindahkan." },
      { label: "‘Pertahankan gagasan utama dan urutan slide. Batasi isi tiap slide menjadi tiga poin; pindahkan bukti rinci ke catatan pembicara.’", correct: true, feedback: "Tepat. Arahan ini menjaga bagian yang sudah benar, memberi batas yang bisa diperiksa, dan menjelaskan tempat untuk rincian." },
      { label: "‘Kurangi teks yang berulang, buat tiap slide lebih visual, dan gunakan catatan pembicara untuk informasi tambahan.’", correct: false, feedback: "Arahan ini punya langkah konkret, tetapi ‘lebih visual’ belum menentukan batas isi dan pengurangan rincian yang diperlukan." },
    ], reveal: "Arahan revisi yang jelas menyebut bagian yang dipertahankan, perubahan yang bisa diperiksa, dan apa yang perlu dilakukan terhadap rincian." }),
    p("steps", "GUNAKAN SUMBER", "Minta jawaban berpijak pada dokumen", [{ title: "Tetapkan sumber", detail: "Gunakan dokumen yang saya unggah sebagai sumber utama." }, { title: "Batasi tambahan", detail: "Jangan menambahkan informasi yang tidak tercantum." }, { title: "Tandai kekosongan", detail: "Jika informasi tidak ada, katakan bahwa informasi itu tidak tersedia di dokumen." }, { title: "Periksa ulang", detail: "Buka dokumen dan cocokkan rujukan sebelum menggunakan klaim." }], "Aktivitas berikut merangkum urutan perbaikan yang dapat kamu pakai."),
    p("steps", "AKTIVITAS 9-10", "Dari prompt sampai pemeriksaan akhir", [], "Selanjutnya, susun satu alur kerja dari permintaan awal hingga hasilnya siap dipakai.", false, { kind: "arrange", instruction: "Urutkan lima langkah, dari permintaan awal sampai pemeriksaan akhir.", items: [{ id: "masukan", label: "Beri arahan: sebutkan perubahan yang perlu dilakukan" }, { id: "cek", label: "Periksa ulang: pastikan klaimnya didukung" }, { id: "prompt", label: "Tulis prompt: jelaskan kebutuhan dan sumbernya" }, { id: "revisi", label: "Minta revisi: minta AI menerapkan arahanmu" }, { id: "tinjau", label: "Tinjau hasil: cari masalah yang paling penting" }], answer: ["prompt", "tinjau", "masukan", "revisi", "cek"], hint: "Kamu perlu membaca drafnya sebelum bisa menentukan perubahan yang dibutuhkan.", reveal: "Tulis prompt → Tinjau hasil → Beri arahan → Minta revisi → Periksa ulang. Alur ini dimulai dari permintaan awal dan berakhir saat kamu memastikan hasilnya sudah layak dipakai." }),
  ],
  [
    p("steps", "PRESENTASI ENERGI TERBARUKAN", "Pecah pekerjaan besar", [{ title: "Brief dan sudut", detail: "Tentukan audiens dan tujuan; minta beberapa sudut bahasan tanpa menyuruh AI memilih." }, { title: "Sumber dan perbandingan", detail: "Cari sumber tepercaya, ringkas tiap sumber, lalu bandingkan temuan dan perbedaannya." }, { title: "Outline dan draf", detail: "Buat alur enam slide, lalu kembangkan draf berdasarkan outline." }, { title: "Kritik dan revisi", detail: "Minta kritik pada bukti dan kejelasan; revisi, lalu buka sumber asli." }], "Alur serupa dapat dipakai untuk menganalisis data survei."),
    p("steps", "CONTOH LANGKAH PRESENTASI", "Dari brief hingga revisi", [{ title: "Pahami dan tentukan sudut", detail: "Jelaskan tujuan dan audiens; minta empat sudut bahasan, bandingkan manfaat dan kekurangannya tanpa memilih satu." }, { title: "Baca sumber", detail: "Minta sumber tepercaya, ringkas temuan tiap sumber, lalu bandingkan bagian yang berbeda." }, { title: "Susun dan tulis", detail: "Minta alur presentasi enam slide, lalu buat draf dari alur itu." }, { title: "Kritik dan perbaiki", detail: "Minta peninjauan atas kejelasan dan bukti, perbaiki draf, lalu buka sumber aslinya." }], "Langkah-langkah kecil juga membantu saat mengolah hasil survei."),
    p("compare", "GANTI PERAN SESUAI TAHAP", "Pencari ide · pembanding · pengkritik · editor", [{ title: "Cari ide", detail: "Minta beberapa pilihan tanpa meminta AI memutuskan." }, { title: "Bandingkan", detail: "Minta kelebihan, kekurangan, dan trade-off tiap opsi." }, { title: "Periksa", detail: "Minta kritik, penjelasan, atau penyuntingan sesuai kebutuhan." }, { title: "Analisis data", detail: "Untuk survei, pahami struktur, bersihkan, cari pola, visualisasikan, simpulkan, lalu periksa tafsir." }], "Sekarang susun urutan analisis survei."),
    p("steps", "AKTIVITAS 11", "Urutkan analisis data survei", [], "AI juga dapat membantu merancang kegiatan kampus dari awal sampai evaluasi.", false, { kind: "arrange", instruction: "Susun langkah menganalisis data survei.", items: [{ id: "pola", label: "Cari pola: eksplorasi kecenderungan dan kelompok" }, { id: "simpul", label: "Simpulkan dan cek: tulis temuan, sebutkan batas data" }, { id: "bersih", label: "Bersihkan: tinjau nilai kosong, ganda, atau keliru" }, { id: "struktur", label: "Pahami struktur: ketahui kolom dan arti datanya" }, { id: "visual", label: "Visualisasikan: pilih grafik yang membantu pembaca" }], answer: ["struktur", "bersih", "pola", "visual", "simpul"], hint: "Jangan mencari pola pada data yang belum kamu pahami.", reveal: "Pahami struktur → Bersihkan → Cari pola → Visualisasikan → Simpulkan dan cek. Melompat ke kesimpulan sebelum tahu isi datanya adalah kesalahan yang paling mahal." }),
    p("tiles", "WORKSHOP KAMPUS", "Satu kegiatan, beberapa tahap", [{ title: "Rancang", detail: "Cari ide, bandingkan format, dan susun jadwal." }, { title: "Siapkan", detail: "Perkirakan anggaran, tinjau risiko, buat proposal sponsor." }, { title: "Ajak peserta", detail: "Siapkan pesan undangan dan materi promosi." }, { title: "Tinjau", detail: "Konfirmasi jadwal, biaya, izin, dan kesiapan dengan pihak terkait." }], "Di tiap tahap, pilih peran AI yang sesuai dengan kebutuhanmu."),
    p("compare", "AKTIVITAS 12", "Pilih peran AI", [], "Sekarang terapkan semua tahap itu pada tantangan akhir.", false, { kind: "arrange", instruction: "Cocokkan tiap kebutuhan dengan peran AI yang paling pas.", items: [{ id: "usul", label: "Kamu butuh beberapa kemungkinan untuk dipilih" }, { id: "timbang", label: "Kamu butuh kelebihan dan kekurangan tiap opsi" }, { id: "risiko", label: "Kamu butuh risiko dan asumsi yang belum kamu lihat" }, { id: "sederhana", label: "Kamu butuh konsep rumit dijelaskan sederhana" }, { id: "rapikan", label: "Kamu butuh tulisan yang lebih jelas tanpa berubah maksud" }], buckets: [{ id: "pencari", label: "Pencari ide" }, { id: "pembanding", label: "Pembanding" }, { id: "pengkritik", label: "Pengkritik" }, { id: "penjelas", label: "Penjelas" }, { id: "editor", label: "Editor" }], answer: { usul: "pencari", timbang: "pembanding", risiko: "pengkritik", sederhana: "penjelas", rapikan: "editor" }, hint: "Pembanding menata pilihan yang sudah ada; pengkritik mencari yang belum kamu lihat.", reveal: "Peran yang kamu minta menentukan bentuk jawabannya. Menyebut peran di awal lebih cepat daripada memperbaiki jawaban yang salah bentuk." }),
    p("steps", "TANTANGAN AKHIR", "Uji ide layanan karier mahasiswa", [{ title: "Petakan dan jelajahi", detail: "Minta lima masalah karier, siapa yang mengalaminya dan apa yang perlu diuji; bandingkan empat arah solusi tanpa memilih otomatis." }, { title: "Tantang asumsi", detail: "Minta alasan ide bisa gagal, calon pengguna yang tidak membutuhkan, alternatif, serta pisahkan fakta, asumsi, dan bukti." }, { title: "Perbaiki dan susun proposal", detail: "Pilih arah; minta tiga kelemahan dan bukti yang perlu dicari. Buat proposal satu halaman: masalah, target, solusi, nilai, asumsi, bukti yang ada/belum ada, langkah berikutnya." }, { title: "Putuskan sebagai manusia", detail: "Catat saran yang diterima, ditolak, dan diubah. Pastikan langkah berikutnya dapat diuji, misalnya wawancara mahasiswa." }], "Gunakan daftar singkat ini setiap kali bekerja dengan AI."),
    p("statement", "PEGANGAN TERAKHIR", "Tidak ada prompt ajaib", [{ title: "Sebelum memakai hasil", detail: "Periksa tujuan, konteks, asumsi, masukan, sumber, bukti, dan keputusan yang tetap menjadi tanggung jawabmu." }], "Kamu sudah menyelesaikan Working with Generative AI."),
  ],
];

export const workingPresentations = [workingPresentationSets[1], workingPresentationSets[0], workingPresentationSets[2], workingPresentationSets[3]];
